import { MapPin, ShieldCheck, Building2 } from "lucide-react";
import { RouteLandingPage, RoutePageData } from "./route-landing-page";

const data: RoutePageData = {
  ru: {
    badge: "Трансфер в Лодзь",
    title: "Минск — Лодзь",
    subtitle: "Прямой трансфер из Минска в Лодзь — польский город творческих кварталов и промышленного наследия. Улица Пётрковска, огромный арт-комплекс «Мануфактура» в кирпичных стенах XIX века и всемирно известная киношкола.",
    stats: [
      { label: "Расстояние", value: "~650 км" },
      { label: "Время в пути", value: "7–9 ч" },
      { label: "Граница", value: "Беларусь–Польша" },
      { label: "Класс авто", value: "Бизнес / Минивэн" },
    ],
    photosTitle: "Лодзь — достопримечательности",
    photos: [
      { src: "/img/lodz/piotrkowska-street.png", caption: "Улица Пётрковска — одна из длиннейших торговых улиц Европы (~4,2 км)" },
      { src: "/img/lodz/manufaktura.png", caption: "«Мануфактура» — бывший текстильный завод И. Познанского, сегодня арт- и торговый центр" },
      { src: "/img/lodz/poznanski-palace.png", caption: "Дворец Израэля Познанского — необарочный шедевр промышленной эпохи" },
    ],
    howTitle: "Как проходит поездка",
    steps: [
      { icon: MapPin, title: "Выезд из Минска", desc: "Водитель заберёт вас по указанному адресу в Минске и направится к польской границе по оптимальному маршруту." },
      { icon: ShieldCheck, title: "Граница Беларусь–Польша", desc: "Переход Брузги / Кузница или Берёза / Половцы. Водитель знает актуальные очереди и помогает на КПП." },
      { icon: Building2, title: "Лодзь: любой адрес", desc: "Довезём до отеля у Пётрковской, аэропорта LCJ или любого другого адреса в городе." },
    ],
    infoTitle: "Детали маршрута",
    infoRows: [
      { label: "Маршрут", value: "Минск → Брест → Тересполь → Варшава → Лодзь" },
      { label: "Расстояние", value: "~650 км" },
      { label: "Пограничный переход", value: "Брузги / Кузница или Берёза / Половцы (Беларусь–Польша)" },
      { label: "Время пересечения границы", value: "1–8 ч в зависимости от сезона и очереди" },
      { label: "Необходимые документы", value: "Виза Шенген, загранпаспорт" },
      { label: "Аэропорт Лодзи", value: "LCJ (им. Владислава Реймонта) — 6 км от центра" },
    ],
    includedTitle: "Что включено",
    included: [
      "Подача от адреса в Минске",
      "Прямой маршрут без пересадок",
      "Помощь водителя на границе",
      "Питьевая вода и комфортный салон",
      "Детские кресла по запросу",
      "Фиксированная цена без счётчика",
    ],
    whyTitle: "Почему ComfortLine",
    whyItems: [
      "Опытные водители маршрута Минск–Польша",
      "Знание актуальных очередей на границе",
      "Возможна остановка в Варшаве по дороге (~130 км от Лодзи)",
      "Обратный трансфер: из Лодзи в Минск",
      "Работаем 24/7, включая праздники",
      "Перевозим с детьми и питомцами",
    ],
    faqTitle: "Часто задаваемые вопросы",
    faq: [
      { q: "Какой маршрут до Лодзи?", a: "Едем через Брест — КПП Брузги/Кузница или Берёза/Половцы — Варшаву — Лодзь. Расстояние около 650 км, время в пути 7–9 ч без учёта границы." },
      { q: "Нужна ли виза в Польшу?", a: "Гражданам Беларуси требуется шенгенская виза. Уточняйте актуальные требования в посольстве Польши или на официальных сайтах перед поездкой." },
      { q: "Что такое «Мануфактура»?", a: "Manufaktura — один из крупнейших арт- и торговых центров Польши, расположенный в отреставрированных кирпичных корпусах хлопкопрядильной фабрики Израэля Познанского XIX века. Здесь музеи, кинотеатры, рестораны и огромная площадь для мероприятий." },
      { q: "Можно ли остановиться в Варшаве по дороге?", a: "Да — Варшава находится примерно в 130 км от Лодзи, маршрут проходит через неё. Остановка почти не удлиняет поездку — договоритесь с менеджером при бронировании." },
    ],
    ctaTitle: "Заказать трансфер Минск–Лодзь",
    ctaDesc: "Оставьте заявку — менеджер свяжется с вами в ближайшее время и назовёт точную стоимость.",
    ctaBtn: "Оставить заявку",
    prefilledFrom: "Минск",
    prefilledTo: "Лодзь",
    backBtn: "← Трансферы в Польшу",
  },
  en: {
    badge: "Łódź Transfer",
    title: "Minsk — Łódź",
    subtitle: "Direct private transfer from Minsk to Łódź — Poland's creative capital of industrial heritage. Piotrkowska Street, the vast Manufaktura arts complex inside 19th-century brick walls and the world-famous Łódź Film School.",
    stats: [
      { label: "Distance", value: "~650 km" },
      { label: "Travel time", value: "7–9 hrs" },
      { label: "Border", value: "Belarus–Poland" },
      { label: "Vehicle class", value: "Business / Minivan" },
    ],
    photosTitle: "Łódź — Highlights",
    photos: [
      { src: "/img/lodz/piotrkowska-street.png", caption: "Piotrkowska Street — one of Europe's longest commercial boulevards (~4.2 km)" },
      { src: "/img/lodz/manufaktura.png", caption: "Manufaktura — Poznański's former cotton mill, now a landmark arts and shopping complex" },
      { src: "/img/lodz/poznanski-palace.png", caption: "Izrael Poznański Palace — neo-baroque masterpiece of the industrial era" },
    ],
    howTitle: "How the transfer works",
    steps: [
      { icon: MapPin, title: "Departure from Minsk", desc: "Your driver picks you up at your Minsk address and heads for the Polish border via the fastest route." },
      { icon: ShieldCheck, title: "Belarus–Poland border", desc: "Bruzgi / Kuźnica or Berёza / Połowce crossing. Your driver knows current queue conditions and assists at the checkpoint." },
      { icon: Building2, title: "Łódź — any address", desc: "We drop you at your hotel near Piotrkowska Street, Łódź Airport (LCJ) or any other address in the city." },
    ],
    infoTitle: "Route Details",
    infoRows: [
      { label: "Route", value: "Minsk → Brest → Terespol → Warsaw → Łódź" },
      { label: "Distance", value: "~650 km" },
      { label: "Border crossing", value: "Bruzgi / Kuźnica or Berёza / Połowce (Belarus–Poland)" },
      { label: "Border crossing time", value: "1–8 hrs depending on season and queues" },
      { label: "Documents required", value: "Schengen visa, valid passport" },
      { label: "Łódź Airport", value: "LCJ (Władysław Reymont Airport) — 6 km from the centre" },
    ],
    includedTitle: "What's included",
    included: [
      "Pickup from your Minsk address",
      "Direct route — no transfers",
      "Driver assistance at the border",
      "Bottled water and comfortable cabin",
      "Child seats on request",
      "Fixed price — no meter, no surprises",
    ],
    whyTitle: "Why ComfortLine",
    whyItems: [
      "Experienced drivers on the Minsk–Poland route",
      "Up-to-date knowledge of border queue conditions",
      "Optional Warsaw stopover en route (~130 km from Łódź)",
      "Return transfer Łódź → Minsk also available",
      "Available 24/7 including public holidays",
      "Kids and pets welcome",
    ],
    faqTitle: "Frequently asked questions",
    faq: [
      { q: "What is the route to Łódź?", a: "We go via Brest – Bruzgi/Kuźnica or Berёza/Połowce border crossing – Warsaw – Łódź. Total distance is about 650 km, travel time 7–9 hours excluding the border stop." },
      { q: "Do I need a visa to enter Poland?", a: "Citizens of Belarus require a Schengen visa. Please check the latest requirements with the Polish embassy or official sources before travelling." },
      { q: "What is Manufaktura?", a: "Manufaktura is one of Poland's largest arts and entertainment complexes, built inside the meticulously restored 19th-century red-brick factory halls of Izrael Poznański's cotton mill. It houses museums, cinemas, restaurants and a huge events square." },
      { q: "Can we stop in Warsaw on the way?", a: "Yes — Warsaw is about 130 km from Łódź and the route passes through it. A stop adds very little extra time; just let the manager know when booking." },
    ],
    ctaTitle: "Book Minsk–Łódź Transfer",
    ctaDesc: "Submit a request and our manager will contact you shortly with an exact price.",
    ctaBtn: "Request a booking",
    prefilledFrom: "Minsk",
    prefilledTo: "Łódź",
    backBtn: "← Poland transfers",
  },
  seo: {
    titleRu: "Трансфер Минск — Лодзь | Польский город кино и моды | ComfortLine",
    titleEn: "Minsk to Łódź Transfer | Poland's Creative Capital | ComfortLine",
    descRu: "Прямой трансфер из Минска в Лодзь. ~650 км, 7–9 ч. Пётрковска, Мануфактура, киношкола. Граница Беларусь–Польша, фиксированная цена.",
    descEn: "Direct transfer from Minsk to Łódź. ~650 km, 7–9 hrs. Piotrkowska Street, Manufaktura, Film School. Belarus–Poland border crossing, fixed price.",
    pathRu: "/трансфер-минск-лодзь",
    pathEn: "/minsk-lodz-transfer",
    breadcrumbRu: "Трансфер Минск–Лодзь",
    breadcrumbEn: "Minsk — Łódź",
    fromName: "Минск",
    toName: "Лодзь",
  },
};

export default function MinskLodzTransferPage() {
  return <RouteLandingPage data={data} />;
}
