import { MapPin, ShieldCheck, Castle } from "lucide-react";
import { RouteLandingPage, RoutePageData } from "./route-landing-page";

const data: RoutePageData = {
  ru: {
    badge: "Трансфер в Тракай",
    title: "Минск — Тракай",
    subtitle: "Прямой трансфер из Минска в Тракай — средневековый замок на острове, священные озёра и уникальная культура крымских евреев-караимов.",
    stats: [
      { label: "Расстояние", value: "~170 км" },
      { label: "Время в пути", value: "2–4 ч" },
      { label: "Граница", value: "Беларусь–Литва" },
      { label: "Класс авто", value: "Бизнес / Минивэн" },
    ],
    photosTitle: "Тракай — достопримечательности",
    photos: [
      { src: "/img/trakai/island-castle.png", caption: "Тракайский замок — готическая крепость XIV века на острове" },
      { src: "/img/trakai/lake-galve.png", caption: "Озеро Гальве — визитная карточка Тракая" },
      { src: "/img/trakai/old-town.png", caption: "Старый город — традиционные дома общины Кaраимов" },
    ],
    howTitle: "Как проходит поездка",
    steps: [
      { icon: MapPin, title: "Выезд из Минска", desc: "Водитель заберёт вас в указанном месте в Минске и выдвинется к литовской границе по оптимальному маршруту." },
      { icon: ShieldCheck, title: "Граница Беларусь–Литва", desc: "Переход Медининкай / Шальчининкай. Водитель знает актуальные очереди и помогает на КПП." },
      { icon: Castle, title: "Тракай: замок и озёра", desc: "Довезём до центра Тракая, паромной переправы на остров или любого адреса. Возможна остановка в Вильнюсе по дороге." },
    ],
    infoTitle: "Детали маршрута",
    infoRows: [
      { label: "Маршрут", value: "Минск → Молодечно → Медининкай → Вильнюс → Тракай" },
      { label: "Расстояние", value: "~170 км" },
      { label: "Пограничный переход", value: "Медининкай / Шальчининкай (Беларусь–Литва)" },
      { label: "Время пересечения границы", value: "30 мин – 4 ч в зависимости от очереди" },
      { label: "Необходимые документы", value: "Виза Шенген (для граждан не ЕС), загранпаспорт" },
      { label: "Расстояние от Вильнюса", value: "~28 км (30 мин)" },
    ],
    includedTitle: "Что включено",
    included: [
      "Подача от адреса в Минске",
      "Прямой маршрут без пересадок",
      "Помощь водителя на границе",
      "Питьевая вода и комфортный салон",
      "Детские кресла по запросу",
      "Фиксированная цена без счётчика",
    ],
    whyTitle: "Почему ComfortLine",
    whyItems: [
      "Опытные водители маршрута Минск–Литва",
      "Знание актуальных очередей на границе",
      "Возможна остановка в Вильнюсе по дороге",
      "Обратный трансфер: из Тракая в Минск",
      "Работаем 24/7, включая праздники",
      "Перевозим с детьми и питомцами",
    ],
    faqTitle: "Часто задаваемые вопросы",
    faq: [
      { q: "Какой маршрут до Тракая?", a: "Едем через Молодечно — Ошмяны — КПП Медининкай/Шальчининкай — Вильнюс — Тракай. Расстояние около 170 км, время в пути 2–4 ч без учёта границы." },
      { q: "Нужна ли виза в Литву?", a: "Гражданам Беларуси требуется шенгенская виза или национальная виза Литовской Республики. Уточняйте актуальные требования в посольстве или на официальных сайтах." },
      { q: "Можно ли заехать в Вильнюс по дороге?", a: "Да, Вильнюс находится всего в 28 км от Тракая. Мы можем сделать остановку — договоритесь с менеджером при бронировании, доплата по согласованию." },
      { q: "Удобно ли ехать в Тракай на один день?", a: "Да, Тракай — отличный вариант для однодневного путешествия из Минска. Замок, озёра и обед с национальными кибинаями — всё можно уместить в один день." },
    ],
    ctaTitle: "Заказать трансфер Минск–Тракай",
    ctaDesc: "Оставьте заявку — менеджер свяжется с вами в ближайшее время и назовёт точную стоимость.",
    ctaBtn: "Оставить заявку",
    prefilledFrom: "Минск",
    prefilledTo: "Тракай",
    backBtn: "← Трансферы в Литву",
  },
  en: {
    badge: "Trakai Transfer",
    title: "Minsk — Trakai",
    subtitle: "Direct private transfer from Minsk to Trakai — a medieval island castle, sacred lakes and the unique culture of the Karaim people, just 28 km from Vilnius.",
    stats: [
      { label: "Distance", value: "~170 km" },
      { label: "Travel time", value: "2–4 hrs" },
      { label: "Border", value: "Belarus–Lithuania" },
      { label: "Vehicle class", value: "Business / Minivan" },
    ],
    photosTitle: "Trakai — Highlights",
    photos: [
      { src: "/img/trakai/island-castle.png", caption: "Trakai Island Castle — 14th-century Gothic fortress" },
      { src: "/img/trakai/lake-galve.png", caption: "Lake Galvė — the iconic backdrop of Trakai" },
      { src: "/img/trakai/old-town.png", caption: "Old town — traditional Karaim community houses" },
    ],
    howTitle: "How the transfer works",
    steps: [
      { icon: MapPin, title: "Departure from Minsk", desc: "Your driver picks you up at your Minsk address and heads for the Lithuanian border via the fastest route." },
      { icon: ShieldCheck, title: "Belarus–Lithuania border", desc: "Medininkai / Šalčininkai crossing. Your driver knows current queue conditions and assists at the checkpoint." },
      { icon: Castle, title: "Trakai — castle & lakes", desc: "We drop you at the town centre, the ferry crossing to the island, or any address. A Vilnius stopover on the way is also possible." },
    ],
    infoTitle: "Route Details",
    infoRows: [
      { label: "Route", value: "Minsk → Maladzyechna → Medininkai → Vilnius → Trakai" },
      { label: "Distance", value: "~170 km" },
      { label: "Border crossing", value: "Medininkai / Šalčininkai (Belarus–Lithuania)" },
      { label: "Border crossing time", value: "30 min – 4 hrs depending on queues" },
      { label: "Documents required", value: "Schengen visa (non-EU citizens), valid passport" },
      { label: "Distance from Vilnius", value: "~28 km (30 min)" },
    ],
    includedTitle: "What's included",
    included: [
      "Pickup from your Minsk address",
      "Direct route — no transfers",
      "Driver assistance at the border",
      "Bottled water and comfortable cabin",
      "Child seats on request",
      "Fixed price — no meter, no surprises",
    ],
    whyTitle: "Why ComfortLine",
    whyItems: [
      "Experienced drivers on the Minsk–Lithuania route",
      "Up-to-date knowledge of border queue conditions",
      "Optional Vilnius stopover on the way",
      "Return transfer Trakai → Minsk also available",
      "Available 24/7 including public holidays",
      "Kids and pets welcome",
    ],
    faqTitle: "Frequently asked questions",
    faq: [
      { q: "What is the route to Trakai?", a: "We go via Maladzyechna – Ashmyany – Medininkai/Šalčininkai border crossing – Vilnius – Trakai. Total distance is about 170 km, travel time 2–4 hours excluding the border stop." },
      { q: "Do I need a visa to enter Lithuania?", a: "Citizens of Belarus require a Schengen visa or a Lithuanian national visa. Please check the latest requirements with the embassy or official sources before travelling." },
      { q: "Can we stop in Vilnius on the way?", a: "Yes — Vilnius is only 28 km from Trakai. We can easily add a Vilnius stop; just let the manager know when booking. An additional charge may apply." },
      { q: "Is Trakai good for a day trip from Minsk?", a: "Absolutely — the castle, lakes and a lunch of traditional Karaim kibinai can all fit into one day. We can arrange pickup for the return journey at any time." },
    ],
    ctaTitle: "Book Minsk–Trakai Transfer",
    ctaDesc: "Submit a request and our manager will contact you shortly with an exact price.",
    ctaBtn: "Request a booking",
    prefilledFrom: "Minsk",
    prefilledTo: "Trakai",
    backBtn: "← Lithuania transfers",
  },
  seo: {
    titleRu: "Трансфер Минск — Тракай | Замок на острове | ComfortLine",
    titleEn: "Minsk to Trakai Transfer | Island Castle Day Trip | ComfortLine",
    descRu: "Прямой трансфер из Минска в Тракай. ~170 км, 2–4 ч. Средневековый замок на острове, озеро Гальве, культура Kaраимов. Фиксированная цена, граница Беларусь–Литва.",
    descEn: "Direct transfer from Minsk to Trakai. ~170 km, 2–4 hrs. Medieval island castle, Lake Galvė, Karaim culture. Fixed price, Belarus–Lithuania border crossing.",
    pathRu: "/трансфер-минск-тракай",
    pathEn: "/minsk-trakai-transfer",
    breadcrumbRu: "Трансфер Минск–Тракай",
    breadcrumbEn: "Minsk — Trakai",
    fromName: "Минск",
    toName: "Тракай",
  },
};

export default function MinskTrakaiTransferPage() {
  return <RouteLandingPage data={data} />;
}
