import { MapPin, Route, Navigation } from "lucide-react";
import { RouteLandingPage, RoutePageData } from "./route-landing-page";


const data: RoutePageData = {
  ru: {
    badge: "Трансфер по Беларуси",
    title: "Трансферы по Беларуси",
    subtitle: "Брест, Гродно, Витебск, Гомель, Могилёв и замки Несвиж / Мир — межгородские поездки по всей Беларуси на комфортабельном автомобиле.",
    stats: [
      { label: "Города", value: "6 областей" },
      { label: "Брест", value: "~350 км" },
      { label: "Гродно", value: "~280 км" },
      { label: "Класс авто", value: "Бизнес / SUV" },
    ],
    photosTitle: "Беларусь — природа и замки",
    photos: [
      { src: "https://thumbs.dreamstime.com/b/old-fortress-4939650.jpg", caption: "Замок Мир" },
      { src: "https://ichef.bbci.co.uk/ace/standard/976/cpsprodpb/14834/production/_89902048_89902047.jpg", caption: "Беловежская пуща" },
      { src: "https://belarus365.com/wp-content/uploads/2022/04/nesv_start.jpg", caption: "Замок Несвиж" },
    ],
    howTitle: "Как проходит поездка",
    steps: [
      { icon: MapPin, title: "Подача от двери", desc: "Водитель забирает вас в Минске по указанному адресу в назначенное время." },
      { icon: Route, title: "Комфортный путь", desc: "Современные трассы Беларуси, климат-контроль, вода — без пересадок и ожиданий." },
      { icon: Navigation, title: "Точное прибытие", desc: "Доставка прямо в нужный адрес города назначения." },
    ],
    infoTitle: "Популярные маршруты",
    infoRows: [
      { label: "Минск — Брест", value: "~350 км, 3,5–4 ч" },
      { label: "Минск — Гродно", value: "~280 км, 3–3,5 ч" },
      { label: "Минск — Витебск", value: "~265 км, 2,5–3 ч" },
      { label: "Минск — Гомель", value: "~305 км, 3–4 ч" },
      { label: "Минск — Несвиж / Мир", value: "~100–120 км, 1,5 ч" },
      { label: "Минск — Могилёв", value: "~195 км, 2–2,5 ч" },
    ],
    includedTitle: "Что включено",
    included: [
      "Подача от адреса в Минске",
      "Прямой маршрут без пересадок",
      "Питьевая вода и чистый салон",
      "Помощь с багажом",
      "Детские кресла по запросу",
      "Фиксированная цена без счётчика",
    ],
    whyTitle: "Почему ComfortLine",
    whyItems: [
      "Опытные водители знают дороги Беларуси",
      "Прямая подача без таксопарков и диспетчеров",
      "Доступны большие автомобили для групп",
      "Работаем 24/7, включая праздники",
      "Фиксированные цены: никаких сюрпризов",
      "Более 5 000 выполненных поездок с 2015 года",
    ],
    ctaTitle: "Заказать трансфер по Беларуси",
    ctaDesc: "Оставьте заявку — менеджер свяжется и назовёт точную стоимость вашего маршрута.",
    ctaBtn: "Оставить заявку",
    prefilledFrom: "Минск",
    prefilledTo: "Беларусь (межгород)",
    backBtn: "← Все услуги",
  },
  en: {
    badge: "Belarus Transfer",
    title: "Belarus Intercity Transfers",
    subtitle: "Brest, Grodno, Vitebsk, Gomel, Mogilev and the castles of Nesvizh & Mir — comfortable intercity travel across Belarus without transfers or layovers.",
    stats: [
      { label: "Coverage", value: "6 regions" },
      { label: "Brest", value: "~350 km" },
      { label: "Grodno", value: "~280 km" },
      { label: "Vehicle class", value: "Business / SUV" },
    ],
    photosTitle: "Belarus — Nature & Castles",
    photos: [
      { src: "https://thumbs.dreamstime.com/b/old-fortress-4939650.jpg", caption: "Mir Castle" },
      { src: "https://ichef.bbci.co.uk/ace/standard/976/cpsprodpb/14834/production/_89902048_89902047.jpg", caption: "Białowieża Forest" },
      { src: "https://belarus365.com/wp-content/uploads/2022/04/nesv_start.jpg", caption: "Nesvizh Castle" },
    ],
    howTitle: "How it works",
    steps: [
      { icon: MapPin, title: "Door pickup in Minsk", desc: "Your driver collects you at your Minsk address at the agreed time." },
      { icon: Route, title: "Comfortable journey", desc: "Modern Belarusian highways, climate control, bottled water — no transfers or waiting." },
      { icon: Navigation, title: "Precise delivery", desc: "Dropped off directly at your chosen address in the destination city." },
    ],
    infoTitle: "Popular Routes",
    infoRows: [
      { label: "Minsk — Brest", value: "~350 km, 3.5–4 hrs" },
      { label: "Minsk — Grodno", value: "~280 km, 3–3.5 hrs" },
      { label: "Minsk — Vitebsk", value: "~265 km, 2.5–3 hrs" },
      { label: "Minsk — Gomel", value: "~305 km, 3–4 hrs" },
      { label: "Minsk — Nesvizh / Mir", value: "~100–120 km, 1.5 hrs" },
      { label: "Minsk — Mogilev", value: "~195 km, 2–2.5 hrs" },
    ],
    includedTitle: "What's included",
    included: [
      "Pickup from your Minsk address",
      "Direct route with no transfers",
      "Bottled water and clean vehicle",
      "Luggage assistance",
      "Child seats on request",
      "Fixed price — no meter, no hidden extras",
    ],
    whyTitle: "Why ComfortLine",
    whyItems: [
      "Drivers with extensive knowledge of Belarusian roads",
      "Direct booking — no agency or dispatch fees",
      "Large vehicles available for groups",
      "Available 24/7 including public holidays",
      "Fixed pricing — no surprises",
      "Over 5,000 completed transfers since 2015",
    ],
    ctaTitle: "Book a Belarus Transfer",
    ctaDesc: "Submit a request and our manager will contact you with an exact price for your route.",
    ctaBtn: "Request a booking",
    prefilledFrom: "Minsk",
    prefilledTo: "Belarus (intercity)",
    backBtn: "← All services",
  },
  seo: {
    titleRu: "Трансфер по Беларуси | Брест, Гродно, Витебск, Несвиж, Мир | ComfortLine",
    titleEn: "Belarus Intercity Transfer | Brest, Grodno, Vitebsk, Mir Castle | ComfortLine",
    descRu: "Межгородские трансферы по Беларуси из Минска: Брест (~350 км), Гродно (~280 км), Витебск, Гомель, Могилёв, замки Мир и Несвиж, Беловежская Пуща. Комфортные авто и фиксированная цена.",
    descEn: "Intercity transfers across Belarus from Minsk — Brest, Grodno, Vitebsk, Gomel, Mogilev, Mir & Nesvizh castles, Belovezhskaya Pushcha. Comfortable cars, fixed prices.",
    pathRu: "/трансфер-по-беларуси",
    pathEn: "/belarus-transfer",
    breadcrumbRu: "Трансфер по Беларуси",
    breadcrumbEn: "Belarus Intercity Transfer",
    fromName: "Минск",
    toName: "Беларусь",
  },
};

export default function BelarusTransferPage() {
  return <RouteLandingPage data={data} />;
}
