import { CountryTransferPage, CountryPageData } from "./country-transfer-page";

const data: CountryPageData = {
  ru: {
    badge: "Трансферы во Францию",
    title: "Минск — Франция",
    subtitle: "Дальние трансферы из Минска в Париж и другие города Франции. Комфортный автомобиль, фиксированная цена, без пересадок.",
    destinationsTitle: "Направления во Франции",
    destinations: [
      {
        cityRu: "Аэропорт Парижа CDG",
        cityEn: "Paris CDG Airport",
        descRu: "Крупнейший аэропорт Франции. Рейсы Air France, Ryanair, Transavia и многих других. Трансфер от Минска напрямую.",
        descEn: "France's busiest airport. Air France, Ryanair, Transavia and many more. Direct transfer from Minsk.",
        distanceKm: "~1900 км",
        travelTime: "по запросу",
        href: "/france-transfer",
        hrefRu: "/трансфер-во-францию",
        isAvailable: false,
        prefilledTo: "Париж CDG",
        slug: "paris-cdg",
      },
      {
        cityRu: "Париж — центр города",
        cityEn: "Paris — city centre",
        descRu: "Эйфелева башня, Лувр, Монмартр. Деловые поездки, туризм, культурные мероприятия.",
        descEn: "Eiffel Tower, Louvre, Montmartre. Business trips, tourism, cultural events.",
        distanceKm: "~1900 км",
        travelTime: "по запросу",
        href: "/france-transfer",
        hrefRu: "/трансфер-во-францию",
        isAvailable: false,
        prefilledTo: "Париж",
        slug: "paris-city",
      },
      {
        cityRu: "Страсбург",
        cityEn: "Strasbourg",
        descRu: "Столица Эльзаса и Европейского парламента. Удобен для транзита через Германию.",
        descEn: "Capital of Alsace and the European Parliament. Convenient via Germany.",
        distanceKm: "~1600 км",
        travelTime: "по запросу",
        href: "/france-transfer",
        hrefRu: "/трансфер-во-францию",
        isAvailable: false,
        prefilledTo: "Страсбург",
        slug: "strasbourg",
      },
    ],
    infoTitle: "Полезная информация",
    infoRows: [
      { label: "Маршрут", value: "Минск → Варшава / Берлин → Париж (через Польшу и Германию)" },
      { label: "Расстояние", value: "~1900 км до Парижа" },
      { label: "Необходимые документы", value: "Шенгенская виза, загранпаспорт" },
      { label: "Валюта", value: "Евро (EUR)" },
      { label: "Формат", value: "Дальний трансфер с водителем, возможно разделение на этапы" },
    ],
    includedTitle: "Что включено в любой трансфер",
    included: [
      "Подача от адреса в Минске",
      "Прямой маршрут без авиапересадок",
      "Комфортный автомобиль бизнес-класса",
      "Питьевая вода и комфортный салон",
      "Детские кресла по запросу",
      "Фиксированная согласованная цена",
    ],
    ctaTitle: "Запросить трансфер во Францию",
    ctaDesc: "Дальний маршрут — рассчитаем индивидуально. Оставьте заявку с маршрутом и датой.",
    ctaBtn: "Оставить заявку",
    backBtn: "← Трансферы в Европу",
    soonLabel: "По запросу",
    bookLabel: "Запросить цену",
    detailsLabel: "Подробнее",
  },
  en: {
    badge: "France Transfers",
    title: "Minsk — France",
    subtitle: "Long-distance transfers from Minsk to Paris and other French cities. Comfortable vehicle, fixed price, door-to-door service.",
    destinationsTitle: "Destinations in France",
    destinations: [
      {
        cityRu: "Аэропорт Парижа CDG",
        cityEn: "Paris CDG Airport",
        descRu: "Крупнейший аэропорт Франции. Рейсы Air France, Ryanair, Transavia и многих других. Трансфер от Минска напрямую.",
        descEn: "France's busiest airport. Air France, Ryanair, Transavia and many more. Direct transfer from Minsk.",
        distanceKm: "~1900 km",
        travelTime: "on request",
        href: "/france-transfer",
        hrefRu: "/трансфер-во-францию",
        isAvailable: false,
        prefilledTo: "Paris CDG",
        slug: "paris-cdg",
      },
      {
        cityRu: "Париж — центр города",
        cityEn: "Paris — city centre",
        descRu: "Эйфелева башня, Лувр, Монмартр. Деловые поездки, туризм, культурные мероприятия.",
        descEn: "Eiffel Tower, Louvre, Montmartre. Business trips, tourism, cultural events.",
        distanceKm: "~1900 km",
        travelTime: "on request",
        href: "/france-transfer",
        hrefRu: "/трансфер-во-францию",
        isAvailable: false,
        prefilledTo: "Paris",
        slug: "paris-city",
      },
      {
        cityRu: "Страсбург",
        cityEn: "Strasbourg",
        descRu: "Столица Эльзаса и Европейского парламента. Удобен для транзита через Германию.",
        descEn: "Capital of Alsace and the European Parliament. Convenient via Germany.",
        distanceKm: "~1600 km",
        travelTime: "on request",
        href: "/france-transfer",
        hrefRu: "/трансфер-во-францию",
        isAvailable: false,
        prefilledTo: "Strasbourg",
        slug: "strasbourg",
      },
    ],
    infoTitle: "Useful information",
    infoRows: [
      { label: "Route", value: "Minsk → Warsaw / Berlin → Paris (via Poland and Germany)" },
      { label: "Distance", value: "~1900 km to Paris" },
      { label: "Documents required", value: "Schengen visa, valid passport" },
      { label: "Currency", value: "Euro (EUR)" },
      { label: "Format", value: "Long-distance driver transfer; may be arranged in stages" },
    ],
    includedTitle: "What's included in every transfer",
    included: [
      "Pickup from your Minsk address",
      "Direct route — no flight connections",
      "Business-class comfortable vehicle",
      "Bottled water and comfortable cabin",
      "Child seats on request",
      "Fixed agreed price — no surprises",
    ],
    ctaTitle: "Request a France Transfer",
    ctaDesc: "Long-distance route — we calculate individually. Leave a request with your route and date.",
    ctaBtn: "Request a booking",
    backBtn: "← Europe transfers",
    soonLabel: "On request",
    bookLabel: "Request price",
    detailsLabel: "View details",
  },
  seo: {
    titleRu: "Трансфер Минск — Франция | Париж, CDG | ComfortLine",
    titleEn: "Minsk to France Transfer | Paris, CDG | ComfortLine",
    descRu: "Дальний трансфер из Минска во Францию: Париж CDG, центр Парижа, Страсбург. Индивидуальный расчёт, фиксированная цена.",
    descEn: "Long-distance transfer from Minsk to France: Paris CDG, Paris city centre, Strasbourg. Individual quote, fixed price.",
    pathRu: "/трансфер-во-францию",
    pathEn: "/france-transfer",
    breadcrumbRu: "Трансферы во Францию",
    breadcrumbEn: "France Transfers",
  },
};

export default function FranceTransferPage() {
  return <CountryTransferPage data={data} />;
}
