import { CountryTransferPage, CountryPageData } from "./country-transfer-page";

const data: CountryPageData = {
  ru: {
    badge: "Трансферы в Германию",
    title: "Минск — Германия",
    subtitle: "Берлин и другие города Германии. Прямые трансферы из Минска — деловые поездки, шопинг, туризм, без пересадок на автобусе.",
    destinationsTitle: "Направления в Германии",
    destinations: [
      {
        cityRu: "Берлин — центр города",
        cityEn: "Berlin — city centre",
        descRu: "Столица Германии. Бранденбургские ворота, Рейхстаг, Музейный остров, деловые кварталы.",
        descEn: "Germany's capital. Brandenburg Gate, Reichstag, Museum Island, business districts.",
        distanceKm: "~1150 км",
        travelTime: "11–14 ч",
        href: "/berlin-transfer",
        hrefRu: "/трансфер-берлин",
        isAvailable: true,
      },
      {
        cityRu: "Берлин — аэропорт BER",
        cityEn: "Berlin BER Airport",
        descRu: "Единственный аэропорт Берлина. Рейсы Lufthansa, Ryanair, easyJet и других авиакомпаний.",
        descEn: "Berlin's only airport. Lufthansa, Ryanair, easyJet and more.",
        distanceKm: "~1170 км",
        travelTime: "11–14 ч",
        href: "/berlin-transfer",
        hrefRu: "/трансфер-берлин",
        isAvailable: false,
        prefilledTo: "Берлин BER",
      },
      {
        cityRu: "Гамбург",
        cityEn: "Hamburg",
        descRu: "Второй по величине город Германии, крупный портовый и деловой центр.",
        descEn: "Germany's second largest city, a major port and business hub.",
        distanceKm: "~1400 км",
        travelTime: "по запросу",
        href: "/germany-transfer",
        hrefRu: "/трансфер-в-германию",
        isAvailable: false,
        prefilledTo: "Гамбург",
      },
    ],
    infoTitle: "Полезная информация",
    infoRows: [
      { label: "Маршрут", value: "Минск → Брест / Варшава → Берлин (через Польшу)" },
      { label: "Расстояние до Берлина", value: "~1150 км" },
      { label: "Необходимые документы", value: "Шенгенская виза, загранпаспорт" },
      { label: "Валюта", value: "Евро (EUR)" },
      { label: "Языки", value: "Немецкий (официальный), английский в городах и туристических местах" },
    ],
    includedTitle: "Что включено в любой трансфер",
    included: [
      "Подача от адреса в Минске",
      "Прямой маршрут без пересадок",
      "Помощь водителя на границах",
      "Питьевая вода и комфортный салон",
      "Детские кресла по запросу",
      "Фиксированная цена без счётчика",
    ],
    ctaTitle: "Заказать трансфер в Германию",
    ctaDesc: "Оставьте заявку с маршрутом и количеством пассажиров — назовём точную цену за 15 минут.",
    ctaBtn: "Оставить заявку",
    backBtn: "← Трансферы в Европу",
    soonLabel: "По запросу",
    bookLabel: "Запросить цену",
    detailsLabel: "Подробнее",
  },
  en: {
    badge: "Germany Transfers",
    title: "Minsk — Germany",
    subtitle: "Berlin and other German cities. Direct transfers from Minsk — business trips, shopping, tourism, no bus connections.",
    destinationsTitle: "Destinations in Germany",
    destinations: [
      {
        cityRu: "Берлин — центр города",
        cityEn: "Berlin — city centre",
        descRu: "Столица Германии. Бранденбургские ворота, Рейхстаг, Музейный остров, деловые кварталы.",
        descEn: "Germany's capital. Brandenburg Gate, Reichstag, Museum Island, business districts.",
        distanceKm: "~1150 km",
        travelTime: "11–14 hrs",
        href: "/berlin-transfer",
        hrefRu: "/трансфер-берлин",
        isAvailable: true,
      },
      {
        cityRu: "Берлин — аэропорт BER",
        cityEn: "Berlin BER Airport",
        descRu: "Единственный аэропорт Берлина. Рейсы Lufthansa, Ryanair, easyJet и других авиакомпаний.",
        descEn: "Berlin's only airport. Lufthansa, Ryanair, easyJet and more.",
        distanceKm: "~1170 km",
        travelTime: "11–14 hrs",
        href: "/berlin-transfer",
        hrefRu: "/трансфер-берлин",
        isAvailable: false,
        prefilledTo: "Berlin BER",
      },
      {
        cityRu: "Гамбург",
        cityEn: "Hamburg",
        descRu: "Второй по величине город Германии, крупный портовый и деловой центр.",
        descEn: "Germany's second largest city, a major port and business hub.",
        distanceKm: "~1400 km",
        travelTime: "on request",
        href: "/germany-transfer",
        hrefRu: "/трансфер-в-германию",
        isAvailable: false,
        prefilledTo: "Hamburg",
      },
    ],
    infoTitle: "Useful information",
    infoRows: [
      { label: "Route", value: "Minsk → Brest / Warsaw → Berlin (via Poland)" },
      { label: "Distance to Berlin", value: "~1150 km" },
      { label: "Documents required", value: "Schengen visa, valid passport" },
      { label: "Currency", value: "Euro (EUR)" },
      { label: "Languages", value: "German (official), English widely spoken in cities and tourist areas" },
    ],
    includedTitle: "What's included in every transfer",
    included: [
      "Pickup from your Minsk address",
      "Direct route — no transfers",
      "Driver assistance at border crossings",
      "Bottled water and comfortable cabin",
      "Child seats on request",
      "Fixed price — no meter, no surprises",
    ],
    ctaTitle: "Book a Germany Transfer",
    ctaDesc: "Tell us your route and number of passengers — we'll send an exact price within 15 minutes.",
    ctaBtn: "Request a booking",
    backBtn: "← Europe transfers",
    soonLabel: "On request",
    bookLabel: "Request price",
    detailsLabel: "View details",
  },
  seo: {
    titleRu: "Трансфер Минск — Германия | Берлин, BER | ComfortLine",
    titleEn: "Minsk to Germany Transfer | Berlin, BER Airport | ComfortLine",
    descRu: "Прямые трансферы из Минска в Германию: Берлин (центр, аэропорт BER), Гамбург. Фиксированная цена, без пересадок.",
    descEn: "Direct transfers from Minsk to Germany: Berlin (city centre, BER airport), Hamburg. Fixed prices, door-to-door.",
    pathRu: "/трансфер-в-германию",
    pathEn: "/germany-transfer",
    breadcrumbRu: "Трансферы в Германию",
    breadcrumbEn: "Germany Transfers",
  },
};

export default function GermanyTransferPage() {
  return <CountryTransferPage data={data} />;
}
