import { CountryTransferPage, CountryPageData } from "./country-transfer-page";

const data: CountryPageData = {
  ru: {
    badge: "Трансферы в Латвию",
    title: "Минск — Латвия",
    subtitle: "Рига и другие города Латвии. Прямые трансферы без пересадок — в аэропорт, центр города или на Балтийское побережье.",
    destinationsTitle: "Направления в Латвии",
    destinations: [
      {
        cityRu: "Аэропорт Риги (RIX)",
        cityEn: "Riga Airport (RIX)",
        descRu: "Крупнейший аэропорт Балтии. Рейсы в более чем 80 городов Европы и мира.",
        descEn: "The largest airport in the Baltics. Flights to over 80 cities across Europe and beyond.",
        distanceKm: "~470 км",
        travelTime: "5–7 ч",
        href: "/minsk-riga-airport",
        hrefRu: "/трансфер-минск-рига-аэропорт",
        isAvailable: true,
      },
      {
        cityRu: "Рига — центр города",
        cityEn: "Riga — city centre",
        descRu: "Старый город под охраной ЮНЕСКО, Дом Черноголовых, Art Nouveau, Рижский рынок.",
        descEn: "UNESCO Old Town, House of the Blackheads, Art Nouveau district, Riga Central Market.",
        distanceKm: "~470 км",
        travelTime: "5–7 ч",
        href: "/riga-transfer",
        hrefRu: "/трансфер-рига",
        isAvailable: true,
      },
      {
        cityRu: "Юрмала",
        cityEn: "Jūrmala",
        descRu: "Балтийский курорт в 25 км от Риги. Пляжи, сосновый воздух, санатории и деревянная архитектура.",
        descEn: "Baltic resort 25 km from Riga. Beaches, pine air, spas and wooden Art Nouveau cottages.",
        distanceKm: "~490 км",
        travelTime: "5.5–7 ч",
        href: "/riga-transfer",
        hrefRu: "/трансфер-рига",
        isAvailable: false,
        prefilledTo: "Юрмала",
      },
      {
        cityRu: "Даугавпилс",
        cityEn: "Daugavpils",
        descRu: "Второй по величине город Латвии. Грандиозная крепость XIX века и Центр Марка Ротко — великого абстракциониста, родившегося здесь.",
        descEn: "Latvia's second-largest city. A vast 19th-century fortress and the Mark Rothko Art Centre — the great abstract expressionist was born here.",
        distanceKm: "~300 км",
        travelTime: "3.5–5 ч",
        href: "/minsk-daugavpils-transfer",
        hrefRu: "/трансфер-минск-даугавпилс",
        isAvailable: true,
      },
    ],
    infoTitle: "Полезная информация",
    infoRows: [
      { label: "Пограничный переход", value: "Урбаны / Патарниеки (Беларусь–Латвия)" },
      { label: "Время на границе", value: "1–6 ч в зависимости от очереди" },
      { label: "Необходимые документы", value: "Шенгенская виза, загранпаспорт" },
      { label: "Валюта", value: "Евро (EUR)" },
      { label: "Языки", value: "Латышский (официальный), русский широко распространён, английский в туристических зонах" },
    ],
    includedTitle: "Что включено в любой трансфер",
    included: [
      "Подача от адреса в Минске",
      "Прямой маршрут без пересадок",
      "Помощь водителя на границе",
      "Питьевая вода и комфортный салон",
      "Детские кресла по запросу",
      "Фиксированная цена без счётчика",
    ],
    ctaTitle: "Заказать трансфер в Латвию",
    ctaDesc: "Оставьте заявку с маршрутом и количеством пассажиров — назовём точную цену за 15 минут.",
    ctaBtn: "Оставить заявку",
    backBtn: "← Трансферы в Европу",
    soonLabel: "Скоро",
    bookLabel: "Запросить цену",
    detailsLabel: "Подробнее",
  },
  en: {
    badge: "Latvia Transfers",
    title: "Minsk — Latvia",
    subtitle: "Riga and other Latvian destinations. Direct door-to-door transfers — to the airport, city centre or Baltic seaside.",
    destinationsTitle: "Destinations in Latvia",
    destinations: [
      {
        cityRu: "Аэропорт Риги (RIX)",
        cityEn: "Riga Airport (RIX)",
        descRu: "Крупнейший аэропорт Балтии. Рейсы в более чем 80 городов Европы и мира.",
        descEn: "The largest airport in the Baltics. Flights to over 80 cities across Europe and beyond.",
        distanceKm: "~470 km",
        travelTime: "5–7 hrs",
        href: "/minsk-riga-airport",
        hrefRu: "/трансфер-минск-рига-аэропорт",
        isAvailable: true,
      },
      {
        cityRu: "Рига — центр города",
        cityEn: "Riga — city centre",
        descRu: "Старый город под охраной ЮНЕСКО, Дом Черноголовых, Art Nouveau, Рижский рынок.",
        descEn: "UNESCO Old Town, House of the Blackheads, Art Nouveau district, Riga Central Market.",
        distanceKm: "~470 km",
        travelTime: "5–7 hrs",
        href: "/riga-transfer",
        hrefRu: "/трансфер-рига",
        isAvailable: true,
      },
      {
        cityRu: "Юрмала",
        cityEn: "Jūrmala",
        descRu: "Балтийский курорт в 25 км от Риги. Пляжи, сосновый воздух, санатории и деревянная архитектура.",
        descEn: "Baltic resort 25 km from Riga. Beaches, pine air, spas and wooden Art Nouveau cottages.",
        distanceKm: "~490 km",
        travelTime: "5.5–7 hrs",
        href: "/riga-transfer",
        hrefRu: "/трансфер-рига",
        isAvailable: false,
        prefilledTo: "Jūrmala",
      },
      {
        cityRu: "Даугавпилс",
        cityEn: "Daugavpils",
        descRu: "Второй по величине город Латвии. Грандиозная крепость XIX века и Центр Марка Ротко — великого абстракциониста, родившегося здесь.",
        descEn: "Latvia's second-largest city. A vast 19th-century fortress and the Mark Rothko Art Centre — the great abstract expressionist was born here.",
        distanceKm: "~300 km",
        travelTime: "3.5–5 hrs",
        href: "/minsk-daugavpils-transfer",
        hrefRu: "/трансфер-минск-даугавпилс",
        isAvailable: true,
      },
    ],
    infoTitle: "Useful information",
    infoRows: [
      { label: "Border crossing", value: "Urbany / Pāternieki (Belarus–Latvia)" },
      { label: "Border crossing time", value: "1–6 hrs depending on queues" },
      { label: "Documents required", value: "Schengen visa, valid passport" },
      { label: "Currency", value: "Euro (EUR)" },
      { label: "Languages", value: "Latvian (official), Russian widely spoken, English in tourist areas" },
    ],
    includedTitle: "What's included in every transfer",
    included: [
      "Pickup from your Minsk address",
      "Direct route — no transfers",
      "Driver assistance at the border",
      "Bottled water and comfortable cabin",
      "Child seats on request",
      "Fixed price — no meter, no surprises",
    ],
    ctaTitle: "Book a Latvia Transfer",
    ctaDesc: "Tell us your route and number of passengers — we'll send an exact price within 15 minutes.",
    ctaBtn: "Request a booking",
    backBtn: "← Europe transfers",
    soonLabel: "Coming soon",
    bookLabel: "Request price",
    detailsLabel: "View details",
  },
  seo: {
    titleRu: "Трансфер Минск — Латвия | Рига, аэропорт RIX, Юрмала | ComfortLine",
    titleEn: "Minsk to Latvia Transfer | Riga, RIX Airport, Jūrmala | ComfortLine",
    descRu: "Прямые трансферы из Минска в Латвию: Рига (RIX), центр Риги, Юрмала. Фиксированная цена, граница Урбаны–Патарниеки.",
    descEn: "Direct transfers from Minsk to Latvia: Riga (RIX), Riga city centre, Jūrmala. Fixed prices, Urbany–Pāternieki border.",
    pathRu: "/трансфер-в-латвию",
    pathEn: "/latvia-transfer",
    breadcrumbRu: "Трансферы в Латвию",
    breadcrumbEn: "Latvia Transfers",
  },
};

export default function LatviaTransferPage() {
  return <CountryTransferPage data={data} />;
}
