import { CountryTransferPage, CountryPageData } from "./country-transfer-page";

const data: CountryPageData = {
  ru: {
    badge: "Трансферы в Литву",
    title: "Минск — Литва",
    subtitle: "Вильнюс, Каунас и другие города Литвы. Прямые трансферы без пересадок — до аэропорта, отеля или офиса.",
    destinationsTitle: "Направления в Литве",
    destinations: [
      {
        cityRu: "Вильнюс — центр города",
        cityEn: "Vilnius — city centre",
        descRu: "Столица Литвы. Старый город ЮНЕСКО, Кафедральная площадь, Ворота Зари, замок Гедиминаса.",
        descEn: "Lithuania's capital. UNESCO Old Town, Cathedral Square, Gate of Dawn, Gediminas Castle.",
        distanceKm: "~170 км",
        travelTime: "2–4 ч",
        href: "/minsk-vilnius-transfer",
        hrefRu: "/трансфер-минск-вильнюс",
        isAvailable: true,
      },
      {
        cityRu: "Аэропорт Вильнюса (VNO)",
        cityEn: "Vilnius Airport (VNO)",
        descRu: "Прямой трансфер к терминалу. Удобно к рейсам Ryanair, Wizz Air, LOT и другим авиакомпаниям.",
        descEn: "Direct transfer to the terminal. Ideal for Ryanair, Wizz Air, LOT and other airlines.",
        distanceKm: "~175 км",
        travelTime: "2.5–4 ч",
        href: "/minsk-vilnius-airport",
        hrefRu: "/трансфер-минск-вильнюс-аэропорт",
        isAvailable: true,
      },
      {
        cityRu: "Каунас — центр города",
        cityEn: "Kaunas — city centre",
        descRu: "Второй по величине город Литвы. Старый город, аллея Свободы, Ратуша, Каунасский замок.",
        descEn: "Lithuania's second largest city. Old Town, Laisvės alėja, Town Hall, Kaunas Castle.",
        distanceKm: "~220 км",
        travelTime: "3–4.5 ч",
        href: "/minsk-kaunas-transfer",
        hrefRu: "/трансфер-минск-каунас",
        isAvailable: true,
      },
      {
        cityRu: "Аэропорт Каунаса (KUN)",
        cityEn: "Kaunas Airport (KUN)",
        descRu: "Рейсы Ryanair в Лондон, Дублин, Берлин, Амстердам и другие города Европы.",
        descEn: "Ryanair flights to London, Dublin, Berlin, Amsterdam and more across Europe.",
        distanceKm: "~225 км",
        travelTime: "3–4.5 ч",
        href: "/minsk-kaunas-airport",
        hrefRu: "/трансфер-минск-каунас-аэропорт",
        isAvailable: true,
      },
      {
        cityRu: "Паланга",
        cityEn: "Palanga",
        descRu: "Главный курорт Литвы на Балтийском море. Янтарный музей, пирс, Бирютский парк, песчаный пляж.",
        descEn: "Lithuania's premier Baltic Sea resort. Amber Museum, the pier, Birutė Park, wide sandy beach.",
        distanceKm: "~390 км",
        travelTime: "5–7 ч",
        href: "/minsk-palanga-transfer",
        hrefRu: "/трансфер-минск-паланга",
        isAvailable: true,
      },
      {
        cityRu: "Тракай",
        cityEn: "Trakai",
        descRu: "Средневековый замок на острове, озеро Гальве, культура Kaраимов. Отличный вариант для однодневной поездки.",
        descEn: "Medieval island castle, Lake Galvė and the unique Karaim culture. A perfect day-trip destination.",
        distanceKm: "~170 км",
        travelTime: "2–4 ч",
        href: "/minsk-trakai-transfer",
        hrefRu: "/трансфер-минск-тракай",
        isAvailable: true,
      },
      {
        cityRu: "Клайпеда",
        cityEn: "Klaipėda",
        descRu: "Портовый город на Балтийском побережье. Паромы в Швецию и Германию, Куршская коса.",
        descEn: "Baltic port city. Ferries to Sweden and Germany, Curonian Spit UNESCO site.",
        distanceKm: "~420 км",
        travelTime: "5–7 ч",
        href: "/minsk-klaipeda-transfer",
        hrefRu: "/трансфер-минск-клайпеда",
        isAvailable: true,
      },
      {
        cityRu: "Друскининкай",
        cityEn: "Druskininkai",
        descRu: "Главный СПА-курорт Литвы. Минеральные воды, аквапарк, горнолыжная трасса Snow Arena.",
        descEn: "Lithuania's premier spa resort. Mineral springs, the Baltics' largest aqua park, ski slope.",
        distanceKm: "~220 км",
        travelTime: "3–5 ч",
        href: "/minsk-druskininkai-transfer",
        hrefRu: "/трансфер-минск-друскининкай",
        isAvailable: true,
      },
    ],
    infoTitle: "Полезная информация",
    infoRows: [
      { label: "Пограничный переход", value: "Медининкай / Шальчининкай (Беларусь–Литва)" },
      { label: "Время на границе", value: "30 мин – 4 ч в зависимости от очереди" },
      { label: "Необходимые документы", value: "Шенгенская виза, загранпаспорт" },
      { label: "Валюта", value: "Евро (EUR)" },
      { label: "Языки", value: "Литовский (официальный), русский понятен старшему поколению, английский в туристических зонах" },
    ],
    includedTitle: "Что включено в любой трансфер",
    included: [
      "Подача от адреса в Минске",
      "Прямой маршрут без пересадок",
      "Помощь водителя на границе",
      "Питьевая вода и комфортный салон",
      "Детские кресла по запросу",
      "Фиксированная цена без счётчика",
    ],
    ctaTitle: "Заказать трансфер в Литву",
    ctaDesc: "Оставьте заявку с маршрутом и количеством пассажиров — назовём точную цену в ближайшее время.",
    ctaBtn: "Оставить заявку",
    backBtn: "← Трансферы в Европу",
    soonLabel: "Скоро",
    bookLabel: "Запросить цену",
    detailsLabel: "Подробнее",
  },
  en: {
    badge: "Lithuania Transfers",
    title: "Minsk — Lithuania",
    subtitle: "Vilnius, Kaunas and more Lithuanian cities. Direct door-to-door transfers — to the airport, your hotel or office.",
    destinationsTitle: "Destinations in Lithuania",
    destinations: [
      {
        cityRu: "Вильнюс — центр города",
        cityEn: "Vilnius — city centre",
        descRu: "Столица Литвы. Старый город ЮНЕСКО, Кафедральная площадь, Ворота Зари, замок Гедиминаса.",
        descEn: "Lithuania's capital. UNESCO Old Town, Cathedral Square, Gate of Dawn, Gediminas Castle.",
        distanceKm: "~170 km",
        travelTime: "2–4 hrs",
        href: "/minsk-vilnius-transfer",
        hrefRu: "/трансфер-минск-вильнюс",
        isAvailable: true,
      },
      {
        cityRu: "Аэропорт Вильнюса (VNO)",
        cityEn: "Vilnius Airport (VNO)",
        descRu: "Прямой трансфер к терминалу. Удобно к рейсам Ryanair, Wizz Air, LOT и другим авиакомпаниям.",
        descEn: "Direct transfer to the terminal. Ideal for Ryanair, Wizz Air, LOT and other airlines.",
        distanceKm: "~175 km",
        travelTime: "2.5–4 hrs",
        href: "/minsk-vilnius-airport",
        hrefRu: "/трансфер-минск-вильнюс-аэропорт",
        isAvailable: true,
      },
      {
        cityRu: "Каунас — центр города",
        cityEn: "Kaunas — city centre",
        descRu: "Второй по величине город Литвы. Старый город, аллея Свободы, Ратуша, Каунасский замок.",
        descEn: "Lithuania's second largest city. Old Town, Laisvės alėja, Town Hall, Kaunas Castle.",
        distanceKm: "~220 km",
        travelTime: "3–4.5 hrs",
        href: "/minsk-kaunas-transfer",
        hrefRu: "/трансфер-минск-каунас",
        isAvailable: true,
      },
      {
        cityRu: "Аэропорт Каунаса (KUN)",
        cityEn: "Kaunas Airport (KUN)",
        descRu: "Рейсы Ryanair в Лондон, Дублин, Берлин, Амстердам и другие города Европы.",
        descEn: "Ryanair flights to London, Dublin, Berlin, Amsterdam and more across Europe.",
        distanceKm: "~225 km",
        travelTime: "3–4.5 hrs",
        href: "/minsk-kaunas-airport",
        hrefRu: "/трансфер-минск-каунас-аэропорт",
        isAvailable: true,
      },
      {
        cityRu: "Паланга",
        cityEn: "Palanga",
        descRu: "Главный курорт Литвы на Балтийском море. Янтарный музей, пирс, Бирютский парк, песчаный пляж.",
        descEn: "Lithuania's premier Baltic Sea resort. Amber Museum, the pier, Birutė Park, wide sandy beach.",
        distanceKm: "~390 km",
        travelTime: "5–7 hrs",
        href: "/minsk-palanga-transfer",
        hrefRu: "/трансфер-минск-паланга",
        isAvailable: true,
      },
      {
        cityRu: "Тракай",
        cityEn: "Trakai",
        descRu: "Средневековый замок на острове, озеро Гальве, культура Kaраимов. Отличный вариант для однодневной поездки.",
        descEn: "Medieval island castle, Lake Galvė and the unique Karaim culture. A perfect day-trip destination.",
        distanceKm: "~170 km",
        travelTime: "2–4 hrs",
        href: "/minsk-trakai-transfer",
        hrefRu: "/трансфер-минск-тракай",
        isAvailable: true,
      },
      {
        cityRu: "Клайпеда",
        cityEn: "Klaipėda",
        descRu: "Портовый город на Балтийском побережье. Паромы в Швецию и Германию, Куршская коса.",
        descEn: "Baltic port city. Ferries to Sweden and Germany, Curonian Spit UNESCO site.",
        distanceKm: "~420 km",
        travelTime: "5–7 hrs",
        href: "/minsk-klaipeda-transfer",
        hrefRu: "/трансфер-минск-клайпеда",
        isAvailable: true,
      },
      {
        cityRu: "Друскининкай",
        cityEn: "Druskininkai",
        descRu: "Главный СПА-курорт Литвы. Минеральные воды, аквапарк, горнолыжная трасса Snow Arena.",
        descEn: "Lithuania's premier spa resort. Mineral springs, the Baltics' largest aqua park, ski slope.",
        distanceKm: "~220 km",
        travelTime: "3–5 hrs",
        href: "/minsk-druskininkai-transfer",
        hrefRu: "/трансфер-минск-друскининкай",
        isAvailable: true,
      },
    ],
    infoTitle: "Useful information",
    infoRows: [
      { label: "Border crossing", value: "Medininkai / Šalčininkai (Belarus–Lithuania)" },
      { label: "Border crossing time", value: "30 min – 4 hrs depending on queues" },
      { label: "Documents required", value: "Schengen visa, valid passport" },
      { label: "Currency", value: "Euro (EUR)" },
      { label: "Languages", value: "Lithuanian (official), Russian understood by older generation, English in tourist areas" },
    ],
    includedTitle: "What's included in every transfer",
    included: [
      "Pickup from your Minsk address",
      "Direct route — no transfers",
      "Driver assistance at the border",
      "Bottled water and comfortable cabin",
      "Child seats on request",
      "Fixed price — no meter, no surprises",
    ],
    ctaTitle: "Book a Lithuania Transfer",
    ctaDesc: "Tell us your route and number of passengers — we'll send an exact price shortly.",
    ctaBtn: "Request a booking",
    backBtn: "← Europe transfers",
    soonLabel: "Coming soon",
    bookLabel: "Request price",
    detailsLabel: "View details",
  },
  seo: {
    titleRu: "Трансфер Минск — Литва | Вильнюс, Каунас, аэропорты | ComfortLine",
    titleEn: "Minsk to Lithuania Transfer | Vilnius, Kaunas, Airports | ComfortLine",
    descRu: "Прямые трансферы из Минска в Литву: Вильнюс (VNO), Каунас, аэропорт Каунаса (KUN), Клайпеда. Фиксированная цена, без пересадок.",
    descEn: "Direct transfers from Minsk to Lithuania: Vilnius (VNO), Kaunas, Kaunas Airport (KUN), Klaipėda. Fixed prices, no transfers.",
    pathRu: "/трансфер-в-литву",
    pathEn: "/lithuania-transfer",
    breadcrumbRu: "Трансферы в Литву",
    breadcrumbEn: "Lithuania Transfers",
  },
};

export default function LithuaniaTransferPage() {
  return <CountryTransferPage data={data} />;
}
