import { MapPin, ShieldCheck, Building2 } from "lucide-react";
import { RouteLandingPage, RoutePageData } from "./route-landing-page";

const data: RoutePageData = {
  ru: {
    badge: "Трансфер в Катовице",
    title: "Минск — Катовице",
    subtitle: "Прямой трансфер из Минска в Катовице — столицу Силезии и один из крупнейших городских агломератов Польши. Арена «Сподек», Силезский музей в шахтных башнях и исторический квартал горняков Никишовец.",
    stats: [
      { label: "Расстояние", value: "~700 км" },
      { label: "Время в пути", value: "8–10 ч" },
      { label: "Граница", value: "Беларусь–Польша" },
      { label: "Класс авто", value: "Бизнес / Минивэн" },
    ],
    photosTitle: "Катовице — достопримечательности",
    photos: [
      { src: "/img/katowice/spodek.png", caption: "«Сподек» — легендарная арена в форме летающей тарелки, символ Катовице" },
      { src: "/img/katowice/silesian-museum.png", caption: "Силезский музей — современный комплекс в башнях бывшей угольной шахты" },
      { src: "/img/katowice/nikiszowiec.png", caption: "Никишовец — исторический квартал горняков начала XX века из красного кирпича" },
    ],
    howTitle: "Как проходит поездка",
    steps: [
      { icon: MapPin, title: "Выезд из Минска", desc: "Водитель заберёт вас по указанному адресу в Минске и направится к польской границе по оптимальному маршруту." },
      { icon: ShieldCheck, title: "Граница Беларусь–Польша", desc: "Переход Брузги / Кузница или Берёза / Половцы. Водитель знает актуальные очереди и помогает на КПП." },
      { icon: Building2, title: "Катовице: любой адрес", desc: "Довезём до отеля в центре, аэропорта KTW (Пыжовице) или любого другого адреса в городе и агломерации." },
    ],
    infoTitle: "Детали маршрута",
    infoRows: [
      { label: "Маршрут", value: "Минск → Брест → Тересполь → Варшава → Катовице" },
      { label: "Расстояние", value: "~700 км" },
      { label: "Пограничный переход", value: "Брузги / Кузница или Берёза / Половцы (Беларусь–Польша)" },
      { label: "Время пересечения границы", value: "1–8 ч в зависимости от сезона и очереди" },
      { label: "Необходимые документы", value: "Виза Шенген, загранпаспорт" },
      { label: "Аэропорт Катовице", value: "KTW (Катовице-Пыжовице) — 30 км от центра" },
    ],
    includedTitle: "Что включено",
    included: [
      "Подача от адреса в Минске",
      "Прямой маршрут без пересадок",
      "Помощь водителя на границе",
      "Питьевая вода и комфортный салон",
      "Детские кресла по запросу",
      "Фиксированная цена без счётчика",
    ],
    whyTitle: "Почему ComfortLine",
    whyItems: [
      "Опытные водители маршрута Минск–Польша",
      "Знание актуальных очередей на границе",
      "Можно доехать до Кракова (+80 км от Катовице) по пути",
      "Возможна остановка в Варшаве по дороге",
      "Обратный трансфер: из Катовице в Минск",
      "Работаем 24/7, включая праздники",
    ],
    faqTitle: "Часто задаваемые вопросы",
    faq: [
      { q: "Какой маршрут до Катовице?", a: "Едем через Брест — КПП Брузги/Кузница или Берёза/Половцы — Варшаву — Катовице. Расстояние около 700 км, время в пути 8–10 ч без учёта границы." },
      { q: "Нужна ли виза в Польшу?", a: "Гражданам Беларуси требуется шенгенская виза. Уточняйте актуальные требования в посольстве Польши или на официальных сайтах перед поездкой." },
      { q: "Что такое «Сподек»?", a: "Spodek («Блюдце») — культовая многофункциональная арена в Катовице, построенная в 1971 году. Её характерная форма летающей тарелки стала символом города. Здесь проходят концерты мировых звёзд, спортивные матчи и крупные конгрессы." },
      { q: "Можно ли заехать в Краков по дороге?", a: "Да — Краков находится в 80 км от Катовице, по пути из Варшавы. Если хотите сначала остановиться в Кракове, а затем ехать в Катовице (или наоборот), договоритесь с менеджером при бронировании." },
    ],
    ctaTitle: "Заказать трансфер Минск–Катовице",
    ctaDesc: "Оставьте заявку — менеджер свяжется с вами в ближайшее время и назовёт точную стоимость.",
    ctaBtn: "Оставить заявку",
    prefilledFrom: "Минск",
    prefilledTo: "Катовице",
    backBtn: "← Трансферы в Польшу",
  },
  en: {
    badge: "Katowice Transfer",
    title: "Minsk — Katowice",
    subtitle: "Direct private transfer from Minsk to Katowice — Silesia's capital and one of Poland's largest urban agglomerations. The iconic Spodek arena, the Silesian Museum inside mine shaft towers and the historic miners' district of Nikiszowiec.",
    stats: [
      { label: "Distance", value: "~700 km" },
      { label: "Travel time", value: "8–10 hrs" },
      { label: "Border", value: "Belarus–Poland" },
      { label: "Vehicle class", value: "Business / Minivan" },
    ],
    photosTitle: "Katowice — Highlights",
    photos: [
      { src: "/img/katowice/spodek.png", caption: "Spodek — the legendary UFO-shaped arena, Katowice's most iconic landmark" },
      { src: "/img/katowice/silesian-museum.png", caption: "Silesian Museum — a striking modern complex built into former colliery shaft towers" },
      { src: "/img/katowice/nikiszowiec.png", caption: "Nikiszowiec — a remarkably preserved early 20th-century red-brick miners' estate" },
    ],
    howTitle: "How the transfer works",
    steps: [
      { icon: MapPin, title: "Departure from Minsk", desc: "Your driver picks you up at your Minsk address and heads for the Polish border via the fastest route." },
      { icon: ShieldCheck, title: "Belarus–Poland border", desc: "Bruzgi / Kuźnica or Berёza / Połowce crossing. Your driver knows current queue conditions and assists at the checkpoint." },
      { icon: Building2, title: "Katowice — any address", desc: "We drop you at your city-centre hotel, Katowice Airport (KTW, Pyrzowice) or any other address in the city and agglomeration." },
    ],
    infoTitle: "Route Details",
    infoRows: [
      { label: "Route", value: "Minsk → Brest → Terespol → Warsaw → Katowice" },
      { label: "Distance", value: "~700 km" },
      { label: "Border crossing", value: "Bruzgi / Kuźnica or Berёza / Połowce (Belarus–Poland)" },
      { label: "Border crossing time", value: "1–8 hrs depending on season and queues" },
      { label: "Documents required", value: "Schengen visa, valid passport" },
      { label: "Katowice Airport", value: "KTW (Katowice-Pyrzowice) — 30 km from the centre" },
    ],
    includedTitle: "What's included",
    included: [
      "Pickup from your Minsk address",
      "Direct route — no transfers",
      "Driver assistance at the border",
      "Bottled water and comfortable cabin",
      "Child seats on request",
      "Fixed price — no meter, no surprises",
    ],
    whyTitle: "Why ComfortLine",
    whyItems: [
      "Experienced drivers on the Minsk–Poland route",
      "Up-to-date knowledge of border queue conditions",
      "Easy side trip to Kraków (+80 km) on the same journey",
      "Optional Warsaw stopover en route",
      "Return transfer Katowice → Minsk also available",
      "Available 24/7 including public holidays",
    ],
    faqTitle: "Frequently asked questions",
    faq: [
      { q: "What is the route to Katowice?", a: "We go via Brest – Bruzgi/Kuźnica or Berёza/Połowce border crossing – Warsaw – Katowice. Total distance is about 700 km, travel time 8–10 hours excluding the border stop." },
      { q: "Do I need a visa to enter Poland?", a: "Citizens of Belarus require a Schengen visa. Please check the latest requirements with the Polish embassy or official sources before travelling." },
      { q: "What is the Spodek?", a: "Spodek (meaning 'saucer') is Katowice's iconic multi-purpose arena built in 1971. Its flying-saucer silhouette has become the city's symbol. It hosts world-class concerts, sporting events and major congresses." },
      { q: "Can we visit Kraków on the way?", a: "Absolutely — Kraków is just 80 km from Katowice, en route from Warsaw. If you'd like a stop in Kraków before continuing to Katowice (or vice versa), just let the manager know when booking." },
    ],
    ctaTitle: "Book Minsk–Katowice Transfer",
    ctaDesc: "Submit a request and our manager will contact you shortly with an exact price.",
    ctaBtn: "Request a booking",
    prefilledFrom: "Minsk",
    prefilledTo: "Katowice",
    backBtn: "← Poland transfers",
  },
  seo: {
    titleRu: "Трансфер Минск — Катовице | Столица Силезии | ComfortLine",
    titleEn: "Minsk to Katowice Transfer | Silesia's Capital | ComfortLine",
    descRu: "Прямой трансфер из Минска в Катовице. ~700 км, 8–10 ч. Сподек, Силезский музей, Никишовец. Граница Беларусь–Польша, фиксированная цена.",
    descEn: "Direct transfer from Minsk to Katowice. ~700 km, 8–10 hrs. Spodek, Silesian Museum, Nikiszowiec. Belarus–Poland border crossing, fixed price.",
    pathRu: "/трансфер-минск-катовице",
    pathEn: "/minsk-katowice-transfer",
    breadcrumbRu: "Трансфер Минск–Катовице",
    breadcrumbEn: "Minsk — Katowice",
    fromName: "Минск",
    toName: "Катовице",
  },
};

export default function MinskKatowiceTransferPage() {
  return <RouteLandingPage data={data} />;
}
