import { MapPin, ShieldCheck, Building2 } from "lucide-react";
import { RouteLandingPage, RoutePageData } from "./route-landing-page";

const data: RoutePageData = {
  ru: {
    badge: "Трансфер в Краков",
    title: "Минск — Краков",
    subtitle: "Прямой трансфер из Минска в Краков — старинную столицу Польши. Вавельский замок, Главная рыночная площадь и Величкская соляная шахта — три объекта ЮНЕСКО в одной поездке.",
    stats: [
      { label: "Расстояние", value: "~750 км" },
      { label: "Время в пути", value: "8–11 ч" },
      { label: "Граница", value: "Беларусь–Польша" },
      { label: "Класс авто", value: "Бизнес / Минивэн" },
    ],
    photosTitle: "Краков — достопримечательности",
    photos: [
      { src: "/img/krakow/main-square.png", caption: "Главная рыночная площадь (Rynek Główny) — крупнейшая средневековая площадь Европы" },
      { src: "/img/krakow/wawel-castle.png", caption: "Вавельский замок — королевская резиденция над Вислой" },
      { src: "/img/krakow/wieliczka-mine.png", caption: "Величкская соляная шахта — объект ЮНЕСКО в 14 км от центра" },
    ],
    howTitle: "Как проходит поездка",
    steps: [
      { icon: MapPin, title: "Выезд из Минска", desc: "Водитель заберёт вас по указанному адресу в Минске и направится к польской границе по оптимальному маршруту." },
      { icon: ShieldCheck, title: "Граница Беларусь–Польша", desc: "Переход Брузги / Кузница или Берёза / Половцы. Водитель знает актуальные очереди и помогает на КПП." },
      { icon: Building2, title: "Краков: любой адрес", desc: "Довезём до отеля у Рыночной площади, аэропорта KRK, Вавельского замка или любого другого адреса в городе." },
    ],
    infoTitle: "Детали маршрута",
    infoRows: [
      { label: "Маршрут", value: "Минск → Брест → Тересполь → Варшава → Краков" },
      { label: "Расстояние", value: "~750 км" },
      { label: "Пограничный переход", value: "Брузги / Кузница или Берёза / Половцы (Беларусь–Польша)" },
      { label: "Время пересечения границы", value: "1–8 ч в зависимости от сезона и очереди" },
      { label: "Необходимые документы", value: "Виза Шенген, загранпаспорт" },
      { label: "Аэропорт Кракова", value: "KRK (им. Иоанна Павла II) — 15 км от центра" },
    ],
    includedTitle: "Что включено",
    included: [
      "Подача от адреса в Минске",
      "Прямой маршрут без пересадок",
      "Помощь водителя на границе",
      "Питьевая вода и комфортный салон",
      "Детские кресла по запросу",
      "Фиксированная цена без счётчика",
    ],
    whyTitle: "Почему ComfortLine",
    whyItems: [
      "Опытные водители маршрута Минск–Польша",
      "Знание актуальных очередей на границе",
      "Возможна остановка в Варшаве по дороге",
      "Заезд в Величку (+14 км от Кракова) по запросу",
      "Обратный трансфер: из Кракова в Минск",
      "Работаем 24/7, включая праздники",
    ],
    faqTitle: "Часто задаваемые вопросы",
    faq: [
      { q: "Какой маршрут до Кракова?", a: "Едем через Брест — КПП Брузги/Кузница или Берёза/Половцы — Варшаву — Краков. Расстояние около 750 км, время в пути 8–11 ч без учёта границы." },
      { q: "Нужна ли виза в Польшу?", a: "Гражданам Беларуси требуется шенгенская виза. Уточняйте актуальные требования в посольстве Польши или на официальных сайтах перед поездкой." },
      { q: "Можно ли заехать в Величкскую шахту?", a: "Да — шахта находится в 14 км от центра Кракова. Мы можем завезти вас туда до или после посещения города. Договоритесь с менеджером при бронировании." },
      { q: "Можно ли остановиться в Варшаве по дороге?", a: "Да, маршрут проходит через Варшаву. Остановка почти не удлиняет поездку — договоритесь с менеджером при бронировании." },
    ],
    ctaTitle: "Заказать трансфер Минск–Краков",
    ctaDesc: "Оставьте заявку — менеджер свяжется с вами в ближайшее время и назовёт точную стоимость.",
    ctaBtn: "Оставить заявку",
    prefilledFrom: "Минск",
    prefilledTo: "Краков",
    backBtn: "← Трансферы в Польшу",
  },
  en: {
    badge: "Kraków Transfer",
    title: "Minsk — Kraków",
    subtitle: "Direct private transfer from Minsk to Kraków — Poland's ancient royal capital. Wawel Castle, the largest medieval market square in Europe and the Wieliczka Salt Mine — three UNESCO sites in one trip.",
    stats: [
      { label: "Distance", value: "~750 km" },
      { label: "Travel time", value: "8–11 hrs" },
      { label: "Border", value: "Belarus–Poland" },
      { label: "Vehicle class", value: "Business / Minivan" },
    ],
    photosTitle: "Kraków — Highlights",
    photos: [
      { src: "/img/krakow/main-square.png", caption: "Rynek Główny — Europe's largest medieval market square" },
      { src: "/img/krakow/wawel-castle.png", caption: "Wawel Castle — the royal residence above the Vistula" },
      { src: "/img/krakow/wieliczka-mine.png", caption: "Wieliczka Salt Mine — UNESCO World Heritage Site, 14 km from the centre" },
    ],
    howTitle: "How the transfer works",
    steps: [
      { icon: MapPin, title: "Departure from Minsk", desc: "Your driver picks you up at your Minsk address and heads for the Polish border via the fastest route." },
      { icon: ShieldCheck, title: "Belarus–Poland border", desc: "Bruzgi / Kuźnica or Berёza / Połowce crossing. Your driver knows current queue conditions and assists at the checkpoint." },
      { icon: Building2, title: "Kraków — any address", desc: "We drop you at your hotel near the Market Square, Kraków Airport (KRK), Wawel Castle or any other address in the city." },
    ],
    infoTitle: "Route Details",
    infoRows: [
      { label: "Route", value: "Minsk → Brest → Terespol → Warsaw → Kraków" },
      { label: "Distance", value: "~750 km" },
      { label: "Border crossing", value: "Bruzgi / Kuźnica or Berёza / Połowce (Belarus–Poland)" },
      { label: "Border crossing time", value: "1–8 hrs depending on season and queues" },
      { label: "Documents required", value: "Schengen visa, valid passport" },
      { label: "Kraków Airport", value: "KRK (John Paul II International) — 15 km from the centre" },
    ],
    includedTitle: "What's included",
    included: [
      "Pickup from your Minsk address",
      "Direct route — no transfers",
      "Driver assistance at the border",
      "Bottled water and comfortable cabin",
      "Child seats on request",
      "Fixed price — no meter, no surprises",
    ],
    whyTitle: "Why ComfortLine",
    whyItems: [
      "Experienced drivers on the Minsk–Poland route",
      "Up-to-date knowledge of border queue conditions",
      "Optional Warsaw stopover en route",
      "Side trip to Wieliczka Salt Mine (+14 km) on request",
      "Return transfer Kraków → Minsk also available",
      "Available 24/7 including public holidays",
    ],
    faqTitle: "Frequently asked questions",
    faq: [
      { q: "What is the route to Kraków?", a: "We go via Brest – Bruzgi/Kuźnica or Berёza/Połowce border crossing – Warsaw – Kraków. Total distance is about 750 km, travel time 8–11 hours excluding the border stop." },
      { q: "Do I need a visa to enter Poland?", a: "Citizens of Belarus require a Schengen visa. Please check the latest requirements with the Polish embassy or official sources before travelling." },
      { q: "Can we visit the Wieliczka Salt Mine on the way?", a: "Yes — the mine is 14 km from Kraków city centre. We can drop you there before or after the city. Just let the manager know when booking." },
      { q: "Can we stop in Warsaw on the way?", a: "Yes — the route passes through Warsaw, so a stop adds almost no extra distance. Let the manager know when booking." },
    ],
    ctaTitle: "Book Minsk–Kraków Transfer",
    ctaDesc: "Submit a request and our manager will contact you shortly with an exact price.",
    ctaBtn: "Request a booking",
    prefilledFrom: "Minsk",
    prefilledTo: "Kraków",
    backBtn: "← Poland transfers",
  },
  seo: {
    titleRu: "Трансфер Минск — Краков | Королевская столица Польши | ComfortLine",
    titleEn: "Minsk to Kraków Transfer | Poland's Royal Capital | ComfortLine",
    descRu: "Прямой трансфер из Минска в Краков. ~750 км, 8–11 ч. Вавельский замок, Главная площадь, Величка. Граница Беларусь–Польша, фиксированная цена.",
    descEn: "Direct transfer from Minsk to Kraków. ~750 km, 8–11 hrs. Wawel Castle, Main Square, Wieliczka. Belarus–Poland border crossing, fixed price.",
    pathRu: "/трансфер-минск-краков",
    pathEn: "/minsk-krakow-transfer",
    breadcrumbRu: "Трансфер Минск–Краков",
    breadcrumbEn: "Minsk — Kraków",
    fromName: "Минск",
    toName: "Краков",
  },
};

export default function MinskKrakowTransferPage() {
  return <RouteLandingPage data={data} />;
}
