import { MapPin, ShieldCheck, Building2 } from "lucide-react";
import { RouteLandingPage, RoutePageData } from "./route-landing-page";

const data: RoutePageData = {
  ru: {
    badge: "Трансфер в Даугавпилс",
    title: "Минск — Даугавпилс",
    subtitle: "Прямой трансфер из Минска в Даугавпилс — второй по величине город Латвии. Грандиозная крепость XIX века, Центр Марка Ротко и многонациональный дух города на берегу Даугавы.",
    stats: [
      { label: "Расстояние", value: "~300 км" },
      { label: "Время в пути", value: "3.5–5 ч" },
      { label: "Граница", value: "Беларусь–Латвия" },
      { label: "Класс авто", value: "Бизнес / Минивэн" },
    ],
    photosTitle: "Даугавпилс — достопримечательности",
    photos: [
      { src: "/img/daugavpils/fortress.png", caption: "Даугавпилсская крепость — одна из крупнейших хорошо сохранившихся крепостей Восточной Европы" },
      { src: "/img/daugavpils/rothko-centre.png", caption: "Центр Марка Ротко — музей в стенах крепости, посвящённый великому абстракционисту, родившемуся в Даугавпилсе" },
      { src: "/img/daugavpils/city-river.png", caption: "Исторический центр Даугавпилса на берегу реки Даугавы" },
    ],
    howTitle: "Как проходит поездка",
    steps: [
      { icon: MapPin, title: "Выезд из Минска", desc: "Водитель заберёт вас по указанному адресу в Минске и направится к латвийской границе по оптимальному маршруту." },
      { icon: ShieldCheck, title: "Граница Беларусь–Латвия", desc: "Переход Урбаны / Патарниеки. Водитель знает актуальные очереди и помогает на КПП." },
      { icon: Building2, title: "Даугавпилс: любой адрес", desc: "Довезём до отеля, крепости, Центра Ротко или любого другого адреса в городе." },
    ],
    infoTitle: "Детали маршрута",
    infoRows: [
      { label: "Маршрут", value: "Минск → Полоцк → Урбаны → Даугавпилс" },
      { label: "Расстояние", value: "~300 км" },
      { label: "Пограничный переход", value: "Урбаны / Патарниеки (Беларусь–Латвия)" },
      { label: "Время пересечения границы", value: "1–6 ч в зависимости от очереди" },
      { label: "Необходимые документы", value: "Виза Шенген, загранпаспорт" },
      { label: "Ближайший аэропорт", value: "RIX (Рига) — 220 км от Даугавпилса" },
    ],
    includedTitle: "Что включено",
    included: [
      "Подача от адреса в Минске",
      "Прямой маршрут без пересадок",
      "Помощь водителя на границе",
      "Питьевая вода и комфортный салон",
      "Детские кресла по запросу",
      "Фиксированная цена без счётчика",
    ],
    whyTitle: "Почему ComfortLine",
    whyItems: [
      "Один из кратчайших маршрутов в Латвию из Минска",
      "Опытные водители маршрута Минск–Латвия",
      "Знание актуальных очередей на границе Урбаны",
      "Возможен продолжительный маршрут до Риги (+220 км)",
      "Обратный трансфер: из Даугавпилса в Минск",
      "Работаем 24/7, включая праздники",
    ],
    faqTitle: "Часто задаваемые вопросы",
    faq: [
      { q: "Какой маршрут до Даугавпилса?", a: "Едем через Полоцк — КПП Урбаны/Патарниеки — Даугавпилс. Расстояние около 300 км, время в пути 3,5–5 ч без учёта границы." },
      { q: "Нужна ли виза в Латвию?", a: "Гражданам Беларуси требуется шенгенская виза. Уточняйте актуальные требования в посольстве Латвии или на официальных сайтах перед поездкой." },
      { q: "Кто такой Марк Ротко и при чём тут Даугавпилс?", a: "Марк Ротко — один из величайших американских художников XX века, основоположник абстрактного экспрессионизма. Он родился в Даугавпилсе в 1903 году. Центр Марка Ротко в стенах крепости хранит работы мастера и рассказывает его историю." },
      { q: "Можно ли продолжить поездку до Риги?", a: "Да — от Даугавпилса до Риги примерно 220 км (2–2,5 ч). Мы можем сделать остановку в Даугавпилсе и затем везти вас до Риги или аэропорта. Обговорите детали с менеджером при бронировании." },
    ],
    ctaTitle: "Заказать трансфер Минск–Даугавпилс",
    ctaDesc: "Оставьте заявку — менеджер свяжется с вами в ближайшее время и назовёт точную стоимость.",
    ctaBtn: "Оставить заявку",
    prefilledFrom: "Минск",
    prefilledTo: "Даугавпилс",
    backBtn: "← Трансферы в Латвию",
  },
  en: {
    badge: "Daugavpils Transfer",
    title: "Minsk — Daugavpils",
    subtitle: "Direct private transfer from Minsk to Daugavpils — Latvia's second-largest city. A vast 19th-century fortress, the Mark Rothko Art Centre and the multicultural spirit of a city on the Daugava river.",
    stats: [
      { label: "Distance", value: "~300 km" },
      { label: "Travel time", value: "3.5–5 hrs" },
      { label: "Border", value: "Belarus–Latvia" },
      { label: "Vehicle class", value: "Business / Minivan" },
    ],
    photosTitle: "Daugavpils — Highlights",
    photos: [
      { src: "/img/daugavpils/fortress.png", caption: "Daugavpils Fortress — one of the largest well-preserved fortresses in Eastern Europe" },
      { src: "/img/daugavpils/rothko-centre.png", caption: "Mark Rothko Art Centre — a museum inside the fortress dedicated to the great abstract expressionist born here" },
      { src: "/img/daugavpils/city-river.png", caption: "Daugavpils historic centre on the banks of the Daugava river" },
    ],
    howTitle: "How the transfer works",
    steps: [
      { icon: MapPin, title: "Departure from Minsk", desc: "Your driver picks you up at your Minsk address and heads for the Latvian border via the fastest route." },
      { icon: ShieldCheck, title: "Belarus–Latvia border", desc: "Urbany / Pāternieki crossing. Your driver knows current queue conditions and assists at the checkpoint." },
      { icon: Building2, title: "Daugavpils — any address", desc: "We drop you at your hotel, the fortress, the Rothko Centre or any other address in the city." },
    ],
    infoTitle: "Route Details",
    infoRows: [
      { label: "Route", value: "Minsk → Polotsk → Urbany → Daugavpils" },
      { label: "Distance", value: "~300 km" },
      { label: "Border crossing", value: "Urbany / Pāternieki (Belarus–Latvia)" },
      { label: "Border crossing time", value: "1–6 hrs depending on queues" },
      { label: "Documents required", value: "Schengen visa, valid passport" },
      { label: "Nearest airport", value: "RIX (Riga) — 220 km from Daugavpils" },
    ],
    includedTitle: "What's included",
    included: [
      "Pickup from your Minsk address",
      "Direct route — no transfers",
      "Driver assistance at the border",
      "Bottled water and comfortable cabin",
      "Child seats on request",
      "Fixed price — no meter, no surprises",
    ],
    whyTitle: "Why ComfortLine",
    whyItems: [
      "One of the shortest Minsk–Latvia routes",
      "Experienced drivers on the Minsk–Latvia corridor",
      "Up-to-date knowledge of Urbany border queues",
      "Easy extension to Riga (+220 km) on the same trip",
      "Return transfer Daugavpils → Minsk also available",
      "Available 24/7 including public holidays",
    ],
    faqTitle: "Frequently asked questions",
    faq: [
      { q: "What is the route to Daugavpils?", a: "We go via Polotsk – Urbany/Pāternieki border crossing – Daugavpils. Total distance is about 300 km, travel time 3.5–5 hours excluding the border stop." },
      { q: "Do I need a visa to enter Latvia?", a: "Citizens of Belarus require a Schengen visa. Please check the latest requirements with the Latvian embassy or official sources before travelling." },
      { q: "Who is Mark Rothko and what is his connection to Daugavpils?", a: "Mark Rothko is one of the greatest American painters of the 20th century and a pioneer of abstract expressionism. He was born in Daugavpils in 1903. The Mark Rothko Art Centre, located inside the historic fortress, preserves his works and tells his story." },
      { q: "Can we continue on to Riga after Daugavpils?", a: "Yes — Riga is about 220 km (2–2.5 hrs) from Daugavpils. We can stop in Daugavpils and then continue to Riga city or Riga Airport. Just let the manager know when booking." },
    ],
    ctaTitle: "Book Minsk–Daugavpils Transfer",
    ctaDesc: "Submit a request and our manager will contact you shortly with an exact price.",
    ctaBtn: "Request a booking",
    prefilledFrom: "Minsk",
    prefilledTo: "Daugavpils",
    backBtn: "← Latvia transfers",
  },
  seo: {
    titleRu: "Трансфер Минск — Даугавпилс | Латвия | ComfortLine",
    titleEn: "Minsk to Daugavpils Transfer | Latvia | ComfortLine",
    descRu: "Прямой трансфер из Минска в Даугавпилс. ~300 км, 3,5–5 ч. Крепость XIX века, Центр Марка Ротко. Граница Урбаны–Патарниеки, фиксированная цена.",
    descEn: "Direct transfer from Minsk to Daugavpils. ~300 km, 3.5–5 hrs. 19th-c fortress, Mark Rothko Art Centre. Urbany–Pāternieki border, fixed price.",
    pathRu: "/трансфер-минск-даугавпилс",
    pathEn: "/minsk-daugavpils-transfer",
    breadcrumbRu: "Трансфер Минск–Даугавпилс",
    breadcrumbEn: "Minsk — Daugavpils",
    fromName: "Минск",
    toName: "Даугавпилс",
  },
};

export default function MinskDaugavpilsTransferPage() {
  return <RouteLandingPage data={data} />;
}
