import { MapPin, ShieldCheck, Anchor } from "lucide-react";
import { RouteLandingPage, RoutePageData } from "./route-landing-page";

const data: RoutePageData = {
  ru: {
    badge: "Трансфер в Клайпеду",
    title: "Минск — Клайпеда",
    subtitle: "Прямой трансфер из Минска в Клайпеду — портовый город на Балтийском побережье Литвы. Паромы в Швецию и Германию, Куршская коса и старый немецкий город.",
    stats: [
      { label: "Расстояние", value: "~420 км" },
      { label: "Время в пути", value: "5–7 ч" },
      { label: "Граница", value: "Беларусь–Литва" },
      { label: "Класс авто", value: "Бизнес / Минивэн" },
    ],
    photosTitle: "Клайпеда — достопримечательности",
    photos: [
      { src: "/img/klaipeda/old-town.png", caption: "Старый город Клайпеды (бывший немецкий квартал)" },
      { src: "/img/klaipeda/curonian-spit.png", caption: "Куршская коса — объект ЮНЕСКО" },
      { src: "/img/klaipeda/ferry-port.png", caption: "Паромный порт — переправа на Куршскую косу" },
    ],
    howTitle: "Как проходит поездка",
    steps: [
      { icon: MapPin, title: "Выезд из Минска", desc: "Водитель заберёт вас в указанном месте в Минске и выдвинется к литовской границе по оптимальному маршруту." },
      { icon: ShieldCheck, title: "Граница Беларусь–Литва", desc: "Переход Медининкай / Шальчининкай. Водитель знает актуальные очереди и помогает на КПП." },
      { icon: Anchor, title: "Клайпеда: порт и старый город", desc: "Довезём до парома в Швецию или Германию, отеля в старом городе или любого адреса в Клайпеде." },
    ],
    infoTitle: "Детали маршрута",
    infoRows: [
      { label: "Маршрут", value: "Минск → Молодечно → Медининкай → Вильнюс → Каунас → Клайпеда" },
      { label: "Расстояние", value: "~420 км" },
      { label: "Пограничный переход", value: "Медининкай / Шальчининкай (Беларусь–Литва)" },
      { label: "Время пересечения границы", value: "30 мин – 4 ч в зависимости от очереди" },
      { label: "Необходимые документы", value: "Виза Шенген (для граждан не ЕС), загранпаспорт" },
      { label: "Паромы из Клайпеды", value: "DFDS в Киль (Германия), Stena Line в Гётеборг (Швеция)" },
    ],
    includedTitle: "Что включено",
    included: [
      "Подача от адреса в Минске",
      "Прямой маршрут без пересадок",
      "Помощь водителя на границе",
      "Питьевая вода и комфортный салон",
      "Детские кресла по запросу",
      "Фиксированная цена без счётчика",
    ],
    whyTitle: "Почему ComfortLine",
    whyItems: [
      "Опытные водители маршрута Минск–Литва",
      "Знание актуальных очередей на границе",
      "Возможна остановка в Вильнюсе или Каунасе",
      "Обратный трансфер: из Клайпеды в Минск",
      "Работаем 24/7, включая праздники",
      "Перевозим с детьми и питомцами",
    ],
    faqTitle: "Часто задаваемые вопросы",
    faq: [
      { q: "Какой маршрут до Клайпеды?", a: "Едем через Молодечно — Ошмяны — КПП Медининкай/Шальчининкай — Вильнюс — Каунас — Клайпеда. Расстояние около 420 км, время в пути 5–7 ч без учёта границы." },
      { q: "Нужна ли виза в Литву?", a: "Гражданам Беларуси требуется шенгенская виза или национальная виза Литовской Республики. Уточняйте актуальные требования в посольстве или на официальных сайтах." },
      { q: "Можно ли доехать до парома вовремя?", a: "Да, рассчитаем время подачи с учётом времени на паром, очереди на границе и пути. Укажите время отплытия при бронировании." },
      { q: "Можно ли заехать в Вильнюс или Каунас по дороге?", a: "Да, мы можем сделать остановку — договоритесь с менеджером при бронировании, доплата по согласованию." },
    ],
    ctaTitle: "Заказать трансфер Минск–Клайпеда",
    ctaDesc: "Оставьте заявку — менеджер свяжется с вами в течение 15 минут и назовёт точную стоимость.",
    ctaBtn: "Оставить заявку",
    prefilledFrom: "Минск",
    prefilledTo: "Клайпеда",
    backBtn: "← Трансферы в Литву",
  },
  en: {
    badge: "Klaipėda Transfer",
    title: "Minsk — Klaipėda",
    subtitle: "Direct private transfer from Minsk to Klaipėda — Lithuania's Baltic port city. Ferries to Sweden and Germany, the Curonian Spit UNESCO site and a charming old German quarter.",
    stats: [
      { label: "Distance", value: "~420 km" },
      { label: "Travel time", value: "5–7 hrs" },
      { label: "Border", value: "Belarus–Lithuania" },
      { label: "Vehicle class", value: "Business / Minivan" },
    ],
    photosTitle: "Klaipėda — Highlights",
    photos: [
      { src: "/img/klaipeda/old-town.png", caption: "Klaipėda Old Town (former German quarter)" },
      { src: "/img/klaipeda/curonian-spit.png", caption: "Curonian Spit — UNESCO World Heritage Site" },
      { src: "/img/klaipeda/ferry-port.png", caption: "Ferry port — crossing to the Curonian Spit" },
    ],
    howTitle: "How the transfer works",
    steps: [
      { icon: MapPin, title: "Departure from Minsk", desc: "Your driver picks you up at your Minsk address and heads for the Lithuanian border via the fastest route." },
      { icon: ShieldCheck, title: "Belarus–Lithuania border", desc: "Medininkai / Šalčininkai crossing. Your driver knows current queue conditions and assists at the checkpoint." },
      { icon: Anchor, title: "Klaipėda — port & old town", desc: "We drop you at the ferry terminal to Sweden or Germany, your hotel in the old town, or any address in Klaipėda." },
    ],
    infoTitle: "Route Details",
    infoRows: [
      { label: "Route", value: "Minsk → Maladzyechna → Medininkai → Vilnius → Kaunas → Klaipėda" },
      { label: "Distance", value: "~420 km" },
      { label: "Border crossing", value: "Medininkai / Šalčininkai (Belarus–Lithuania)" },
      { label: "Border crossing time", value: "30 min – 4 hrs depending on queues" },
      { label: "Documents required", value: "Schengen visa (non-EU citizens), valid passport" },
      { label: "Ferries from Klaipėda", value: "DFDS to Kiel (Germany), Stena Line to Gothenburg (Sweden)" },
    ],
    includedTitle: "What's included",
    included: [
      "Pickup from your Minsk address",
      "Direct route — no transfers",
      "Driver assistance at the border",
      "Bottled water and comfortable cabin",
      "Child seats on request",
      "Fixed price — no meter, no surprises",
    ],
    whyTitle: "Why ComfortLine",
    whyItems: [
      "Experienced drivers on the Minsk–Lithuania route",
      "Up-to-date knowledge of border queue conditions",
      "Optional stop in Vilnius or Kaunas en route",
      "Return transfer Klaipėda → Minsk also available",
      "Available 24/7 including public holidays",
      "Kids and pets welcome",
    ],
    faqTitle: "Frequently asked questions",
    faq: [
      { q: "What is the route to Klaipėda?", a: "We go via Maladzyechna – Ashmyany – Medininkai/Šalčininkai border crossing – Vilnius – Kaunas – Klaipėda. Total distance is about 420 km, travel time 5–7 hours excluding the border stop." },
      { q: "Do I need a visa to enter Lithuania?", a: "Citizens of Belarus require a Schengen visa or a Lithuanian national visa. Please check the latest requirements with the embassy or official sources before travelling." },
      { q: "Can you get me to the ferry on time?", a: "Yes — we calculate pickup time accounting for your ferry departure, border queues and travel time. Please share your sailing time when booking." },
      { q: "Can we stop in Vilnius or Kaunas on the way?", a: "Yes — we can make a stop. Just let the manager know when booking; an additional charge may apply." },
    ],
    ctaTitle: "Book Minsk–Klaipėda Transfer",
    ctaDesc: "Submit a request and our manager will contact you within 15 minutes with an exact price.",
    ctaBtn: "Request a booking",
    prefilledFrom: "Minsk",
    prefilledTo: "Klaipėda",
    backBtn: "← Lithuania transfers",
  },
  seo: {
    titleRu: "Трансфер Минск — Клайпеда | Паром в Германию и Швецию | ComfortLine",
    titleEn: "Minsk to Klaipėda Transfer | Ferry to Germany & Sweden | ComfortLine",
    descRu: "Прямой трансфер из Минска в Клайпеду. ~420 км, 5–7 ч. Паром в Германию и Швецию, Куршская коса, старый город. Фиксированная цена, граница Беларусь–Литва.",
    descEn: "Direct transfer from Minsk to Klaipėda. ~420 km, 5–7 hrs. Ferries to Germany & Sweden, Curonian Spit, old town. Fixed price, Belarus–Lithuania border crossing.",
    pathRu: "/трансфер-минск-клайпеда",
    pathEn: "/minsk-klaipeda-transfer",
    breadcrumbRu: "Трансфер Минск–Клайпеда",
    breadcrumbEn: "Minsk — Klaipėda",
    fromName: "Минск",
    toName: "Клайпеда",
  },
};

export default function MinskKlaipedaTransferPage() {
  return <RouteLandingPage data={data} />;
}
