import { MapPin, ShieldCheck, Anchor } from "lucide-react";
import { RouteLandingPage, RoutePageData } from "./route-landing-page";

const data: RoutePageData = {
  ru: {
    badge: "Трансфер в Гданьск",
    title: "Минск — Гданьск",
    subtitle: "Прямой трансфер из Минска в Гданьск — жемчужину польского Балтийского побережья. Готический старый город, знаменитый кран на набережной Мотлавы и мировая столица янтаря.",
    stats: [
      { label: "Расстояние", value: "~750 км" },
      { label: "Время в пути", value: "8–11 ч" },
      { label: "Граница", value: "Беларусь–Польша" },
      { label: "Класс авто", value: "Бизнес / Минивэн" },
    ],
    photosTitle: "Гданьск — достопримечательности",
    photos: [
      { src: "/img/gdansk/long-market.png", caption: "Длинный рынок (Długi Targ) — парадная улица старого города" },
      { src: "/img/gdansk/harbour-crane.png", caption: "Гданьский кран (Żuraw) — символ города на реке Мотлава" },
      { src: "/img/gdansk/st-marys-basilica.png", caption: "Базилика Святой Марии — крупнейший кирпичный храм мира" },
    ],
    howTitle: "Как проходит поездка",
    steps: [
      { icon: MapPin, title: "Выезд из Минска", desc: "Водитель заберёт вас по указанному адресу в Минске и направится к польской границе по оптимальному маршруту." },
      { icon: ShieldCheck, title: "Граница Беларусь–Польша", desc: "Переход Брузги / Кузница или Берёза / Половцы. Водитель знает актуальные очереди и помогает на КПП." },
      { icon: Anchor, title: "Гданьск: порт и старый город", desc: "Довезём до отеля в историческом центре, морского порта, порта Сопота или любого адреса в Гданьске." },
    ],
    infoTitle: "Детали маршрута",
    infoRows: [
      { label: "Маршрут", value: "Минск → Брест → Тересполь → Варшава → Гданьск" },
      { label: "Расстояние", value: "~750 км" },
      { label: "Пограничный переход", value: "Брузги / Кузница или Берёза / Половцы (Беларусь–Польша)" },
      { label: "Время пересечения границы", value: "1–8 ч в зависимости от сезона и очереди" },
      { label: "Необходимые документы", value: "Виза Шенген, загранпаспорт" },
      { label: "Аэропорт Гданьска", value: "GDN (им. Леха Валенсы) — 13 км от центра" },
    ],
    includedTitle: "Что включено",
    included: [
      "Подача от адреса в Минске",
      "Прямой маршрут без пересадок",
      "Помощь водителя на границе",
      "Питьевая вода и комфортный салон",
      "Детские кресла по запросу",
      "Фиксированная цена без счётчика",
    ],
    whyTitle: "Почему ComfortLine",
    whyItems: [
      "Опытные водители маршрута Минск–Польша",
      "Знание актуальных очередей на границе",
      "Возможна остановка в Варшаве по дороге",
      "Трёхградье: Гданьск, Сопот, Гдыня в одном трансфере",
      "Обратный трансфер: из Гданьска в Минск",
      "Работаем 24/7, включая праздники",
    ],
    faqTitle: "Часто задаваемые вопросы",
    faq: [
      { q: "Какой маршрут до Гданьска?", a: "Едем через Брест — КПП Брузги/Кузница или Берёза/Половцы — Варшаву — Гданьск. Расстояние около 750 км, время в пути 8–11 ч без учёта границы." },
      { q: "Нужна ли виза в Польшу?", a: "Гражданам Беларуси требуется шенгенская виза. Уточняйте актуальные требования в посольстве Польши или на официальных сайтах перед поездкой." },
      { q: "Можно ли заехать в Сопот или Гдыню?", a: "Да — Трёхградье (Гданьск, Сопот, Гдыня) расположено компактно. Довезём до любой точки агломерации, доплата минимальная." },
      { q: "Можно ли заехать в Варшаву по дороге?", a: "Да, возможна остановка в Варшаве. Договоритесь с менеджером при бронировании, доплата по согласованию." },
    ],
    ctaTitle: "Заказать трансфер Минск–Гданьск",
    ctaDesc: "Оставьте заявку — менеджер свяжется с вами в ближайшее время и назовёт точную стоимость.",
    ctaBtn: "Оставить заявку",
    prefilledFrom: "Минск",
    prefilledTo: "Гданьск",
    backBtn: "← Трансферы в Польшу",
  },
  en: {
    badge: "Gdańsk Transfer",
    title: "Minsk — Gdańsk",
    subtitle: "Direct private transfer from Minsk to Gdańsk — the jewel of Poland's Baltic coast. Gothic old town, the iconic Crane on the Motława river and the world capital of amber.",
    stats: [
      { label: "Distance", value: "~750 km" },
      { label: "Travel time", value: "8–11 hrs" },
      { label: "Border", value: "Belarus–Poland" },
      { label: "Vehicle class", value: "Business / Minivan" },
    ],
    photosTitle: "Gdańsk — Highlights",
    photos: [
      { src: "/img/gdansk/long-market.png", caption: "Długi Targ (Long Market) — the showpiece street of the old town" },
      { src: "/img/gdansk/harbour-crane.png", caption: "Gdańsk Crane (Żuraw) — city symbol on the Motława river" },
      { src: "/img/gdansk/st-marys-basilica.png", caption: "St Mary's Basilica — the world's largest brick church" },
    ],
    howTitle: "How the transfer works",
    steps: [
      { icon: MapPin, title: "Departure from Minsk", desc: "Your driver picks you up at your Minsk address and heads for the Polish border via the fastest route." },
      { icon: ShieldCheck, title: "Belarus–Poland border", desc: "Bruzgi / Kuźnica or Berёza / Połowce crossing. Your driver knows current queue conditions and assists at the checkpoint." },
      { icon: Anchor, title: "Gdańsk — port & old town", desc: "We drop you at your hotel in the historic centre, the sea port, Sopot pier or any address in the Tri-City area." },
    ],
    infoTitle: "Route Details",
    infoRows: [
      { label: "Route", value: "Minsk → Brest → Terespol → Warsaw → Gdańsk" },
      { label: "Distance", value: "~750 km" },
      { label: "Border crossing", value: "Bruzgi / Kuźnica or Berёza / Połowce (Belarus–Poland)" },
      { label: "Border crossing time", value: "1–8 hrs depending on season and queues" },
      { label: "Documents required", value: "Schengen visa, valid passport" },
      { label: "Gdańsk Airport", value: "GDN (Lech Wałęsa Airport) — 13 km from the city centre" },
    ],
    includedTitle: "What's included",
    included: [
      "Pickup from your Minsk address",
      "Direct route — no transfers",
      "Driver assistance at the border",
      "Bottled water and comfortable cabin",
      "Child seats on request",
      "Fixed price — no meter, no surprises",
    ],
    whyTitle: "Why ComfortLine",
    whyItems: [
      "Experienced drivers on the Minsk–Poland route",
      "Up-to-date knowledge of border queue conditions",
      "Optional Warsaw stopover en route",
      "Tri-City coverage: Gdańsk, Sopot and Gdynia in one ride",
      "Return transfer Gdańsk → Minsk also available",
      "Available 24/7 including public holidays",
    ],
    faqTitle: "Frequently asked questions",
    faq: [
      { q: "What is the route to Gdańsk?", a: "We go via Brest – Bruzgi/Kuźnica or Berёza/Połowce border crossing – Warsaw – Gdańsk. Total distance is about 750 km, travel time 8–11 hours excluding the border stop." },
      { q: "Do I need a visa to enter Poland?", a: "Citizens of Belarus require a Schengen visa. Please check the latest requirements with the Polish embassy or official sources before travelling." },
      { q: "Can you take me to Sopot or Gdynia too?", a: "Yes — the Tri-City (Gdańsk, Sopot, Gdynia) is compact. We can drop you anywhere in the agglomeration at minimal extra cost." },
      { q: "Can we stop in Warsaw on the way?", a: "Yes — a Warsaw stop is easy to arrange. Let the manager know when booking; an additional charge may apply." },
    ],
    ctaTitle: "Book Minsk–Gdańsk Transfer",
    ctaDesc: "Submit a request and our manager will contact you shortly with an exact price.",
    ctaBtn: "Request a booking",
    prefilledFrom: "Minsk",
    prefilledTo: "Gdańsk",
    backBtn: "← Poland transfers",
  },
  seo: {
    titleRu: "Трансфер Минск — Гданьск | Польское побережье Балтики | ComfortLine",
    titleEn: "Minsk to Gdańsk Transfer | Polish Baltic Coast | ComfortLine",
    descRu: "Прямой трансфер из Минска в Гданьск. ~750 км, 8–11 ч. Длинный рынок, кран Журав, Сопот. Граница Беларусь–Польша, фиксированная цена.",
    descEn: "Direct transfer from Minsk to Gdańsk. ~750 km, 8–11 hrs. Long Market, Żuraw crane, Sopot. Belarus–Poland border crossing, fixed price.",
    pathRu: "/трансфер-минск-гданьск",
    pathEn: "/minsk-gdansk-transfer",
    breadcrumbRu: "Трансфер Минск–Гданьск",
    breadcrumbEn: "Minsk — Gdańsk",
    fromName: "Минск",
    toName: "Гданьск",
  },
};

export default function MinskGdanskTransferPage() {
  return <RouteLandingPage data={data} />;
}
