import { MapPin, ShieldCheck, Waves } from "lucide-react";
import { RouteLandingPage, RoutePageData } from "./route-landing-page";

const data: RoutePageData = {
  ru: {
    badge: "Трансфер в Палангу",
    title: "Минск — Паланга",
    subtitle: "Прямой трансфер из Минска в Палангу — курортный город на берегу Балтийского моря. Янтарный музей, знаменитый пирс, сосновый парк и широкий пляж.",
    stats: [
      { label: "Расстояние", value: "~390 км" },
      { label: "Время в пути", value: "5–7 ч" },
      { label: "Граница", value: "Беларусь–Литва" },
      { label: "Класс авто", value: "Бизнес / Минивэн" },
    ],
    photosTitle: "Паланга — достопримечательности",
    photos: [
      { src: "/img/palanga/pier.png", caption: "Палангский пирс на Балтийском море" },
      { src: "/img/palanga/amber-museum.png", caption: "Янтарный музей (дворец Тышкевичей)" },
      { src: "/img/palanga/beach.png", caption: "Пляж Паланги — широкая песчаная полоса" },
    ],
    howTitle: "Как проходит поездка",
    steps: [
      { icon: MapPin, title: "Выезд из Минска", desc: "Водитель заберёт вас в указанном месте в Минске и выдвинется к литовской границе по оптимальному маршруту." },
      { icon: ShieldCheck, title: "Граница Беларусь–Литва", desc: "Переход Медининкай / Шальчининкай. Водитель знает актуальные очереди и помогает на КПП." },
      { icon: Waves, title: "Паланга: море и курорт", desc: "Довезём до отеля, пирса, аэропорта PLQ или любого адреса в Паланге и окрестностях." },
    ],
    infoTitle: "Детали маршрута",
    infoRows: [
      { label: "Маршрут", value: "Минск → Молодечно → Медининкай → Вильнюс → Каунас → Паланга" },
      { label: "Расстояние", value: "~390 км" },
      { label: "Пограничный переход", value: "Медининкай / Шальчининкай (Беларусь–Литва)" },
      { label: "Время пересечения границы", value: "30 мин – 4 ч в зависимости от очереди" },
      { label: "Необходимые документы", value: "Виза Шенген (для граждан не ЕС), загранпаспорт" },
      { label: "Аэропорт Паланги", value: "PLQ — сезонные рейсы Ryanair" },
    ],
    includedTitle: "Что включено",
    included: [
      "Подача от адреса в Минске",
      "Прямой маршрут без пересадок",
      "Помощь водителя на границе",
      "Питьевая вода и комфортный салон",
      "Детские кресла по запросу",
      "Фиксированная цена без счётчика",
    ],
    whyTitle: "Почему ComfortLine",
    whyItems: [
      "Опытные водители маршрута Минск–Литва",
      "Знание актуальных очередей на границе",
      "Возможна остановка в Вильнюсе или Каунасе",
      "Обратный трансфер: из Паланги в Минск",
      "Работаем 24/7, включая праздники",
      "Перевозим с детьми и питомцами",
    ],
    faqTitle: "Часто задаваемые вопросы",
    faq: [
      { q: "Какой маршрут до Паланги?", a: "Едем через Молодечно — Ошмяны — КПП Медининкай/Шальчининкай — Вильнюс — Каунас — Паланга. Расстояние около 390 км, время в пути 5–7 ч без учёта границы." },
      { q: "Нужна ли виза в Литву?", a: "Гражданам Беларуси требуется шенгенская виза или национальная виза Литовской Республики. Уточняйте актуальные требования в посольстве или на официальных сайтах." },
      { q: "Можно ли заехать в Вильнюс или Каунас по дороге?", a: "Да, мы можем сделать остановку — договоритесь с менеджером при бронировании, доплата по согласованию." },
      { q: "Работаете ли вы в курортный сезон?", a: "Да, мы работаем круглосуточно и весь год. В летний сезон (июнь–август) рекомендуем бронировать заранее." },
    ],
    ctaTitle: "Заказать трансфер Минск–Паланга",
    ctaDesc: "Оставьте заявку — менеджер свяжется с вами в ближайшее время и назовёт точную стоимость.",
    ctaBtn: "Оставить заявку",
    prefilledFrom: "Минск",
    prefilledTo: "Паланга",
    backBtn: "← Трансферы в Литву",
  },
  en: {
    badge: "Palanga Transfer",
    title: "Minsk — Palanga",
    subtitle: "Direct private transfer from Minsk to Palanga — Lithuania's premier Baltic Sea resort. Amber Museum, the famous pier, Birutė Park and a wide sandy beach await.",
    stats: [
      { label: "Distance", value: "~390 km" },
      { label: "Travel time", value: "5–7 hrs" },
      { label: "Border", value: "Belarus–Lithuania" },
      { label: "Vehicle class", value: "Business / Minivan" },
    ],
    photosTitle: "Palanga — Highlights",
    photos: [
      { src: "/img/palanga/pier.png", caption: "Palanga Pier on the Baltic Sea" },
      { src: "/img/palanga/amber-museum.png", caption: "Amber Museum (Tyszkiewicz Palace)" },
      { src: "/img/palanga/beach.png", caption: "Palanga beach — wide sandy shore" },
    ],
    howTitle: "How the transfer works",
    steps: [
      { icon: MapPin, title: "Departure from Minsk", desc: "Your driver picks you up at your Minsk address and heads for the Lithuanian border via the fastest route." },
      { icon: ShieldCheck, title: "Belarus–Lithuania border", desc: "Medininkai / Šalčininkai crossing. Your driver knows current queue conditions and assists at the checkpoint." },
      { icon: Waves, title: "Palanga — sea & resort", desc: "We drop you at your hotel, the pier, Palanga Airport (PLQ) or any address in and around Palanga." },
    ],
    infoTitle: "Route Details",
    infoRows: [
      { label: "Route", value: "Minsk → Maladzyechna → Medininkai → Vilnius → Kaunas → Palanga" },
      { label: "Distance", value: "~390 km" },
      { label: "Border crossing", value: "Medininkai / Šalčininkai (Belarus–Lithuania)" },
      { label: "Border crossing time", value: "30 min – 4 hrs depending on queues" },
      { label: "Documents required", value: "Schengen visa (non-EU citizens), valid passport" },
      { label: "Palanga Airport", value: "PLQ — seasonal Ryanair flights" },
    ],
    includedTitle: "What's included",
    included: [
      "Pickup from your Minsk address",
      "Direct route — no transfers",
      "Driver assistance at the border",
      "Bottled water and comfortable cabin",
      "Child seats on request",
      "Fixed price — no meter, no surprises",
    ],
    whyTitle: "Why ComfortLine",
    whyItems: [
      "Experienced drivers on the Minsk–Lithuania route",
      "Up-to-date knowledge of border queue conditions",
      "Optional stop in Vilnius or Kaunas en route",
      "Return transfer Palanga → Minsk also available",
      "Available 24/7 including public holidays",
      "Kids and pets welcome",
    ],
    faqTitle: "Frequently asked questions",
    faq: [
      { q: "What is the route to Palanga?", a: "We go via Maladzyechna – Ashmyany – Medininkai/Šalčininkai border crossing – Vilnius – Kaunas – Palanga. Total distance is about 390 km, travel time 5–7 hours excluding the border stop." },
      { q: "Do I need a visa to enter Lithuania?", a: "Citizens of Belarus require a Schengen visa or a Lithuanian national visa. Please check the latest requirements with the embassy or official sources before travelling." },
      { q: "Can we stop in Vilnius or Kaunas on the way?", a: "Yes — we can make a stop. Just let the manager know when booking; an additional charge may apply." },
      { q: "Do you operate in the summer season?", a: "Yes, we run 24/7 all year round. In peak summer (June–August) we recommend booking in advance." },
    ],
    ctaTitle: "Book Minsk–Palanga Transfer",
    ctaDesc: "Submit a request and our manager will contact you shortly with an exact price.",
    ctaBtn: "Request a booking",
    prefilledFrom: "Minsk",
    prefilledTo: "Palanga",
    backBtn: "← Lithuania transfers",
  },
  seo: {
    titleRu: "Трансфер Минск — Паланга | Прямая поездка на Балтику | ComfortLine",
    titleEn: "Minsk to Palanga Transfer | Direct Ride to the Baltic | ComfortLine",
    descRu: "Прямой трансфер из Минска в Палангу. ~390 км, 5–7 ч. Балтийское море, янтарный музей, пирс. Фиксированная цена, опытный водитель, граница Беларусь–Литва.",
    descEn: "Direct transfer from Minsk to Palanga. ~390 km, 5–7 hrs. Baltic Sea, Amber Museum, pier. Fixed price, professional driver, Belarus–Lithuania border crossing.",
    pathRu: "/трансфер-минск-паланга",
    pathEn: "/minsk-palanga-transfer",
    breadcrumbRu: "Трансфер Минск–Паланга",
    breadcrumbEn: "Minsk — Palanga",
    fromName: "Минск",
    toName: "Паланга",
  },
};

export default function MinskPalangaTransferPage() {
  return <RouteLandingPage data={data} />;
}
