import { MapPin, ShieldCheck, Building2 } from "lucide-react";
import { RouteLandingPage, RoutePageData } from "./route-landing-page";

const data: RoutePageData = {
  ru: {
    badge: "Трансфер в Познань",
    title: "Минск — Познань",
    subtitle: "Прямой трансфер из Минска в Познань — один из старейших городов Польши, колыбель государственности Пястов. Яркая рыночная площадь, козлы на Ратуше и старейший польский собор.",
    stats: [
      { label: "Расстояние", value: "~700 км" },
      { label: "Время в пути", value: "7–10 ч" },
      { label: "Граница", value: "Беларусь–Польша" },
      { label: "Класс авто", value: "Бизнес / Минивэн" },
    ],
    photosTitle: "Познань — достопримечательности",
    photos: [
      { src: "/img/poznan/old-market-square.png", caption: "Старый рынок (Stary Rynek) — одна из красивейших площадей Польши" },
      { src: "/img/poznan/town-hall.png", caption: "Ратуша Познани — шедевр польского Ренессанса" },
      { src: "/img/poznan/cathedral.png", caption: "Собор Святых Апостолов на острове Тумском — старейший в Польше" },
    ],
    howTitle: "Как проходит поездка",
    steps: [
      { icon: MapPin, title: "Выезд из Минска", desc: "Водитель заберёт вас по указанному адресу в Минске и направится к польской границе по оптимальному маршруту." },
      { icon: ShieldCheck, title: "Граница Беларусь–Польша", desc: "Переход Брузги / Кузница или Берёза / Половцы. Водитель знает актуальные очереди и помогает на КПП." },
      { icon: Building2, title: "Познань: любой адрес", desc: "Довезём до отеля у Старого рынка, аэропорта POZ или любого другого адреса в городе." },
    ],
    infoTitle: "Детали маршрута",
    infoRows: [
      { label: "Маршрут", value: "Минск → Брест → Тересполь → Варшава → Познань" },
      { label: "Расстояние", value: "~700 км" },
      { label: "Пограничный переход", value: "Брузги / Кузница или Берёза / Половцы (Беларусь–Польша)" },
      { label: "Время пересечения границы", value: "1–8 ч в зависимости от сезона и очереди" },
      { label: "Необходимые документы", value: "Виза Шенген, загранпаспорт" },
      { label: "Аэропорт Познани", value: "POZ (им. Генрика Венявского) — 7 км от центра" },
    ],
    includedTitle: "Что включено",
    included: [
      "Подача от адреса в Минске",
      "Прямой маршрут без пересадок",
      "Помощь водителя на границе",
      "Питьевая вода и комфортный салон",
      "Детские кресла по запросу",
      "Фиксированная цена без счётчика",
    ],
    whyTitle: "Почему ComfortLine",
    whyItems: [
      "Опытные водители маршрута Минск–Польша",
      "Знание актуальных очередей на границе",
      "Возможна остановка в Варшаве по дороге",
      "Обратный трансфер: из Познани в Минск",
      "Работаем 24/7, включая праздники",
      "Перевозим с детьми и питомцами",
    ],
    faqTitle: "Часто задаваемые вопросы",
    faq: [
      { q: "Какой маршрут до Познани?", a: "Едем через Брест — КПП Брузги/Кузница или Берёза/Половцы — Варшаву — Познань. Расстояние около 700 км, время в пути 7–10 ч без учёта границы." },
      { q: "Нужна ли виза в Польшу?", a: "Гражданам Беларуси требуется шенгенская виза. Уточняйте актуальные требования в посольстве Польши или на официальных сайтах перед поездкой." },
      { q: "Что такое «козлы на Ратуше»?", a: "Каждый день в полдень из башни Ратуши Познани выезжают два механических козла и бьют рогами. Это символ города с XVI века — одна из самых любимых туристических традиций Польши." },
      { q: "Можно ли заехать в Варшаву по дороге?", a: "Да, маршрут проходит через Варшаву. Остановка добавляет минимум времени — договоритесь с менеджером при бронировании." },
    ],
    ctaTitle: "Заказать трансфер Минск–Познань",
    ctaDesc: "Оставьте заявку — менеджер свяжется с вами в течение 15 минут и назовёт точную стоимость.",
    ctaBtn: "Оставить заявку",
    prefilledFrom: "Минск",
    prefilledTo: "Познань",
    backBtn: "← Трансферы в Польшу",
  },
  en: {
    badge: "Poznań Transfer",
    title: "Minsk — Poznań",
    subtitle: "Direct private transfer from Minsk to Poznań — one of Poland's oldest cities and the cradle of the Piast dynasty. A vibrant market square, billy goats on the Town Hall clock and Poland's oldest cathedral.",
    stats: [
      { label: "Distance", value: "~700 km" },
      { label: "Travel time", value: "7–10 hrs" },
      { label: "Border", value: "Belarus–Poland" },
      { label: "Vehicle class", value: "Business / Minivan" },
    ],
    photosTitle: "Poznań — Highlights",
    photos: [
      { src: "/img/poznan/old-market-square.png", caption: "Stary Rynek (Old Market Square) — one of Poland's most beautiful squares" },
      { src: "/img/poznan/town-hall.png", caption: "Poznań Town Hall — a masterpiece of Polish Renaissance architecture" },
      { src: "/img/poznan/cathedral.png", caption: "Cathedral of SS. Peter and Paul on Cathedral Island — Poland's oldest cathedral" },
    ],
    howTitle: "How the transfer works",
    steps: [
      { icon: MapPin, title: "Departure from Minsk", desc: "Your driver picks you up at your Minsk address and heads for the Polish border via the fastest route." },
      { icon: ShieldCheck, title: "Belarus–Poland border", desc: "Bruzgi / Kuźnica or Berёza / Połowce crossing. Your driver knows current queue conditions and assists at the checkpoint." },
      { icon: Building2, title: "Poznań — any address", desc: "We drop you at your hotel near the Old Market Square, Poznań Airport (POZ) or any other address in the city." },
    ],
    infoTitle: "Route Details",
    infoRows: [
      { label: "Route", value: "Minsk → Brest → Terespol → Warsaw → Poznań" },
      { label: "Distance", value: "~700 km" },
      { label: "Border crossing", value: "Bruzgi / Kuźnica or Berёza / Połowce (Belarus–Poland)" },
      { label: "Border crossing time", value: "1–8 hrs depending on season and queues" },
      { label: "Documents required", value: "Schengen visa, valid passport" },
      { label: "Poznań Airport", value: "POZ (Henryk Wieniawski Airport) — 7 km from the centre" },
    ],
    includedTitle: "What's included",
    included: [
      "Pickup from your Minsk address",
      "Direct route — no transfers",
      "Driver assistance at the border",
      "Bottled water and comfortable cabin",
      "Child seats on request",
      "Fixed price — no meter, no surprises",
    ],
    whyTitle: "Why ComfortLine",
    whyItems: [
      "Experienced drivers on the Minsk–Poland route",
      "Up-to-date knowledge of border queue conditions",
      "Optional Warsaw stopover en route",
      "Return transfer Poznań → Minsk also available",
      "Available 24/7 including public holidays",
      "Kids and pets welcome",
    ],
    faqTitle: "Frequently asked questions",
    faq: [
      { q: "What is the route to Poznań?", a: "We go via Brest – Bruzgi/Kuźnica or Berёza/Połowce border crossing – Warsaw – Poznań. Total distance is about 700 km, travel time 7–10 hours excluding the border stop." },
      { q: "Do I need a visa to enter Poland?", a: "Citizens of Belarus require a Schengen visa. Please check the latest requirements with the Polish embassy or official sources before travelling." },
      { q: "What are the famous billy goats of Poznań?", a: "Every day at noon, two mechanical billy goats emerge from the Town Hall tower and butt heads — a tradition dating back to the 16th century and one of Poland's most beloved tourist rituals." },
      { q: "Can we stop in Warsaw on the way?", a: "Yes — the route passes through Warsaw, so a stop adds very little extra time. Let the manager know when booking." },
    ],
    ctaTitle: "Book Minsk–Poznań Transfer",
    ctaDesc: "Submit a request and our manager will contact you within 15 minutes with an exact price.",
    ctaBtn: "Request a booking",
    prefilledFrom: "Minsk",
    prefilledTo: "Poznań",
    backBtn: "← Poland transfers",
  },
  seo: {
    titleRu: "Трансфер Минск — Познань | Старейший город Польши | ComfortLine",
    titleEn: "Minsk to Poznań Transfer | Poland's Ancient Capital | ComfortLine",
    descRu: "Прямой трансфер из Минска в Познань. ~700 км, 7–10 ч. Старый рынок, Ратуша с козлами, Тумский собор. Граница Беларусь–Польша, фиксированная цена.",
    descEn: "Direct transfer from Minsk to Poznań. ~700 km, 7–10 hrs. Old Market Square, Town Hall billy goats, Cathedral Island. Belarus–Poland border crossing, fixed price.",
    pathRu: "/трансфер-минск-познань",
    pathEn: "/minsk-poznan-transfer",
    breadcrumbRu: "Трансфер Минск–Познань",
    breadcrumbEn: "Minsk — Poznań",
    fromName: "Минск",
    toName: "Познань",
  },
};

export default function MinskPoznanTransferPage() {
  return <RouteLandingPage data={data} />;
}
