import { MapPin, ShieldCheck, Building2 } from "lucide-react";
import { RouteLandingPage, RoutePageData } from "./route-landing-page";

const data: RoutePageData = {
  ru: {
    badge: "Трансфер в Каунас",
    title: "Минск — Каунас",
    subtitle: "Прямой трансфер из Минска в Каунас — второй по величине город Литвы. Исторический центр, аэропорт KUN или любой адрес без пересадок и задержек.",
    stats: [
      { label: "Расстояние", value: "~220 км" },
      { label: "Время в пути", value: "3–4.5 ч" },
      { label: "Граница", value: "Беларусь–Литва" },
      { label: "Класс авто", value: "Бизнес / Минивэн" },
    ],
    photosTitle: "Каунас — достопримечательности",
    photos: [
      { src: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Kaunas_Town_Hall.jpg/1280px-Kaunas_Town_Hall.jpg", caption: "Каунасская ратуша («Белый лебедь»)" },
      { src: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/KaunasOldTown.jpg/1280px-KaunasOldTown.jpg", caption: "Старый город Каунаса" },
      { src: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Laisves_aleja_in_Kaunas.JPG/1280px-Laisves_aleja_in_Kaunas.JPG", caption: "Аллея свободы (Laisvės alėja)" },
    ],
    howTitle: "Как проходит поездка",
    steps: [
      { icon: MapPin, title: "Выезд из Минска", desc: "Водитель заберёт вас в указанном месте в Минске и выдвинется к литовской границе по оптимальному маршруту." },
      { icon: ShieldCheck, title: "Граница Беларусь–Литва", desc: "Переход Медининкай / Шальчининкай. Водитель знает актуальные очереди и помогает на КПП." },
      { icon: Building2, title: "Каунас: любой адрес", desc: "Старый город, аллея Свободы, аэропорт KUN, отель или бизнес-центр — доставим точно по назначению." },
    ],
    infoTitle: "Детали маршрута",
    infoRows: [
      { label: "Маршрут", value: "Минск → Молодечно → Медининкай → Вильнюс → Каунас" },
      { label: "Расстояние", value: "~220 км" },
      { label: "Пограничный переход", value: "Медининкай / Шальчининкай (Беларусь–Литва)" },
      { label: "Время пересечения границы", value: "30 мин – 4 ч в зависимости от очереди" },
      { label: "Необходимые документы", value: "Виза Шенген (для граждан не ЕС), загранпаспорт" },
      { label: "Аэропорт Каунаса", value: "KUN — рейсы Ryanair в Лондон, Дублин, Берлин и др." },
    ],
    includedTitle: "Что включено",
    included: [
      "Подача от адреса в Минске",
      "Прямой маршрут без пересадок",
      "Помощь водителя на границе",
      "Питьевая вода и комфортный салон",
      "Детские кресла по запросу",
      "Фиксированная цена без счётчика",
    ],
    whyTitle: "Почему ComfortLine",
    whyItems: [
      "Опытные водители маршрута Минск–Литва",
      "Знание актуальных очередей на границе",
      "Возможна остановка в Вильнюсе по пути",
      "Обратный трансфер: из Каунаса в Минск",
      "Работаем 24/7, включая праздники",
      "Перевозим с детьми и питомцами",
    ],
    faqTitle: "Часто задаваемые вопросы",
    faq: [
      { q: "Какой маршрут до Каунаса?", a: "Обычно едем через Молодечно — Ошмяны — КПП Медининкай/Шальчининкай — Вильнюс — Каунас. Расстояние около 220 км, время в пути 3–4.5 ч без учёта границы." },
      { q: "Нужна ли виза в Литву?", a: "Граждане Беларуси и России нуждаются в шенгенской визе или визе Литовской Республики. Пожалуйста, уточняйте актуальные требования в посольстве или на официальных сайтах." },
      { q: "Можно ли заехать в Вильнюс по дороге?", a: "Да, мы можем сделать остановку в Вильнюсе — договоритесь с менеджером при бронировании, доплата по согласованию." },
      { q: "Можно ли уехать ночью или рано утром?", a: "Да, мы работаем круглосуточно. Сообщите желаемое время вылета — рассчитаем оптимальное время подачи автомобиля." },
    ],
    ctaTitle: "Заказать трансфер Минск–Каунас",
    ctaDesc: "Оставьте заявку — менеджер свяжется с вами в течение 15 минут и назовёт точную стоимость.",
    ctaBtn: "Оставить заявку",
    prefilledFrom: "Минск",
    prefilledTo: "Каунас",
    backBtn: "← Трансферы в Литву",
  },
  en: {
    badge: "Kaunas Transfer",
    title: "Minsk — Kaunas",
    subtitle: "Direct private transfer from Minsk to Kaunas — Lithuania's second largest city. Historical Old Town, KUN airport or any address, without changes or delays.",
    stats: [
      { label: "Distance", value: "~220 km" },
      { label: "Travel time", value: "3–4.5 hrs" },
      { label: "Border", value: "Belarus–Lithuania" },
      { label: "Vehicle class", value: "Business / Minivan" },
    ],
    photosTitle: "Kaunas — Highlights",
    photos: [
      { src: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Kaunas_Town_Hall.jpg/1280px-Kaunas_Town_Hall.jpg", caption: "Kaunas Town Hall (\"White Swan\")" },
      { src: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/KaunasOldTown.jpg/1280px-KaunasOldTown.jpg", caption: "Kaunas Old Town" },
      { src: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Laisves_aleja_in_Kaunas.JPG/1280px-Laisves_aleja_in_Kaunas.JPG", caption: "Laisvės alėja (Freedom Avenue)" },
    ],
    howTitle: "How the transfer works",
    steps: [
      { icon: MapPin, title: "Departure from Minsk", desc: "Your driver picks you up at your Minsk address and heads for the Lithuanian border via the fastest route." },
      { icon: ShieldCheck, title: "Belarus–Lithuania border", desc: "Medininkai / Šalčininkai crossing. Your driver knows current queue conditions and assists at the checkpoint." },
      { icon: Building2, title: "Kaunas — any address", desc: "Old Town, Laisvės alėja, KUN airport, your hotel or business centre — wherever you need to be." },
    ],
    infoTitle: "Route Details",
    infoRows: [
      { label: "Route", value: "Minsk → Maladzyechna → Medininkai → Vilnius → Kaunas" },
      { label: "Distance", value: "~220 km" },
      { label: "Border crossing", value: "Medininkai / Šalčininkai (Belarus–Lithuania)" },
      { label: "Border crossing time", value: "30 min – 4 hrs depending on queues" },
      { label: "Documents required", value: "Schengen visa (non-EU citizens), valid passport" },
      { label: "Kaunas Airport", value: "KUN — Ryanair flights to London, Dublin, Berlin and more" },
    ],
    includedTitle: "What's included",
    included: [
      "Pickup from your Minsk address",
      "Direct route — no transfers",
      "Driver assistance at the border",
      "Bottled water and comfortable cabin",
      "Child seats on request",
      "Fixed price — no meter, no surprises",
    ],
    whyTitle: "Why ComfortLine",
    whyItems: [
      "Experienced drivers on the Minsk–Lithuania route",
      "Up-to-date knowledge of border queue conditions",
      "Optional stop in Vilnius en route",
      "Return transfer Kaunas → Minsk also available",
      "Available 24/7 including public holidays",
      "Kids and pets welcome",
    ],
    faqTitle: "Frequently asked questions",
    faq: [
      { q: "What is the route to Kaunas?", a: "We typically go via Maladzyechna – Ashmyany – Medininkai/Šalčininkai border crossing – Vilnius – Kaunas. Total distance is about 220 km, travel time 3–4.5 hours excluding the border stop." },
      { q: "Do I need a visa to enter Lithuania?", a: "Citizens of Belarus and Russia require a Schengen visa or a Lithuanian national visa. Please check the latest requirements with the embassy or official sources before travelling." },
      { q: "Can we stop in Vilnius on the way?", a: "Yes — we can make a stop in Vilnius. Just let the manager know when booking; an additional charge may apply." },
      { q: "Can I travel at night or very early morning?", a: "Yes, we operate 24/7. Just tell us your preferred departure time and we'll calculate the optimal pickup time." },
    ],
    ctaTitle: "Book Minsk–Kaunas Transfer",
    ctaDesc: "Submit a request and our manager will contact you within 15 minutes with an exact price.",
    ctaBtn: "Request a booking",
    prefilledFrom: "Minsk",
    prefilledTo: "Kaunas",
    backBtn: "← Lithuania transfers",
  },
  seo: {
    titleRu: "Трансфер Минск — Каунас | Прямая поездка в Литву | ComfortLine",
    titleEn: "Minsk to Kaunas Transfer | Direct Ride to Lithuania | ComfortLine",
    descRu: "Прямой трансфер из Минска в Каунас. ~220 км, 3–4.5 ч. Старый город, аллея Свободы, аэропорт KUN. Фиксированная цена, опытный водитель, граница Беларусь–Литва.",
    descEn: "Direct transfer from Minsk to Kaunas. ~220 km, 3–4.5 hrs. Old Town, Laisvės alėja, KUN airport. Fixed price, professional driver, Belarus–Lithuania border crossing.",
    pathRu: "/трансфер-минск-каунас",
    pathEn: "/minsk-kaunas-transfer",
    breadcrumbRu: "Трансфер Минск–Каунас",
    breadcrumbEn: "Minsk — Kaunas",
    fromName: "Минск",
    toName: "Каунас",
  },
};

export default function MinskKaunasTransferPage() {
  return <RouteLandingPage data={data} />;
}
