import { MapPin, ShieldCheck, Building2 } from "lucide-react";
import { RouteLandingPage, RoutePageData } from "./route-landing-page";

const data: RoutePageData = {
  ru: {
    badge: "Трансфер в Юрмалу",
    title: "Минск — Юрмала",
    subtitle: "Прямой трансфер из Минска в Юрмалу — жемчужину Балтийского побережья. Белый песок, сосновый воздух, деревянные виллы в стиле модерн и лучшие санатории Латвии.",
    stats: [
      { label: "Расстояние", value: "~490 км" },
      { label: "Время в пути", value: "5.5–7 ч" },
      { label: "Граница", value: "Беларусь–Латвия" },
      { label: "Класс авто", value: "Бизнес / Минивэн" },
    ],
    photosTitle: "Юрмала — достопримечательности",
    photos: [
      { src: "/img/jurmala/beach.png", caption: "Пляж Майори — белый песок, чистый воздух и сосны у самой воды" },
      { src: "/img/jurmala/wooden-villas.png", caption: "Деревянные дачи в стиле модерн — визитная карточка Юрмалы" },
      { src: "/img/jurmala/pine-forest.png", caption: "Дзинтарский лесопарк — сосновый бор прямо между пляжем и городом" },
    ],
    howTitle: "Как проходит поездка",
    steps: [
      { icon: MapPin, title: "Выезд из Минска", desc: "Водитель заберёт вас по указанному адресу в Минске и направится к латвийской границе по оптимальному маршруту." },
      { icon: ShieldCheck, title: "Граница Беларусь–Латвия", desc: "Переход Урбаны / Патарниеки. Водитель знает актуальные очереди и помогает на КПП." },
      { icon: Building2, title: "Юрмала: любой адрес", desc: "Довезём до санатория, отеля у пляжа, улицы Йомас или любого другого адреса в городе." },
    ],
    infoTitle: "Детали маршрута",
    infoRows: [
      { label: "Маршрут", value: "Минск → Урбаны → Рига → Юрмала" },
      { label: "Расстояние", value: "~490 км (~470 км до Риги + 25 км)" },
      { label: "Пограничный переход", value: "Урбаны / Патарниеки (Беларусь–Латвия)" },
      { label: "Время пересечения границы", value: "1–6 ч в зависимости от очереди" },
      { label: "Необходимые документы", value: "Виза Шенген, загранпаспорт" },
      { label: "Ближайший аэропорт", value: "RIX (Рига) — 30 км от Юрмалы" },
    ],
    includedTitle: "Что включено",
    included: [
      "Подача от адреса в Минске",
      "Прямой маршрут без пересадок",
      "Помощь водителя на границе",
      "Питьевая вода и комфортный салон",
      "Детские кресла по запросу",
      "Фиксированная цена без счётчика",
    ],
    whyTitle: "Почему ComfortLine",
    whyItems: [
      "Прямо до санатория или отеля в Юрмале без пересадок",
      "Опытные водители маршрута Минск–Латвия",
      "Знание актуальных очередей на границе Урбаны",
      "Остановка в Риге по пути — по запросу",
      "Обратный трансфер: из Юрмалы в Минск",
      "Работаем 24/7, включая праздники",
    ],
    faqTitle: "Часто задаваемые вопросы",
    faq: [
      { q: "Какой маршрут до Юрмалы?", a: "Едем через КПП Урбаны/Патарниеки — Ригу — Юрмалу. Расстояние около 490 км (470 км до Риги плюс 25 км до Юрмалы), время в пути 5,5–7 ч без учёта границы." },
      { q: "Нужна ли виза в Латвию?", a: "Гражданам Беларуси требуется шенгенская виза. Уточняйте актуальные требования в посольстве Латвии или на официальных сайтах перед поездкой." },
      { q: "Можно ли заехать в Ригу по дороге?", a: "Да — маршрут проходит через Ригу. Остановка добавляет минимум времени. Договоритесь с менеджером при бронировании." },
      { q: "До какого санатория или отеля вы довезёте?", a: "До любого. Укажите точный адрес в Юрмале при бронировании — водитель доставит вас прямо ко входу." },
    ],
    ctaTitle: "Заказать трансфер Минск–Юрмала",
    ctaDesc: "Оставьте заявку — менеджер свяжется с вами в ближайшее время и назовёт точную стоимость.",
    ctaBtn: "Оставить заявку",
    prefilledFrom: "Минск",
    prefilledTo: "Юрмала",
    backBtn: "← Трансферы в Латвию",
  },
  en: {
    badge: "Jūrmala Transfer",
    title: "Minsk — Jūrmala",
    subtitle: "Direct private transfer from Minsk to Jūrmala — the pearl of the Baltic coast. White sand, pine-scented air, ornate Art Nouveau wooden villas and Latvia's finest spa resorts.",
    stats: [
      { label: "Distance", value: "~490 km" },
      { label: "Travel time", value: "5.5–7 hrs" },
      { label: "Border", value: "Belarus–Latvia" },
      { label: "Vehicle class", value: "Business / Minivan" },
    ],
    photosTitle: "Jūrmala — Highlights",
    photos: [
      { src: "/img/jurmala/beach.png", caption: "Majori Beach — white sand, clean air and pine trees right at the water's edge" },
      { src: "/img/jurmala/wooden-villas.png", caption: "Art Nouveau wooden dachas — the architectural signature of Jūrmala" },
      { src: "/img/jurmala/pine-forest.png", caption: "Dzintari Forest Park — fragrant pine forest stretching between the beach and the town" },
    ],
    howTitle: "How the transfer works",
    steps: [
      { icon: MapPin, title: "Departure from Minsk", desc: "Your driver picks you up at your Minsk address and heads for the Latvian border via the fastest route." },
      { icon: ShieldCheck, title: "Belarus–Latvia border", desc: "Urbany / Pāternieki crossing. Your driver knows current queue conditions and assists at the checkpoint." },
      { icon: Building2, title: "Jūrmala — any address", desc: "We drop you at your sanatorium, beachside hotel, Jomas Street or any other address in the resort." },
    ],
    infoTitle: "Route Details",
    infoRows: [
      { label: "Route", value: "Minsk → Urbany → Riga → Jūrmala" },
      { label: "Distance", value: "~490 km (~470 km to Riga + 25 km)" },
      { label: "Border crossing", value: "Urbany / Pāternieki (Belarus–Latvia)" },
      { label: "Border crossing time", value: "1–6 hrs depending on queues" },
      { label: "Documents required", value: "Schengen visa, valid passport" },
      { label: "Nearest airport", value: "RIX (Riga) — 30 km from Jūrmala" },
    ],
    includedTitle: "What's included",
    included: [
      "Pickup from your Minsk address",
      "Direct route — no transfers",
      "Driver assistance at the border",
      "Bottled water and comfortable cabin",
      "Child seats on request",
      "Fixed price — no meter, no surprises",
    ],
    whyTitle: "Why ComfortLine",
    whyItems: [
      "Door-to-door delivery to your sanatorium or hotel in Jūrmala",
      "Experienced drivers on the Minsk–Latvia corridor",
      "Up-to-date knowledge of Urbany border queues",
      "Optional Riga stopover en route — on request",
      "Return transfer Jūrmala → Minsk also available",
      "Available 24/7 including public holidays",
    ],
    faqTitle: "Frequently asked questions",
    faq: [
      { q: "What is the route to Jūrmala?", a: "We go via Urbany/Pāternieki border crossing – Riga – Jūrmala. Total distance is about 490 km (470 km to Riga plus 25 km to Jūrmala), travel time 5.5–7 hours excluding the border stop." },
      { q: "Do I need a visa to enter Latvia?", a: "Citizens of Belarus require a Schengen visa. Please check the latest requirements with the Latvian embassy or official sources before travelling." },
      { q: "Can we stop in Riga on the way?", a: "Yes — the route passes through Riga. A stop adds very little extra time. Just let the manager know when booking." },
      { q: "Which sanatorium or hotel can you take us to?", a: "Any address in Jūrmala. Provide the exact address when booking and your driver will deliver you directly to the entrance." },
    ],
    ctaTitle: "Book Minsk–Jūrmala Transfer",
    ctaDesc: "Submit a request and our manager will contact you shortly with an exact price.",
    ctaBtn: "Request a booking",
    prefilledFrom: "Minsk",
    prefilledTo: "Jūrmala",
    backBtn: "← Latvia transfers",
  },
  seo: {
    titleRu: "Трансфер Минск — Юрмала | Балтийский курорт Латвии | ComfortLine",
    titleEn: "Minsk to Jūrmala Transfer | Latvia's Baltic Resort | ComfortLine",
    descRu: "Прямой трансфер из Минска в Юрмалу. ~490 км, 5,5–7 ч. Пляж, сосновый лес, санатории, деревянные дачи. Граница Урбаны–Патарниеки, фиксированная цена.",
    descEn: "Direct transfer from Minsk to Jūrmala. ~490 km, 5.5–7 hrs. Baltic beach, pine forest, spas, Art Nouveau dachas. Urbany–Pāternieki border, fixed price.",
    pathRu: "/трансфер-минск-юрмала",
    pathEn: "/minsk-jurmala-transfer",
    breadcrumbRu: "Трансфер Минск–Юрмала",
    breadcrumbEn: "Minsk — Jūrmala",
    fromName: "Минск",
    toName: "Юрмала",
  },
};

export default function MinskJurmalaTransferPage() {
  return <RouteLandingPage data={data} />;
}
