import { MapPin, ShieldCheck, Building2 } from "lucide-react";
import { RouteLandingPage, RoutePageData } from "./route-landing-page";

const data: RoutePageData = {
  ru: {
    badge: "Трансфер во Вроцлав",
    title: "Минск — Вроцлав",
    subtitle: "Прямой трансфер из Минска во Вроцлав — «город мостов» и гномов. Крупнейшая рыночная площадь Польши, остров Тумский и более 100 мостов через Одер.",
    stats: [
      { label: "Расстояние", value: "~850 км" },
      { label: "Время в пути", value: "9–12 ч" },
      { label: "Граница", value: "Беларусь–Польша" },
      { label: "Класс авто", value: "Бизнес / Минивэн" },
    ],
    photosTitle: "Вроцлав — достопримечательности",
    photos: [
      { src: "/img/wroclaw/market-square.png", caption: "Рыночная площадь (Rynek) — одна из крупнейших в Европе" },
      { src: "/img/wroclaw/cathedral-island.png", caption: "Остров Тумский (Ostrów Tumski) — самая старая часть города" },
      { src: "/img/wroclaw/oder-bridges.png", caption: "Мосты через Одер — Вроцлав называют «польской Венецией»" },
    ],
    howTitle: "Как проходит поездка",
    steps: [
      { icon: MapPin, title: "Выезд из Минска", desc: "Водитель заберёт вас по указанному адресу в Минске и направится к польской границе по оптимальному маршруту." },
      { icon: ShieldCheck, title: "Граница Беларусь–Польша", desc: "Переход Брузги / Кузница или Берёза / Половцы. Водитель знает актуальные очереди и помогает на КПП." },
      { icon: Building2, title: "Вроцлав: любой адрес", desc: "Довезём до отеля у Рыночной площади, аэропорта WRO или любого другого адреса в городе." },
    ],
    infoTitle: "Детали маршрута",
    infoRows: [
      { label: "Маршрут", value: "Минск → Брест → Тересполь → Варшава → Вроцлав" },
      { label: "Расстояние", value: "~850 км" },
      { label: "Пограничный переход", value: "Брузги / Кузница или Берёза / Половцы (Беларусь–Польша)" },
      { label: "Время пересечения границы", value: "1–8 ч в зависимости от сезона и очереди" },
      { label: "Необходимые документы", value: "Виза Шенген, загранпаспорт" },
      { label: "Аэропорт Вроцлава", value: "WRO (им. Николая Коперника) — 10 км от центра" },
    ],
    includedTitle: "Что включено",
    included: [
      "Подача от адреса в Минске",
      "Прямой маршрут без пересадок",
      "Помощь водителя на границе",
      "Питьевая вода и комфортный салон",
      "Детские кресла по запросу",
      "Фиксированная цена без счётчика",
    ],
    whyTitle: "Почему ComfortLine",
    whyItems: [
      "Опытные водители маршрута Минск–Польша",
      "Знание актуальных очередей на границе",
      "Возможна остановка в Варшаве или Лодзи по дороге",
      "Обратный трансфер: из Вроцлава в Минск",
      "Работаем 24/7, включая праздники",
      "Перевозим с детьми и питомцами",
    ],
    faqTitle: "Часто задаваемые вопросы",
    faq: [
      { q: "Какой маршрут до Вроцлава?", a: "Едем через Брест — КПП Брузги/Кузница или Берёза/Половцы — Варшаву — Вроцлав. Расстояние около 850 км, время в пути 9–12 ч без учёта границы." },
      { q: "Нужна ли виза в Польшу?", a: "Гражданам Беларуси требуется шенгенская виза. Уточняйте актуальные требования в посольстве Польши или на официальных сайтах перед поездкой." },
      { q: "Можно ли заехать в Варшаву по дороге?", a: "Да, возможна остановка в Варшаве. Маршрут проходит через польскую столицу, поэтому остановка почти не удлиняет поездку. Договоритесь с менеджером при бронировании." },
      { q: "Можно ли добраться до аэропорта Вроцлава WRO?", a: "Да, аэропорт Николая Коперника (WRO) находится в 10 км от центра. Укажите при бронировании — довезём прямо к терминалу." },
    ],
    ctaTitle: "Заказать трансфер Минск–Вроцлав",
    ctaDesc: "Оставьте заявку — менеджер свяжется с вами в течение 15 минут и назовёт точную стоимость.",
    ctaBtn: "Оставить заявку",
    prefilledFrom: "Минск",
    prefilledTo: "Вроцлав",
    backBtn: "← Трансферы в Польшу",
  },
  en: {
    badge: "Wrocław Transfer",
    title: "Minsk — Wrocław",
    subtitle: "Direct private transfer from Minsk to Wrocław — Poland's city of bridges and dwarfs. One of Europe's largest market squares, Cathedral Island and over 100 bridges across the Oder.",
    stats: [
      { label: "Distance", value: "~850 km" },
      { label: "Travel time", value: "9–12 hrs" },
      { label: "Border", value: "Belarus–Poland" },
      { label: "Vehicle class", value: "Business / Minivan" },
    ],
    photosTitle: "Wrocław — Highlights",
    photos: [
      { src: "/img/wroclaw/market-square.png", caption: "Rynek (Market Square) — one of the largest in Europe" },
      { src: "/img/wroclaw/cathedral-island.png", caption: "Cathedral Island (Ostrów Tumski) — the oldest part of the city" },
      { src: "/img/wroclaw/oder-bridges.png", caption: "Oder bridges — Wrocław is often called the 'Venice of Poland'" },
    ],
    howTitle: "How the transfer works",
    steps: [
      { icon: MapPin, title: "Departure from Minsk", desc: "Your driver picks you up at your Minsk address and heads for the Polish border via the fastest route." },
      { icon: ShieldCheck, title: "Belarus–Poland border", desc: "Bruzgi / Kuźnica or Berёza / Połowce crossing. Your driver knows current queue conditions and assists at the checkpoint." },
      { icon: Building2, title: "Wrocław — any address", desc: "We drop you at your hotel near the Market Square, Wrocław Airport (WRO) or any other address in the city." },
    ],
    infoTitle: "Route Details",
    infoRows: [
      { label: "Route", value: "Minsk → Brest → Terespol → Warsaw → Wrocław" },
      { label: "Distance", value: "~850 km" },
      { label: "Border crossing", value: "Bruzgi / Kuźnica or Berёza / Połowce (Belarus–Poland)" },
      { label: "Border crossing time", value: "1–8 hrs depending on season and queues" },
      { label: "Documents required", value: "Schengen visa, valid passport" },
      { label: "Wrocław Airport", value: "WRO (Nicolaus Copernicus Airport) — 10 km from the centre" },
    ],
    includedTitle: "What's included",
    included: [
      "Pickup from your Minsk address",
      "Direct route — no transfers",
      "Driver assistance at the border",
      "Bottled water and comfortable cabin",
      "Child seats on request",
      "Fixed price — no meter, no surprises",
    ],
    whyTitle: "Why ComfortLine",
    whyItems: [
      "Experienced drivers on the Minsk–Poland route",
      "Up-to-date knowledge of border queue conditions",
      "Optional Warsaw or Łódź stopover en route",
      "Return transfer Wrocław → Minsk also available",
      "Available 24/7 including public holidays",
      "Kids and pets welcome",
    ],
    faqTitle: "Frequently asked questions",
    faq: [
      { q: "What is the route to Wrocław?", a: "We go via Brest – Bruzgi/Kuźnica or Berёza/Połowce border crossing – Warsaw – Wrocław. Total distance is about 850 km, travel time 9–12 hours excluding the border stop." },
      { q: "Do I need a visa to enter Poland?", a: "Citizens of Belarus require a Schengen visa. Please check the latest requirements with the Polish embassy or official sources before travelling." },
      { q: "Can we stop in Warsaw on the way?", a: "Yes — the route passes through Warsaw, so a stop adds almost no extra distance. Let the manager know when booking." },
      { q: "Can you drop me at Wrocław Airport (WRO)?", a: "Yes — Nicolaus Copernicus Airport is 10 km from the city centre. Just mention it when booking and we'll take you straight to the terminal." },
    ],
    ctaTitle: "Book Minsk–Wrocław Transfer",
    ctaDesc: "Submit a request and our manager will contact you within 15 minutes with an exact price.",
    ctaBtn: "Request a booking",
    prefilledFrom: "Minsk",
    prefilledTo: "Wrocław",
    backBtn: "← Poland transfers",
  },
  seo: {
    titleRu: "Трансфер Минск — Вроцлав | Город мостов Польши | ComfortLine",
    titleEn: "Minsk to Wrocław Transfer | City of Bridges, Poland | ComfortLine",
    descRu: "Прямой трансфер из Минска во Вроцлав. ~850 км, 9–12 ч. Рыночная площадь, остров Тумский, 100+ мостов. Граница Беларусь–Польша, фиксированная цена.",
    descEn: "Direct transfer from Minsk to Wrocław. ~850 km, 9–12 hrs. Market Square, Cathedral Island, 100+ bridges. Belarus–Poland border crossing, fixed price.",
    pathRu: "/трансфер-минск-вроцлав",
    pathEn: "/minsk-wroclaw-transfer",
    breadcrumbRu: "Трансфер Минск–Вроцлав",
    breadcrumbEn: "Minsk — Wrocław",
    fromName: "Минск",
    toName: "Вроцлав",
  },
};

export default function MinskWroclawTransferPage() {
  return <RouteLandingPage data={data} />;
}
