import { MapPin, ShieldCheck, Building2 } from "lucide-react";
import { RouteLandingPage, RoutePageData } from "./route-landing-page";

const data: RoutePageData = {
  ru: {
    badge: "Трансфер в Лиепаю",
    title: "Минск — Лиепая",
    subtitle: "Прямой трансфер из Минска в Лиепаю — «Город ветров» на Балтийском побережье. Широкий песчаный пляж, военный квартал Карроста с имперской архитектурой и один из лучших органов Европы в Соборе Святой Троицы.",
    stats: [
      { label: "Расстояние", value: "~650 км" },
      { label: "Время в пути", value: "7–9 ч" },
      { label: "Граница", value: "Беларусь–Латвия" },
      { label: "Класс авто", value: "Бизнес / Минивэн" },
    ],
    photosTitle: "Лиепая — достопримечательности",
    photos: [
      { src: "/img/liepaja/beach.png", caption: "Лиепайский пляж — один из лучших на Балтийском побережье Латвии" },
      { src: "/img/liepaja/karosta.png", caption: "Кароста — бывший военно-морской порт с Морским собором Святого Николая" },
      { src: "/img/liepaja/old-town.png", caption: "Исторический центр Лиепаи с барочным Собором Святой Троицы" },
    ],
    howTitle: "Как проходит поездка",
    steps: [
      { icon: MapPin, title: "Выезд из Минска", desc: "Водитель заберёт вас по указанному адресу в Минске и направится к латвийской границе по оптимальному маршруту." },
      { icon: ShieldCheck, title: "Граница Беларусь–Латвия", desc: "Переход Урбаны / Патарниеки. Водитель знает актуальные очереди и помогает на КПП." },
      { icon: Building2, title: "Лиепая: любой адрес", desc: "Довезём до отеля у пляжа, исторического центра, квартала Кароста или любого другого адреса в городе." },
    ],
    infoTitle: "Детали маршрута",
    infoRows: [
      { label: "Маршрут", value: "Минск → Урбаны → Рига → Лиепая" },
      { label: "Расстояние", value: "~650 км (~470 км до Риги + ~180 км до Лиепаи)" },
      { label: "Пограничный переход", value: "Урбаны / Патарниеки (Беларусь–Латвия)" },
      { label: "Время пересечения границы", value: "1–6 ч в зависимости от очереди" },
      { label: "Необходимые документы", value: "Виза Шенген, загранпаспорт" },
      { label: "Ближайший крупный аэропорт", value: "RIX (Рига) — 180 км от Лиепаи" },
    ],
    includedTitle: "Что включено",
    included: [
      "Подача от адреса в Минске",
      "Прямой маршрут без пересадок",
      "Помощь водителя на границе",
      "Питьевая вода и комфортный салон",
      "Детские кресла по запросу",
      "Фиксированная цена без счётчика",
    ],
    whyTitle: "Почему ComfortLine",
    whyItems: [
      "Прямо до отеля или пляжа в Лиепае без пересадок",
      "Опытные водители маршрута Минск–Латвия",
      "Знание актуальных очередей на границе Урбаны",
      "Остановка в Риге или Юрмале по пути — по запросу",
      "Обратный трансфер: из Лиепаи в Минск",
      "Работаем 24/7, включая праздники",
    ],
    faqTitle: "Часто задаваемые вопросы",
    faq: [
      { q: "Какой маршрут до Лиепаи?", a: "Едем через КПП Урбаны/Патарниеки — Ригу — Лиепаю. Расстояние около 650 км (470 км до Риги плюс 180 км до Лиепаи), время в пути 7–9 ч без учёта границы." },
      { q: "Нужна ли виза в Латвию?", a: "Гражданам Беларуси требуется шенгенская виза. Уточняйте актуальные требования в посольстве Латвии или на официальных сайтах перед поездкой." },
      { q: "Что такое Кароста?", a: "Кароста — уникальный военный район Лиепаи, построенный в конце XIX века по приказу российского императора Александра III. Здесь расположен Морской собор Святого Николая в неовизантийском стиле, военные казармы и укрепления. Сейчас это историческая достопримечательность с экскурсиями." },
      { q: "Можно ли остановиться в Риге или Юрмале по дороге?", a: "Да — маршрут проходит через Ригу. При желании можно сделать остановку в Риге или заехать в Юрмалу (+25 км от трассы). Договоритесь с менеджером при бронировании." },
    ],
    ctaTitle: "Заказать трансфер Минск–Лиепая",
    ctaDesc: "Оставьте заявку — менеджер свяжется с вами в течение 15 минут и назовёт точную стоимость.",
    ctaBtn: "Оставить заявку",
    prefilledFrom: "Минск",
    prefilledTo: "Лиепая",
    backBtn: "← Трансферы в Латвию",
  },
  en: {
    badge: "Liepāja Transfer",
    title: "Minsk — Liepāja",
    subtitle: "Direct private transfer from Minsk to Liepāja — the \"City of Wind\" on the Baltic coast. A wide sandy beach, the imperial Karosta military district and one of Europe's finest organs inside St Trinity Cathedral.",
    stats: [
      { label: "Distance", value: "~650 km" },
      { label: "Travel time", value: "7–9 hrs" },
      { label: "Border", value: "Belarus–Latvia" },
      { label: "Vehicle class", value: "Business / Minivan" },
    ],
    photosTitle: "Liepāja — Highlights",
    photos: [
      { src: "/img/liepaja/beach.png", caption: "Liepāja Beach — one of the finest stretches of sand on Latvia's Baltic coast" },
      { src: "/img/liepaja/karosta.png", caption: "Karosta — the former Imperial naval port with the St Nicholas Naval Cathedral" },
      { src: "/img/liepaja/old-town.png", caption: "Liepāja's historic centre with the Baroque St Trinity Cathedral" },
    ],
    howTitle: "How the transfer works",
    steps: [
      { icon: MapPin, title: "Departure from Minsk", desc: "Your driver picks you up at your Minsk address and heads for the Latvian border via the fastest route." },
      { icon: ShieldCheck, title: "Belarus–Latvia border", desc: "Urbany / Pāternieki crossing. Your driver knows current queue conditions and assists at the checkpoint." },
      { icon: Building2, title: "Liepāja — any address", desc: "We drop you at your beachside hotel, the historic centre, Karosta or any other address in the city." },
    ],
    infoTitle: "Route Details",
    infoRows: [
      { label: "Route", value: "Minsk → Urbany → Riga → Liepāja" },
      { label: "Distance", value: "~650 km (~470 km to Riga + ~180 km to Liepāja)" },
      { label: "Border crossing", value: "Urbany / Pāternieki (Belarus–Latvia)" },
      { label: "Border crossing time", value: "1–6 hrs depending on queues" },
      { label: "Documents required", value: "Schengen visa, valid passport" },
      { label: "Nearest major airport", value: "RIX (Riga) — 180 km from Liepāja" },
    ],
    includedTitle: "What's included",
    included: [
      "Pickup from your Minsk address",
      "Direct route — no transfers",
      "Driver assistance at the border",
      "Bottled water and comfortable cabin",
      "Child seats on request",
      "Fixed price — no meter, no surprises",
    ],
    whyTitle: "Why ComfortLine",
    whyItems: [
      "Door-to-door delivery to your hotel or the beach in Liepāja",
      "Experienced drivers on the Minsk–Latvia corridor",
      "Up-to-date knowledge of Urbany border queues",
      "Optional Riga or Jūrmala stop en route — on request",
      "Return transfer Liepāja → Minsk also available",
      "Available 24/7 including public holidays",
    ],
    faqTitle: "Frequently asked questions",
    faq: [
      { q: "What is the route to Liepāja?", a: "We go via Urbany/Pāternieki border crossing – Riga – Liepāja. Total distance is about 650 km (470 km to Riga plus 180 km to Liepāja), travel time 7–9 hours excluding the border stop." },
      { q: "Do I need a visa to enter Latvia?", a: "Citizens of Belarus require a Schengen visa. Please check the latest requirements with the Latvian embassy or official sources before travelling." },
      { q: "What is Karosta?", a: "Karosta is a unique military district built on the orders of Tsar Alexander III in the late 19th century. Its centrepiece is the ornate Neo-Byzantine St Nicholas Naval Cathedral. Today it is a fascinating heritage site offering guided tours of the barracks and fortifications." },
      { q: "Can we stop in Riga or Jūrmala on the way?", a: "Yes — the route passes through Riga. You can also add a Jūrmala detour (+25 km off the main route). Just let the manager know when booking." },
    ],
    ctaTitle: "Book Minsk–Liepāja Transfer",
    ctaDesc: "Submit a request and our manager will contact you within 15 minutes with an exact price.",
    ctaBtn: "Request a booking",
    prefilledFrom: "Minsk",
    prefilledTo: "Liepāja",
    backBtn: "← Latvia transfers",
  },
  seo: {
    titleRu: "Трансфер Минск — Лиепая | Город ветров Латвии | ComfortLine",
    titleEn: "Minsk to Liepāja Transfer | Latvia's City of Wind | ComfortLine",
    descRu: "Прямой трансфер из Минска в Лиепаю. ~650 км, 7–9 ч. Пляж, Кароста, орган Святой Троицы. Граница Урбаны–Патарниеки, фиксированная цена.",
    descEn: "Direct transfer from Minsk to Liepāja. ~650 km, 7–9 hrs. Baltic beach, Karosta, St Trinity organ. Urbany–Pāternieki border, fixed price.",
    pathRu: "/трансфер-минск-лиепая",
    pathEn: "/minsk-liepaja-transfer",
    breadcrumbRu: "Трансфер Минск–Лиепая",
    breadcrumbEn: "Minsk — Liepāja",
    fromName: "Минск",
    toName: "Лиепая",
  },
};

export default function MinskLiepajaTransferPage() {
  return <RouteLandingPage data={data} />;
}
