import { MapPin, ShieldCheck, Landmark } from "lucide-react";
import { RouteLandingPage, RoutePageData } from "./route-landing-page";

const data: RoutePageData = {
  ru: {
    badge: "Трансфер в Вильнюс",
    title: "Минск — Вильнюс",
    subtitle: "Прямой трансфер из Минска в столицу Литвы. Один из крупнейших средневековых старых городов Европы, внесённый в список ЮНЕСКО.",
    stats: [
      { label: "Расстояние", value: "~170 км" },
      { label: "Время в пути", value: "2–4 ч" },
      { label: "Граница", value: "Беларусь–Литва" },
      { label: "Класс авто", value: "Бизнес / Минивэн" },
    ],
    photosTitle: "Вильнюс — достопримечательности",
    photos: [
      { src: "/img/vilnius/old-town-aerial.png", caption: "Старый город Вильнюса — объект ЮНЕСКО" },
      { src: "/img/vilnius/cathedral-square.png", caption: "Кафедральная площадь — сердце литовской столицы" },
      { src: "/img/vilnius/gate-of-dawn.png", caption: "Ворота Зари (Аушрос Вартай) — главная святыня города" },
    ],
    howTitle: "Как проходит поездка",
    steps: [
      { icon: MapPin, title: "Выезд из Минска", desc: "Водитель заберёт вас в указанном месте в Минске и выдвинется к литовской границе по оптимальному маршруту." },
      { icon: ShieldCheck, title: "Граница Беларусь–Литва", desc: "Переход Медининкай / Шальчининкай. Водитель знает актуальные очереди и помогает на КПП." },
      { icon: Landmark, title: "Вильнюс: столица и старый город", desc: "Довезём до отеля, аэропорта, офиса или любого адреса в Вильнюсе. Возможна дальнейшая поездка в Тракай." },
    ],
    infoTitle: "Детали маршрута",
    infoRows: [
      { label: "Маршрут", value: "Минск → Молодечно → Медининкай → Вильнюс" },
      { label: "Расстояние", value: "~170 км" },
      { label: "Пограничный переход", value: "Медининкай / Шальчининкай (Беларусь–Литва)" },
      { label: "Время пересечения границы", value: "30 мин – 4 ч в зависимости от очереди" },
      { label: "Необходимые документы", value: "Виза Шенген (для граждан не ЕС), загранпаспорт" },
      { label: "Аэропорт Вильнюса", value: "VNO — 10 км от центра города (15 мин)" },
    ],
    includedTitle: "Что включено",
    included: [
      "Подача от адреса в Минске",
      "Прямой маршрут без пересадок",
      "Помощь водителя на границе",
      "Питьевая вода и комфортный салон",
      "Детские кресла по запросу",
      "Фиксированная цена без счётчика",
    ],
    whyTitle: "Почему ComfortLine",
    whyItems: [
      "Опытные водители маршрута Минск–Вильнюс",
      "Знание актуальных очередей на границе",
      "Возможна поездка в Тракай по дороге или после",
      "Обратный трансфер: из Вильнюса в Минск",
      "Работаем 24/7, включая праздники",
      "Перевозим с детьми и питомцами",
    ],
    faqTitle: "Часто задаваемые вопросы",
    faq: [
      { q: "Какой маршрут до Вильнюса?", a: "Едем через Молодечно — Ошмяны — КПП Медининкай/Шальчининкай — Вильнюс. Расстояние около 170 км, время в пути 2–4 ч без учёта границы." },
      { q: "Нужна ли виза в Литву?", a: "Гражданам Беларуси требуется шенгенская виза или национальная виза Литовской Республики. Уточняйте актуальные требования в посольстве или на официальных сайтах." },
      { q: "Можно ли заехать в Тракай по дороге?", a: "Да — Тракай находится в 28 км от Вильнюса. Мы можем сделать остановку или завезти вас сначала в Тракай, а затем в Вильнюс. Договоритесь с менеджером при бронировании." },
      { q: "Чем отличается этот трансфер от трансфера в аэропорт Вильнюса?", a: "Мы довезём вас до любого адреса в центре Вильнюса, а не только до аэропорта. Если вам нужен именно аэропорт — воспользуйтесь нашим трансфером Минск–аэропорт Вильнюса (VNO)." },
    ],
    ctaTitle: "Заказать трансфер Минск–Вильнюс",
    ctaDesc: "Оставьте заявку — менеджер свяжется с вами в течение 15 минут и назовёт точную стоимость.",
    ctaBtn: "Оставить заявку",
    prefilledFrom: "Минск",
    prefilledTo: "Вильнюс",
    backBtn: "← Трансферы в Литву",
  },
  en: {
    badge: "Vilnius Transfer",
    title: "Minsk — Vilnius",
    subtitle: "Direct private transfer from Minsk to the capital of Lithuania — home to one of Europe's largest and best-preserved medieval old towns, a UNESCO World Heritage Site.",
    stats: [
      { label: "Distance", value: "~170 km" },
      { label: "Travel time", value: "2–4 hrs" },
      { label: "Border", value: "Belarus–Lithuania" },
      { label: "Vehicle class", value: "Business / Minivan" },
    ],
    photosTitle: "Vilnius — Highlights",
    photos: [
      { src: "/img/vilnius/old-town-aerial.png", caption: "Vilnius Old Town — UNESCO World Heritage Site" },
      { src: "/img/vilnius/cathedral-square.png", caption: "Cathedral Square — the heart of the Lithuanian capital" },
      { src: "/img/vilnius/gate-of-dawn.png", caption: "Gate of Dawn (Aušros Vartai) — the city's most sacred landmark" },
    ],
    howTitle: "How the transfer works",
    steps: [
      { icon: MapPin, title: "Departure from Minsk", desc: "Your driver picks you up at your Minsk address and heads for the Lithuanian border via the fastest route." },
      { icon: ShieldCheck, title: "Belarus–Lithuania border", desc: "Medininkai / Šalčininkai crossing. Your driver knows current queue conditions and assists at the checkpoint." },
      { icon: Landmark, title: "Vilnius — capital & old town", desc: "We drop you at your hotel, office, Vilnius Airport or any address. A Trakai side trip on the way is also easy to arrange." },
    ],
    infoTitle: "Route Details",
    infoRows: [
      { label: "Route", value: "Minsk → Maladzyechna → Medininkai → Vilnius" },
      { label: "Distance", value: "~170 km" },
      { label: "Border crossing", value: "Medininkai / Šalčininkai (Belarus–Lithuania)" },
      { label: "Border crossing time", value: "30 min – 4 hrs depending on queues" },
      { label: "Documents required", value: "Schengen visa (non-EU citizens), valid passport" },
      { label: "Vilnius Airport", value: "VNO — 10 km from the city centre (15 min)" },
    ],
    includedTitle: "What's included",
    included: [
      "Pickup from your Minsk address",
      "Direct route — no transfers",
      "Driver assistance at the border",
      "Bottled water and comfortable cabin",
      "Child seats on request",
      "Fixed price — no meter, no surprises",
    ],
    whyTitle: "Why ComfortLine",
    whyItems: [
      "Experienced drivers on the Minsk–Vilnius route",
      "Up-to-date knowledge of border queue conditions",
      "Optional Trakai stopover — 28 km from Vilnius",
      "Return transfer Vilnius → Minsk also available",
      "Available 24/7 including public holidays",
      "Kids and pets welcome",
    ],
    faqTitle: "Frequently asked questions",
    faq: [
      { q: "What is the route to Vilnius?", a: "We go via Maladzyechna – Ashmyany – Medininkai/Šalčininkai border crossing – Vilnius. Total distance is about 170 km, travel time 2–4 hours excluding the border stop." },
      { q: "Do I need a visa to enter Lithuania?", a: "Citizens of Belarus require a Schengen visa or a Lithuanian national visa. Please check the latest requirements with the embassy or official sources before travelling." },
      { q: "Can we stop at Trakai on the way?", a: "Yes — Trakai is just 28 km from Vilnius. We can stop there first or arrange it as a side trip. Let the manager know when booking." },
      { q: "How is this different from the Vilnius Airport transfer?", a: "This transfer takes you to any address in Vilnius city centre, not just the airport. If you specifically need the airport, see our Minsk to Vilnius Airport (VNO) transfer instead." },
    ],
    ctaTitle: "Book Minsk–Vilnius Transfer",
    ctaDesc: "Submit a request and our manager will contact you within 15 minutes with an exact price.",
    ctaBtn: "Request a booking",
    prefilledFrom: "Minsk",
    prefilledTo: "Vilnius",
    backBtn: "← Lithuania transfers",
  },
  seo: {
    titleRu: "Трансфер Минск — Вильнюс | Столица Литвы | ComfortLine",
    titleEn: "Minsk to Vilnius Transfer | Lithuania Capital | ComfortLine",
    descRu: "Прямой трансфер из Минска в Вильнюс. ~170 км, 2–4 ч. Старый город ЮНЕСКО, Кафедральная площадь, Ворота Зари. Фиксированная цена, граница Беларусь–Литва.",
    descEn: "Direct transfer from Minsk to Vilnius. ~170 km, 2–4 hrs. UNESCO Old Town, Cathedral Square, Gate of Dawn. Fixed price, Belarus–Lithuania border crossing.",
    pathRu: "/трансфер-минск-вильнюс",
    pathEn: "/minsk-vilnius-transfer",
    breadcrumbRu: "Трансфер Минск–Вильнюс",
    breadcrumbEn: "Minsk — Vilnius",
    fromName: "Минск",
    toName: "Вильнюс",
  },
};

export default function MinskVilniusTransferPage() {
  return <RouteLandingPage data={data} />;
}
