import { MapPin, ShieldCheck, Heart } from "lucide-react";
import { RouteLandingPage, RoutePageData } from "./route-landing-page";

const data: RoutePageData = {
  ru: {
    badge: "Трансфер в Друскининкай",
    title: "Минск — Друскининкай",
    subtitle: "Прямой трансфер из Минска в Друскининкай — главный курортный и спа-город Литвы. Минеральные воды, аквапарк, горнолыжная трасса и парк скульптур Грутас.",
    stats: [
      { label: "Расстояние", value: "~220 км" },
      { label: "Время в пути", value: "3–5 ч" },
      { label: "Граница", value: "Беларусь–Литва" },
      { label: "Класс авто", value: "Бизнес / Минивэн" },
    ],
    photosTitle: "Друскининкай — достопримечательности",
    photos: [
      { src: "/img/druskininkai/resort.png", caption: "Курортный центр Друскининкай" },
      { src: "/img/druskininkai/aqua-park.png", caption: "Аквапарк — крупнейший в странах Балтии" },
      { src: "/img/druskininkai/grutas-park.png", caption: "Парк Грутас — музей советской скульптуры" },
    ],
    howTitle: "Как проходит поездка",
    steps: [
      { icon: MapPin, title: "Выезд из Минска", desc: "Водитель заберёт вас в указанном месте в Минске и выдвинется к литовской границе по оптимальному маршруту." },
      { icon: ShieldCheck, title: "Граница Беларусь–Литва", desc: "Переход Медининкай / Шальчининкай или Котловка (возможны варианты). Водитель знает актуальные очереди." },
      { icon: Heart, title: "Друскининкай: курорт и СПА", desc: "Довезём до санатория, отеля, аквапарка или любого адреса в Друскининкай." },
    ],
    infoTitle: "Детали маршрута",
    infoRows: [
      { label: "Маршрут", value: "Минск → Гродно → Котловка / Медининкай → Друскининкай" },
      { label: "Расстояние", value: "~220 км" },
      { label: "Пограничный переход", value: "Котловка / Медининкай (Беларусь–Литва)" },
      { label: "Время пересечения границы", value: "30 мин – 3 ч в зависимости от очереди" },
      { label: "Необходимые документы", value: "Виза Шенген (для граждан не ЕС), загранпаспорт" },
      { label: "Курорт", value: "Минеральные воды, спа, горнолыжная трасса Snow Arena" },
    ],
    includedTitle: "Что включено",
    included: [
      "Подача от адреса в Минске",
      "Прямой маршрут без пересадок",
      "Помощь водителя на границе",
      "Питьевая вода и комфортный салон",
      "Детские кресла по запросу",
      "Фиксированная цена без счётчика",
    ],
    whyTitle: "Почему ComfortLine",
    whyItems: [
      "Опытные водители маршрута Минск–Литва",
      "Знание актуальных очередей на границе",
      "Удобно для семей и групп на отдых",
      "Обратный трансфер: из Друскининкай в Минск",
      "Работаем 24/7, включая праздники",
      "Перевозим с детьми и питомцами",
    ],
    faqTitle: "Часто задаваемые вопросы",
    faq: [
      { q: "Какой маршрут до Друскининкай?", a: "Чаще всего едем через Гродно и КПП Котловка или через Медининкай. Расстояние около 220 км, время в пути 3–5 ч без учёта границы." },
      { q: "Нужна ли виза в Литву?", a: "Гражданам Беларуси требуется шенгенская виза или национальная виза Литовской Республики. Уточняйте актуальные требования в посольстве или на официальных сайтах." },
      { q: "Можно ли доехать до санатория с вещами?", a: "Да, минивэн вмещает до 8 пассажиров с багажом. Если у вас много вещей — сообщите при бронировании." },
      { q: "Можно ли заехать в Гродно по дороге?", a: "Да, возможна остановка в Гродно. Договоритесь с менеджером при бронировании, доплата по согласованию." },
    ],
    ctaTitle: "Заказать трансфер Минск–Друскининкай",
    ctaDesc: "Оставьте заявку — менеджер свяжется с вами в ближайшее время и назовёт точную стоимость.",
    ctaBtn: "Оставить заявку",
    prefilledFrom: "Минск",
    prefilledTo: "Друскининкай",
    backBtn: "← Трансферы в Литву",
  },
  en: {
    badge: "Druskininkai Transfer",
    title: "Minsk — Druskininkai",
    subtitle: "Direct private transfer from Minsk to Druskininkai — Lithuania's premier spa and health resort. Mineral springs, the Baltic's largest aqua park, a ski slope and the unique Grūtas Park.",
    stats: [
      { label: "Distance", value: "~220 km" },
      { label: "Travel time", value: "3–5 hrs" },
      { label: "Border", value: "Belarus–Lithuania" },
      { label: "Vehicle class", value: "Business / Minivan" },
    ],
    photosTitle: "Druskininkai — Highlights",
    photos: [
      { src: "/img/druskininkai/resort.png", caption: "Druskininkai resort centre" },
      { src: "/img/druskininkai/aqua-park.png", caption: "Aqua Park — largest in the Baltics" },
      { src: "/img/druskininkai/grutas-park.png", caption: "Grūtas Park — Soviet sculpture museum" },
    ],
    howTitle: "How the transfer works",
    steps: [
      { icon: MapPin, title: "Departure from Minsk", desc: "Your driver picks you up at your Minsk address and heads for the Lithuanian border via the fastest route." },
      { icon: ShieldCheck, title: "Belarus–Lithuania border", desc: "Kotlovka / Medininkai crossing. Your driver knows current queue conditions and assists at the checkpoint." },
      { icon: Heart, title: "Druskininkai — spa & resort", desc: "We drop you at your sanatorium, hotel, the aqua park or any address in Druskininkai." },
    ],
    infoTitle: "Route Details",
    infoRows: [
      { label: "Route", value: "Minsk → Grodno → Kotlovka / Medininkai → Druskininkai" },
      { label: "Distance", value: "~220 km" },
      { label: "Border crossing", value: "Kotlovka / Medininkai (Belarus–Lithuania)" },
      { label: "Border crossing time", value: "30 min – 3 hrs depending on queues" },
      { label: "Documents required", value: "Schengen visa (non-EU citizens), valid passport" },
      { label: "Resort highlights", value: "Mineral springs, spa, Snow Arena ski slope" },
    ],
    includedTitle: "What's included",
    included: [
      "Pickup from your Minsk address",
      "Direct route — no transfers",
      "Driver assistance at the border",
      "Bottled water and comfortable cabin",
      "Child seats on request",
      "Fixed price — no meter, no surprises",
    ],
    whyTitle: "Why ComfortLine",
    whyItems: [
      "Experienced drivers on the Minsk–Lithuania route",
      "Up-to-date knowledge of border queue conditions",
      "Great for families and leisure groups",
      "Return transfer Druskininkai → Minsk also available",
      "Available 24/7 including public holidays",
      "Kids and pets welcome",
    ],
    faqTitle: "Frequently asked questions",
    faq: [
      { q: "What is the route to Druskininkai?", a: "We typically go via Grodno and the Kotlovka crossing, or via Medininkai. Total distance is about 220 km, travel time 3–5 hours excluding the border stop." },
      { q: "Do I need a visa to enter Lithuania?", a: "Citizens of Belarus require a Schengen visa or a Lithuanian national visa. Please check the latest requirements with the embassy or official sources before travelling." },
      { q: "Can you fit all my luggage for a health resort stay?", a: "Yes — our minivan seats up to 8 passengers with luggage. If you have particularly heavy bags, let us know when booking." },
      { q: "Can we stop in Grodno on the way?", a: "Yes — we can make a stop in Grodno. Just let the manager know when booking; an additional charge may apply." },
    ],
    ctaTitle: "Book Minsk–Druskininkai Transfer",
    ctaDesc: "Submit a request and our manager will contact you shortly with an exact price.",
    ctaBtn: "Request a booking",
    prefilledFrom: "Minsk",
    prefilledTo: "Druskininkai",
    backBtn: "← Lithuania transfers",
  },
  seo: {
    titleRu: "Трансфер Минск — Друскининкай | СПА-курорт Литвы | ComfortLine",
    titleEn: "Minsk to Druskininkai Transfer | Lithuania Spa Resort | ComfortLine",
    descRu: "Прямой трансфер из Минска в Друскининкай. ~220 км, 3–5 ч. Минеральные воды, аквапарк, Snow Arena. Фиксированная цена, граница Беларусь–Литва.",
    descEn: "Direct transfer from Minsk to Druskininkai. ~220 km, 3–5 hrs. Mineral springs, aqua park, Snow Arena ski slope. Fixed price, Belarus–Lithuania border crossing.",
    pathRu: "/трансфер-минск-друскининкай",
    pathEn: "/minsk-druskininkai-transfer",
    breadcrumbRu: "Трансфер Минск–Друскининкай",
    breadcrumbEn: "Minsk — Druskininkai",
    fromName: "Минск",
    toName: "Друскининкай",
  },
};

export default function MinskDruskininkaiTransferPage() {
  return <RouteLandingPage data={data} />;
}
