import { MapPin, ShieldCheck, Building2 } from "lucide-react";
import { RouteLandingPage, RoutePageData } from "./route-landing-page";

const data: RoutePageData = {
  ru: {
    badge: "Трансфер в Вентспилс",
    title: "Минск — Вентспилс",
    subtitle: "Прямой трансфер из Минска в Вентспилс — один из чистейших портовых городов Балтии. Пляж с голубым флагом, рыцарский замок Ливонского ордена и знаменитые синие коровы на каждом углу.",
    stats: [
      { label: "Расстояние", value: "~620 км" },
      { label: "Время в пути", value: "7–9 ч" },
      { label: "Граница", value: "Беларусь–Латвия" },
      { label: "Класс авто", value: "Бизнес / Минивэн" },
    ],
    photosTitle: "Вентспилс — достопримечательности",
    photos: [
      { src: "/img/ventspils/beach.png", caption: "Пляж Вентспилса — Голубой флаг и один из чистейших в Латвии" },
      { src: "/img/ventspils/castle.png", caption: "Замок Ливонского ордена — один из лучших сохранившихся средневековых замков Латвии" },
      { src: "/img/ventspils/waterfront.png", caption: "Набережная реки Венты — колоритный портовый центр города" },
    ],
    howTitle: "Как проходит поездка",
    steps: [
      { icon: MapPin, title: "Выезд из Минска", desc: "Водитель заберёт вас по указанному адресу в Минске и направится к латвийской границе по оптимальному маршруту." },
      { icon: ShieldCheck, title: "Граница Беларусь–Латвия", desc: "Переход Урбаны / Патарниеки. Водитель знает актуальные очереди и помогает на КПП." },
      { icon: Building2, title: "Вентспилс: любой адрес", desc: "Довезём до отеля у пляжа, замка, набережной или любого другого адреса в городе." },
    ],
    infoTitle: "Детали маршрута",
    infoRows: [
      { label: "Маршрут", value: "Минск → Урбаны → Рига → Вентспилс" },
      { label: "Расстояние", value: "~620 км (~470 км до Риги + ~185 км до Вентспилса)" },
      { label: "Пограничный переход", value: "Урбаны / Патарниеки (Беларусь–Латвия)" },
      { label: "Время пересечения границы", value: "1–6 ч в зависимости от очереди" },
      { label: "Необходимые документы", value: "Виза Шенген, загранпаспорт" },
      { label: "Ближайший крупный аэропорт", value: "RIX (Рига) — 185 км от Вентспилса" },
    ],
    includedTitle: "Что включено",
    included: [
      "Подача от адреса в Минске",
      "Прямой маршрут без пересадок",
      "Помощь водителя на границе",
      "Питьевая вода и комфортный салон",
      "Детские кресла по запросу",
      "Фиксированная цена без счётчика",
    ],
    whyTitle: "Почему ComfortLine",
    whyItems: [
      "Прямо до пляжа или замка в Вентспилсе без пересадок",
      "Опытные водители маршрута Минск–Латвия",
      "Знание актуальных очередей на границе Урбаны",
      "Остановка в Риге или Юрмале по пути — по запросу",
      "Обратный трансфер: из Вентспилса в Минск",
      "Работаем 24/7, включая праздники",
    ],
    faqTitle: "Часто задаваемые вопросы",
    faq: [
      { q: "Какой маршрут до Вентспилса?", a: "Едем через КПП Урбаны/Патарниеки — Ригу — Вентспилс. Расстояние около 620 км (470 км до Риги плюс 185 км до Вентспилса), время в пути 7–9 ч без учёта границы." },
      { q: "Нужна ли виза в Латвию?", a: "Гражданам Беларуси требуется шенгенская виза. Уточняйте актуальные требования в посольстве Латвии или на официальных сайтах перед поездкой." },
      { q: "Что такое «синие коровы» Вентспилса?", a: "Вентспилс знаменит арт-проектом «Коровы на пляже»: по всему городу расставлены скульптуры коров, расписанных местными художниками. Это стало визитной карточкой города и любимым символом туристов." },
      { q: "Можно ли остановиться в Риге или Юрмале по дороге?", a: "Да — маршрут проходит через Ригу. При желании можно заехать в Юрмалу (+25 км от трассы). Договоритесь с менеджером при бронировании." },
    ],
    ctaTitle: "Заказать трансфер Минск–Вентспилс",
    ctaDesc: "Оставьте заявку — менеджер свяжется с вами в ближайшее время и назовёт точную стоимость.",
    ctaBtn: "Оставить заявку",
    prefilledFrom: "Минск",
    prefilledTo: "Вентспилс",
    backBtn: "← Трансферы в Латвию",
  },
  en: {
    badge: "Ventspils Transfer",
    title: "Minsk — Ventspils",
    subtitle: "Direct private transfer from Minsk to Ventspils — one of the cleanest port cities on the Baltic. A Blue Flag beach, a well-preserved Livonian Order castle and the famous blue cow sculptures scattered across the city.",
    stats: [
      { label: "Distance", value: "~620 km" },
      { label: "Travel time", value: "7–9 hrs" },
      { label: "Border", value: "Belarus–Latvia" },
      { label: "Vehicle class", value: "Business / Minivan" },
    ],
    photosTitle: "Ventspils — Highlights",
    photos: [
      { src: "/img/ventspils/beach.png", caption: "Ventspils Beach — Blue Flag awarded and one of the cleanest in Latvia" },
      { src: "/img/ventspils/castle.png", caption: "Livonian Order Castle — one of the best-preserved medieval castles in Latvia" },
      { src: "/img/ventspils/waterfront.png", caption: "Venta riverside waterfront — the colourful heart of this Baltic port city" },
    ],
    howTitle: "How the transfer works",
    steps: [
      { icon: MapPin, title: "Departure from Minsk", desc: "Your driver picks you up at your Minsk address and heads for the Latvian border via the fastest route." },
      { icon: ShieldCheck, title: "Belarus–Latvia border", desc: "Urbany / Pāternieki crossing. Your driver knows current queue conditions and assists at the checkpoint." },
      { icon: Building2, title: "Ventspils — any address", desc: "We drop you at your beachside hotel, the castle, the waterfront or any other address in the city." },
    ],
    infoTitle: "Route Details",
    infoRows: [
      { label: "Route", value: "Minsk → Urbany → Riga → Ventspils" },
      { label: "Distance", value: "~620 km (~470 km to Riga + ~185 km to Ventspils)" },
      { label: "Border crossing", value: "Urbany / Pāternieki (Belarus–Latvia)" },
      { label: "Border crossing time", value: "1–6 hrs depending on queues" },
      { label: "Documents required", value: "Schengen visa, valid passport" },
      { label: "Nearest major airport", value: "RIX (Riga) — 185 km from Ventspils" },
    ],
    includedTitle: "What's included",
    included: [
      "Pickup from your Minsk address",
      "Direct route — no transfers",
      "Driver assistance at the border",
      "Bottled water and comfortable cabin",
      "Child seats on request",
      "Fixed price — no meter, no surprises",
    ],
    whyTitle: "Why ComfortLine",
    whyItems: [
      "Door-to-door delivery to your hotel or the beach in Ventspils",
      "Experienced drivers on the Minsk–Latvia corridor",
      "Up-to-date knowledge of Urbany border queues",
      "Optional Riga or Jūrmala stop en route — on request",
      "Return transfer Ventspils → Minsk also available",
      "Available 24/7 including public holidays",
    ],
    faqTitle: "Frequently asked questions",
    faq: [
      { q: "What is the route to Ventspils?", a: "We go via Urbany/Pāternieki border crossing – Riga – Ventspils. Total distance is about 620 km (470 km to Riga plus 185 km to Ventspils), travel time 7–9 hours excluding the border stop." },
      { q: "Do I need a visa to enter Latvia?", a: "Citizens of Belarus require a Schengen visa. Please check the latest requirements with the Latvian embassy or official sources before travelling." },
      { q: "What are the famous blue cows of Ventspils?", a: "Ventspils is famous for its 'Cows on the Beach' art project — colourfully painted cow sculptures placed around the city by local artists. They have become the city's beloved symbol and a favourite photo stop for visitors." },
      { q: "Can we stop in Riga or Jūrmala on the way?", a: "Yes — the route passes through Riga. You can also add a Jūrmala detour (+25 km off the main route). Just let the manager know when booking." },
    ],
    ctaTitle: "Book Minsk–Ventspils Transfer",
    ctaDesc: "Submit a request and our manager will contact you shortly with an exact price.",
    ctaBtn: "Request a booking",
    prefilledFrom: "Minsk",
    prefilledTo: "Ventspils",
    backBtn: "← Latvia transfers",
  },
  seo: {
    titleRu: "Трансфер Минск — Вентспилс | Латвия | ComfortLine",
    titleEn: "Minsk to Ventspils Transfer | Latvia | ComfortLine",
    descRu: "Прямой трансфер из Минска в Вентспилс. ~620 км, 7–9 ч. Пляж Голубой флаг, замок Ливонского ордена, синие коровы. Граница Урбаны–Патарниеки, фиксированная цена.",
    descEn: "Direct transfer from Minsk to Ventspils. ~620 km, 7–9 hrs. Blue Flag beach, Livonian Order castle, blue cow sculptures. Urbany–Pāternieki border, fixed price.",
    pathRu: "/трансфер-минск-вентспилс",
    pathEn: "/minsk-ventspils-transfer",
    breadcrumbRu: "Трансфер Минск–Вентспилс",
    breadcrumbEn: "Minsk — Ventspils",
    fromName: "Минск",
    toName: "Вентспилс",
  },
};

export default function MinskVentspilsTransferPage() {
  return <RouteLandingPage data={data} />;
}
