import { CountryTransferPage, CountryPageData } from "./country-transfer-page";

const data: CountryPageData = {
  ru: {
    badge: "Трансферы в Польшу",
    title: "Минск — Польша",
    subtitle: "Варшава и её аэропорты — самое популярное европейское направление из Минска. Трансфер к аэропортам Шопен (WAW) и Модлин, а также в центр города.",
    destinationsTitle: "Направления в Польше",
    destinations: [
      {
        cityRu: "Аэропорт Варшавы Шопен (WAW)",
        cityEn: "Warsaw Chopin Airport (WAW)",
        descRu: "Главный аэропорт Польши. Рейсы LOT, Ryanair, Wizz Air и десятков других авиакомпаний.",
        descEn: "Poland's main airport. LOT, Ryanair, Wizz Air and dozens of other airlines.",
        distanceKm: "~600 км",
        travelTime: "6–9 ч",
        href: "/minsk-warsaw-airport",
        hrefRu: "/трансфер-минск-варшава-шопен",
        isAvailable: true,
      },
      {
        cityRu: "Аэропорт Варшавы Модлин",
        cityEn: "Warsaw Modlin Airport",
        descRu: "Бюджетный аэропорт в 40 км к северу от Варшавы. Рейсы Ryanair в города Европы.",
        descEn: "Budget airport 40 km north of Warsaw. Ryanair flights across Europe.",
        distanceKm: "~620 км",
        travelTime: "6.5–9 ч",
        href: "/minsk-warsaw-modlin-airport",
        hrefRu: "/трансфер-минск-варшава-модлин",
        isAvailable: true,
      },
      {
        cityRu: "Варшава — центр города",
        cityEn: "Warsaw — city centre",
        descRu: "Деловые поездки, шопинг, туризм. Доставка до отеля, офиса или торгового центра.",
        descEn: "Business trips, shopping, tourism. Delivery to your hotel, office or shopping centre.",
        distanceKm: "~600 км",
        travelTime: "6–9 ч",
        href: "/warsaw-transfer",
        hrefRu: "/трансфер-варшава",
        isAvailable: true,
      },
      {
        cityRu: "Гданьск",
        cityEn: "Gdańsk",
        descRu: "Жемчужина Балтийского побережья. Длинный рынок, кран Журав, базилика Святой Марии, мировая столица янтаря.",
        descEn: "Jewel of the Baltic coast. Long Market, Żuraw crane, St Mary's Basilica, world amber capital.",
        distanceKm: "~750 км",
        travelTime: "8–11 ч",
        href: "/minsk-gdansk-transfer",
        hrefRu: "/трансфер-минск-гданьск",
        isAvailable: true,
      },
      {
        cityRu: "Вроцлав",
        cityEn: "Wrocław",
        descRu: "Город мостов и гномов. Рыночная площадь Rynek, остров Тумский, более 100 мостов через Одер.",
        descEn: "City of bridges and dwarfs. Rynek Market Square, Cathedral Island, 100+ bridges over the Oder.",
        distanceKm: "~850 км",
        travelTime: "9–12 ч",
        href: "/minsk-wroclaw-transfer",
        hrefRu: "/трансфер-минск-вроцлав",
        isAvailable: true,
      },
      {
        cityRu: "Краков",
        cityEn: "Kraków",
        descRu: "Королевская столица Польши. Вавельский замок, Главная площадь, Казимеж, Величкская соляная шахта.",
        descEn: "Poland's royal capital. Wawel Castle, Main Market Square, Kazimierz, Wieliczka Salt Mine.",
        distanceKm: "~750 км",
        travelTime: "8–11 ч",
        href: "/minsk-krakow-transfer",
        hrefRu: "/трансфер-минск-краков",
        isAvailable: true,
      },
    ],
    infoTitle: "Полезная информация",
    infoRows: [
      { label: "Пограничный переход", value: "Брузги / Кузница или Берёза / Половцы (Беларусь–Польша)" },
      { label: "Время на границе", value: "1–8 ч в зависимости от сезона и очереди" },
      { label: "Необходимые документы", value: "Шенгенская виза, загранпаспорт" },
      { label: "Валюта", value: "Польский злотый (PLN)" },
      { label: "Языки", value: "Польский (официальный), английский в городах и туристических местах" },
    ],
    includedTitle: "Что включено в любой трансфер",
    included: [
      "Подача от адреса в Минске",
      "Прямой маршрут без пересадок",
      "Помощь водителя на границе",
      "Питьевая вода и комфортный салон",
      "Детские кресла по запросу",
      "Фиксированная цена без счётчика",
    ],
    ctaTitle: "Заказать трансфер в Польшу",
    ctaDesc: "Оставьте заявку с маршрутом и количеством пассажиров — назовём точную цену за 15 минут.",
    ctaBtn: "Оставить заявку",
    backBtn: "← Трансферы в Европу",
    soonLabel: "Скоро",
    bookLabel: "Запросить цену",
    detailsLabel: "Подробнее",
  },
  en: {
    badge: "Poland Transfers",
    title: "Minsk — Poland",
    subtitle: "Warsaw and its airports — the most popular European destination from Minsk. Transfers to Chopin (WAW), Modlin, and Warsaw city centre.",
    destinationsTitle: "Destinations in Poland",
    destinations: [
      {
        cityRu: "Аэропорт Варшавы Шопен (WAW)",
        cityEn: "Warsaw Chopin Airport (WAW)",
        descRu: "Главный аэропорт Польши. Рейсы LOT, Ryanair, Wizz Air и десятков других авиакомпаний.",
        descEn: "Poland's main airport. LOT, Ryanair, Wizz Air and dozens of other airlines.",
        distanceKm: "~600 km",
        travelTime: "6–9 hrs",
        href: "/minsk-warsaw-airport",
        hrefRu: "/трансфер-минск-варшава-шопен",
        isAvailable: true,
      },
      {
        cityRu: "Аэропорт Варшавы Модлин",
        cityEn: "Warsaw Modlin Airport",
        descRu: "Бюджетный аэропорт в 40 км к северу от Варшавы. Рейсы Ryanair в города Европы.",
        descEn: "Budget airport 40 km north of Warsaw. Ryanair flights across Europe.",
        distanceKm: "~620 km",
        travelTime: "6.5–9 hrs",
        href: "/minsk-warsaw-modlin-airport",
        hrefRu: "/трансфер-минск-варшава-модлин",
        isAvailable: true,
      },
      {
        cityRu: "Гданьск",
        cityEn: "Gdańsk",
        descRu: "Жемчужина Балтийского побережья. Длинный рынок, кран Журав, базилика Святой Марии, мировая столица янтаря.",
        descEn: "Jewel of the Baltic coast. Long Market, Żuraw crane, St Mary's Basilica, world amber capital.",
        distanceKm: "~750 km",
        travelTime: "8–11 hrs",
        href: "/minsk-gdansk-transfer",
        hrefRu: "/трансфер-минск-гданьск",
        isAvailable: true,
      },
      {
        cityRu: "Вроцлав",
        cityEn: "Wrocław",
        descRu: "Город мостов и гномов. Рыночная площадь Rynek, остров Тумский, более 100 мостов через Одер.",
        descEn: "City of bridges and dwarfs. Rynek Market Square, Cathedral Island, 100+ bridges over the Oder.",
        distanceKm: "~850 km",
        travelTime: "9–12 hrs",
        href: "/minsk-wroclaw-transfer",
        hrefRu: "/трансфер-минск-вроцлав",
        isAvailable: true,
      },
      {
        cityRu: "Краков",
        cityEn: "Kraków",
        descRu: "Королевская столица Польши. Вавельский замок, Главная площадь, Казимеж, Величкская соляная шахта.",
        descEn: "Poland's royal capital. Wawel Castle, Main Market Square, Kazimierz, Wieliczka Salt Mine.",
        distanceKm: "~750 km",
        travelTime: "8–11 hrs",
        href: "/minsk-krakow-transfer",
        hrefRu: "/трансфер-минск-краков",
        isAvailable: true,
      },
      {
        cityRu: "Варшава — центр города",
        cityEn: "Warsaw — city centre",
        descRu: "Деловые поездки, шопинг, туризм. Доставка до отеля, офиса или торгового центра.",
        descEn: "Business trips, shopping, tourism. Delivery to your hotel, office or shopping centre.",
        distanceKm: "~600 km",
        travelTime: "6–9 hrs",
        href: "/warsaw-transfer",
        hrefRu: "/трансфер-варшава",
        isAvailable: true,
      },
    ],
    infoTitle: "Useful information",
    infoRows: [
      { label: "Border crossing", value: "Bruzgi / Kuźnica or Byaroza / Połowce (Belarus–Poland)" },
      { label: "Border crossing time", value: "1–8 hrs depending on season and queues" },
      { label: "Documents required", value: "Schengen visa, valid passport" },
      { label: "Currency", value: "Polish złoty (PLN)" },
      { label: "Languages", value: "Polish (official), English widely spoken in cities and tourist areas" },
    ],
    includedTitle: "What's included in every transfer",
    included: [
      "Pickup from your Minsk address",
      "Direct route — no transfers",
      "Driver assistance at the border",
      "Bottled water and comfortable cabin",
      "Child seats on request",
      "Fixed price — no meter, no surprises",
    ],
    ctaTitle: "Book a Poland Transfer",
    ctaDesc: "Tell us your route and number of passengers — we'll send an exact price within 15 minutes.",
    ctaBtn: "Request a booking",
    backBtn: "← Europe transfers",
    soonLabel: "Coming soon",
    bookLabel: "Request price",
    detailsLabel: "View details",
  },
  seo: {
    titleRu: "Трансфер Минск — Польша | Варшава, WAW, Модлин | ComfortLine",
    titleEn: "Minsk to Poland Transfer | Warsaw, WAW, Modlin | ComfortLine",
    descRu: "Прямые трансферы из Минска в Польшу: аэропорт Шопен (WAW), аэропорт Модлин, центр Варшавы. Фиксированная цена, без пересадок.",
    descEn: "Direct transfers from Minsk to Poland: Warsaw Chopin (WAW), Modlin Airport, Warsaw city centre. Fixed prices, door-to-door.",
    pathRu: "/трансфер-в-польшу",
    pathEn: "/poland-transfer",
    breadcrumbRu: "Трансферы в Польшу",
    breadcrumbEn: "Poland Transfers",
  },
};

export default function PolandTransferPage() {
  return <CountryTransferPage data={data} />;
}
