import { MapPin, ShieldCheck, Building2 } from "lucide-react";
import { RouteLandingPage, RoutePageData } from "./route-landing-page";

const data: RoutePageData = {
  ru: {
    badge: "Трансфер в Ригу",
    title: "Минск — Рига",
    subtitle: "Прямой трансфер из Минска в центр Риги. Деловые поездки, отдых на Балтийском побережье или транзит через Латвию — без пересадок и автобусов.",
    stats: [
      { label: "Расстояние", value: "~470 км" },
      { label: "Время в пути", value: "5–7 ч" },
      { label: "Граница", value: "Беларусь–Латвия" },
      { label: "Класс авто", value: "Бизнес / Минивэн" },
    ],
    photosTitle: "Рига — достопримечательности",
    photos: [
      { src: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Views_from_St._Peter%27s_Church_Spire%2C_Riga_20180808-2.jpg/1280px-Views_from_St._Peter%27s_Church_Spire%2C_Riga_20180808-2.jpg", caption: "Старый город Риги" },
      { src: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/House_of_Blackheads_at_Dusk_3%2C_Riga%2C_Latvia_-_Diliff.jpg/1280px-House_of_Blackheads_at_Dusk_3%2C_Riga%2C_Latvia_-_Diliff.jpg", caption: "Дом Черноголовых" },
      { src: "https://images.pexels.com/photos/7245326/pexels-photo-7245326.jpeg?auto=compress&cs=tinysrgb&w=800", caption: "Балтийское побережье" },
    ],
    howTitle: "Как проходит поездка",
    steps: [
      { icon: MapPin, title: "Выезд из Минска", desc: "Водитель заберёт вас по указанному адресу в Минске и направится к латвийской границе." },
      { icon: ShieldCheck, title: "Граница Беларусь–Латвия", desc: "Переход Урбаны / Патарниеки. Водитель знает актуальные очереди и помогает на КПП." },
      { icon: Building2, title: "Рига: любой адрес", desc: "Старый город, аэропорт RIX, отель или Юрмала — доставим точно по назначению." },
    ],
    infoTitle: "Детали маршрута",
    infoRows: [
      { label: "Маршрут", value: "Минск → Полоцк → Урбаны → Даугавпилс → Рига" },
      { label: "Расстояние", value: "~470 км" },
      { label: "Пограничный переход", value: "Урбаны / Патарниеки (Беларусь–Латвия)" },
      { label: "Время пересечения границы", value: "1–6 ч в зависимости от очереди" },
      { label: "Необходимые документы", value: "Виза Шенген (для граждан не ЕС), загранпаспорт" },
    ],
    includedTitle: "Что включено",
    included: [
      "Подача от адреса в Минске",
      "Прямой маршрут без пересадок",
      "Помощь водителя на границе",
      "Питьевая вода и комфортный салон",
      "Детские кресла по запросу",
      "Фиксированная цена без счётчика",
    ],
    whyTitle: "Почему ComfortLine",
    whyItems: [
      "Регулярные рейсы в Ригу с 2015 года",
      "Водитель знает переход Урбаны и очереди",
      "Можно добавить остановку в Юрмале",
      "Обратный трансфер: из Риги в Минск",
      "Работаем 24/7, включая праздники",
      "Перевозим с детьми и питомцами",
    ],
    ctaTitle: "Заказать трансфер Минск–Рига",
    ctaDesc: "Оставьте заявку — менеджер свяжется с вами в течение 15 минут и назовёт точную стоимость.",
    ctaBtn: "Оставить заявку",
    prefilledFrom: "Минск",
    prefilledTo: "Рига",
    backBtn: "← Все услуги",
  },
  en: {
    badge: "Riga Transfer",
    title: "Minsk — Riga",
    subtitle: "Direct private transfer from Minsk to Riga city centre. Business meetings, Baltic seaside breaks or onward travel through Latvia — no changes, no buses.",
    stats: [
      { label: "Distance", value: "~470 km" },
      { label: "Travel time", value: "5–7 hrs" },
      { label: "Border", value: "Belarus–Latvia" },
      { label: "Vehicle class", value: "Business / Minivan" },
    ],
    photosTitle: "Riga — Highlights",
    photos: [
      { src: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Views_from_St._Peter%27s_Church_Spire%2C_Riga_20180808-2.jpg/1280px-Views_from_St._Peter%27s_Church_Spire%2C_Riga_20180808-2.jpg", caption: "Riga Old Town" },
      { src: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/House_of_Blackheads_at_Dusk_3%2C_Riga%2C_Latvia_-_Diliff.jpg/1280px-House_of_Blackheads_at_Dusk_3%2C_Riga%2C_Latvia_-_Diliff.jpg", caption: "House of the Blackheads" },
      { src: "https://images.pexels.com/photos/7245326/pexels-photo-7245326.jpeg?auto=compress&cs=tinysrgb&w=800", caption: "Baltic seaside" },
    ],
    howTitle: "How the transfer works",
    steps: [
      { icon: MapPin, title: "Departure from Minsk", desc: "Your driver picks you up at your Minsk address and heads for the Latvian border." },
      { icon: ShieldCheck, title: "Belarus–Latvia border", desc: "Urbany / Pāternieki crossing. Your driver knows current queue conditions and assists at the checkpoint." },
      { icon: Building2, title: "Riga — any address", desc: "Old Town, RIX Airport, your hotel or Jūrmala beach — wherever you need to go." },
    ],
    infoTitle: "Route Details",
    infoRows: [
      { label: "Route", value: "Minsk → Polotsk → Urbany → Daugavpils → Riga" },
      { label: "Distance", value: "~470 km" },
      { label: "Border crossing", value: "Urbany / Pāternieki (Belarus–Latvia)" },
      { label: "Border crossing time", value: "1–6 hrs depending on queues" },
      { label: "Documents required", value: "Schengen visa (non-EU citizens), valid passport" },
    ],
    includedTitle: "What's included",
    included: [
      "Pickup from your Minsk address",
      "Direct route — no transfers",
      "Driver assistance at the border",
      "Bottled water and comfortable cabin",
      "Child seats on request",
      "Fixed price — no meter, no surprises",
    ],
    whyTitle: "Why ComfortLine",
    whyItems: [
      "Regular Riga runs since 2015",
      "Driver familiar with Urbany crossing and queues",
      "Optional stop at Jūrmala beach on request",
      "Return transfer Riga → Minsk also available",
      "Available 24/7 including public holidays",
      "Kids and pets welcome",
    ],
    ctaTitle: "Book Minsk–Riga Transfer",
    ctaDesc: "Submit a request and our manager will contact you within 15 minutes with an exact price.",
    ctaBtn: "Request a booking",
    prefilledFrom: "Minsk",
    prefilledTo: "Riga",
    backBtn: "← All services",
  },
  seo: {
    titleRu: "Трансфер Минск — Рига | Прямая поездка в Латвию | ComfortLine",
    titleEn: "Minsk to Riga Transfer | Direct Ride to Latvia | ComfortLine",
    descRu: "Прямой трансфер из Минска в центр Риги. ~470 км, 5–7 ч. Старый город, аэропорт RIX, Юрмала. Фиксированная цена, опытный водитель, граница Беларусь–Латвия.",
    descEn: "Direct transfer from Minsk to central Riga. ~470 km, 5–7 hrs. Old Town, RIX airport, Jurmala. Fixed price, professional driver, Belarus–Latvia border crossing.",
    pathRu: "/трансфер-рига",
    pathEn: "/riga-transfer",
    breadcrumbRu: "Трансфер в Ригу",
    breadcrumbEn: "Minsk — Riga",
    fromName: "Минск",
    toName: "Рига",
  },
};

export default function RigaTransferPage() {
  return <RouteLandingPage data={data} />;
}
