import { MapPin, Users, CheckCircle2 } from "lucide-react";
import { RouteLandingPage, RoutePageData } from "./route-landing-page";

const data: RoutePageData = {
  ru: {
    badge: "Трансфер в санаторий",
    title: "Трансфер в санатории Беларуси",
    subtitle: "Доставим вас от двери дома или аэропорта прямо к корпусу санатория. Нарочь, Браслав, Жлобин, Беловежская Пуща — комфорт без пересадок на электричках и автобусах.",
    stats: [
      { label: "Маршруты", value: "Все санатории РБ" },
      { label: "Багаж", value: "Без ограничений" },
      { label: "Подача", value: "Из любой точки" },
      { label: "Класс авто", value: "Седан / Минивэн" },
    ],
    photosTitle: "Здравницы Беларуси",
    photos: [
      { src: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/%D0%A1%D0%B0%D0%BD%D0%B0%D1%82%D0%BE%D1%80%D0%B8%D0%B9_%D0%9D%D0%B0%D1%80%D0%BE%D1%87%D1%8C_%D0%B2%D0%B8%D0%B4_%D1%81_%D0%BE%D0%B7%D0%B5%D1%80%D0%B0.jpg/1280px-%D0%A1%D0%B0%D0%BD%D0%B0%D1%82%D0%BE%D1%80%D0%B8%D0%B9_%D0%9D%D0%B0%D1%80%D0%BE%D1%87%D1%8C_%D0%B2%D0%B8%D0%B4_%D1%81_%D0%BE%D0%B7%D0%B5%D1%80%D0%B0.jpg", caption: "Санаторий «Нарочь»" },
      { src: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/%D0%A1%D0%B0%D0%BD%D0%B0%D1%82%D0%BE%D1%80%D0%B8%D0%B9_%22%D0%A1%D0%BF%D1%83%D1%82%D0%BD%D0%B8%D0%BA%22_-_panoramio.jpg/1280px-%D0%A1%D0%B0%D0%BD%D0%B0%D1%82%D0%BE%D1%80%D0%B8%D0%B9_%22%D0%A1%D0%BF%D1%83%D1%82%D0%BD%D0%B8%D0%BA%22_-_panoramio.jpg", caption: "Санаторий «Спутник»" },
      { src: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Sanatoriy_Krinica.jpg", caption: "Санаторий «Криница»" },
    ],
    howTitle: "Как проходит поездка",
    steps: [
      { icon: MapPin, title: "Подача к адресу", desc: "Заберём вас от дома, аэропорта или вокзала в назначенное время — без долгого ожидания." },
      { icon: Users, title: "Комфорт всей семье", desc: "Помощь с багажом, удобный салон, остановки по запросу. Перевозим с пожилыми пассажирами и детьми." },
      { icon: CheckCircle2, title: "Прямо к корпусу", desc: "Доставим прямо к нужному корпусу санатория — не нужно идти с чемоданами." },
    ],
    infoTitle: "Популярные направления",
    infoRows: [
      { label: "Минск — Нарочь", value: "~160 км, 2–2,5 ч" },
      { label: "Минск — Браслав", value: "~240 км, 3–3,5 ч" },
      { label: "Минск — Беловежская Пуща", value: "~370 км, 4,5–5 ч" },
      { label: "Минск — Жлобин / Бобруйск", value: "~150–170 км, 2–2,5 ч" },
      { label: "Аэропорт Минск — любой санаторий", value: "Прямой трансфер без посадок" },
    ],
    includedTitle: "Что включено",
    included: [
      "Подача в любую точку Беларуси",
      "Помощь с багажом и сумками",
      "Остановки по запросу (туалет, кафе)",
      "Сопровождение пожилых пассажиров",
      "Детские кресла и бустеры по запросу",
      "Фиксированная цена в обе стороны",
    ],
    whyTitle: "Почему ComfortLine",
    whyItems: [
      "Доставка прямо к корпусу санатория",
      "Возможен трансфер «туда-обратно» через 7–14–21 день",
      "Чистый и просторный салон",
      "Возможность перевозки с домашним питомцем",
      "Опытные водители — спокойная и плавная езда",
      "Работаем 24/7 — рейс в любое время",
    ],
    ctaTitle: "Заказать трансфер в санаторий",
    ctaDesc: "Оставьте заявку — менеджер свяжется в течение 15 минут, уточнит санаторий и назовёт точную стоимость в обе стороны.",
    ctaBtn: "Оставить заявку",
    prefilledFrom: "Минск",
    prefilledTo: "Санаторий",
    backBtn: "← Все услуги",
    faqTitle: "Частые вопросы — трансфер в санатории",
    faq: [
      { q: "Сколько стоит трансфер из Минска в санаторий «Нарочь»?", a: "Цена — по запросу, свяжитесь с нами. Стоимость зависит от класса авто (бизнес-седан 1–3 пассажира или минивэн 4–8), необходимости детского кресла, поездки с домашним животным, конкретного санатория и даты, а также других пожеланий клиента. Маршрут до Нарочи ~160 км, время в пути 2–2,5 часа. Менеджер озвучит фиксированную сумму с включёнными топливом, страховкой, помощью с багажом и подачей от любого адреса в Минске." },
      { q: "До каких санаториев вы возите?", a: "Все санатории Беларуси: Нарочь и Сосны (озеро Нарочь), Лесные озёра и Браславские озёра, «Спутник», «Криница», «Журавушка», Беловежская Пуща, Жлобин, Бобруйск, Могилёвская и Брестская области. Доставляем точно к нужному корпусу — без долгих прогулок с чемоданами." },
      { q: "Подаёте ли вы прямо из аэропорта Минск-2?", a: "Да. Встретим у выхода из терминала с табличкой и доставим прямо к корпусу санатория без пересадок и автобусов. Из аэропорта в Нарочь — около 3 часов." },
      { q: "Можно ли заказать обратный трансфер заранее?", a: "Да, чаще всего так и делают: бронируете «туда и обратно» одной заявкой, мы фиксируем дату возврата (через 7, 14 или 21 день). Скидка 5% на пару поездок. За день до возврата водитель уточнит точное время выезда." },
      { q: "Можно ли с пожилым пассажиром или ребёнком?", a: "Да — это наш основной профиль. Помогаем сесть/встать, грузим всё в багажник сами, везём плавно без резких манёвров. Детские кресла — бесплатно по запросу. Можно делать остановки в дороге каждые 1,5–2 часа." },
      { q: "А с домашним животным?", a: "Везём кошек и собак мелких/средних пород в переноске или на коврике. Предупредите менеджера при заказе — подадим машину с защитным чехлом (небольшая доплата за подготовку салона)." },
    ],
  },
  en: {
    badge: "Resort Transfer",
    title: "Transfer to Belarus Resorts",
    subtitle: "Door-to-door transfers from home or airport directly to your resort building. Naroch, Braslav, Zhlobin, Belovezhskaya Pushcha — no train changes, no shuttle buses.",
    stats: [
      { label: "Destinations", value: "All Belarus resorts" },
      { label: "Luggage", value: "No limits" },
      { label: "Pickup", value: "From anywhere" },
      { label: "Vehicle", value: "Sedan / Minivan" },
    ],
    photosTitle: "Belarus Resorts",
    photos: [
      { src: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/%D0%A1%D0%B0%D0%BD%D0%B0%D1%82%D0%BE%D1%80%D0%B8%D0%B9_%D0%9D%D0%B0%D1%80%D0%BE%D1%87%D1%8C_%D0%B2%D0%B8%D0%B4_%D1%81_%D0%BE%D0%B7%D0%B5%D1%80%D0%B0.jpg/1280px-%D0%A1%D0%B0%D0%BD%D0%B0%D1%82%D0%BE%D1%80%D0%B8%D0%B9_%D0%9D%D0%B0%D1%80%D0%BE%D1%87%D1%8C_%D0%B2%D0%B8%D0%B4_%D1%81_%D0%BE%D0%B7%D0%B5%D1%80%D0%B0.jpg", caption: "Naroch Resort" },
      { src: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/%D0%A1%D0%B0%D0%BD%D0%B0%D1%82%D0%BE%D1%80%D0%B8%D0%B9_%22%D0%A1%D0%BF%D1%83%D1%82%D0%BD%D0%B8%D0%BA%22_-_panoramio.jpg/1280px-%D0%A1%D0%B0%D0%BD%D0%B0%D1%82%D0%BE%D1%80%D0%B8%D0%B9_%22%D0%A1%D0%BF%D1%83%D1%82%D0%BD%D0%B8%D0%BA%22_-_panoramio.jpg", caption: "Sputnik Resort" },
      { src: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Sanatoriy_Krinica.jpg", caption: "Krinitsa Resort" },
    ],
    howTitle: "How the transfer works",
    steps: [
      { icon: MapPin, title: "Pickup at your address", desc: "We collect you from home, the airport or the station at the agreed time — no long waits." },
      { icon: Users, title: "Comfort for the whole family", desc: "Luggage assistance, comfortable cabin, on-request stops. Suitable for elderly passengers and children." },
      { icon: CheckCircle2, title: "Right to the building", desc: "We drop you off directly at the correct resort building — no walking with suitcases." },
    ],
    infoTitle: "Popular destinations",
    infoRows: [
      { label: "Minsk — Naroch", value: "~160 km, 2–2.5 hrs" },
      { label: "Minsk — Braslav", value: "~240 km, 3–3.5 hrs" },
      { label: "Minsk — Belovezhskaya Pushcha", value: "~370 km, 4.5–5 hrs" },
      { label: "Minsk — Zhlobin / Bobruisk", value: "~150–170 km, 2–2.5 hrs" },
      { label: "Minsk Airport — any resort", value: "Direct transfer, no stops" },
    ],
    includedTitle: "What's included",
    included: [
      "Pickup anywhere in Belarus",
      "Help with luggage and bags",
      "On-request stops (restroom, café)",
      "Assistance for elderly passengers",
      "Child seats and boosters on request",
      "Fixed return price both ways",
    ],
    whyTitle: "Why ComfortLine",
    whyItems: [
      "Drop-off at the exact resort building",
      "Round-trip option: pickup after 7–14–21 days",
      "Clean and spacious cabin",
      "Pets welcome on request",
      "Experienced drivers — calm, smooth driving",
      "24/7 — depart anytime",
    ],
    ctaTitle: "Book a Resort Transfer",
    ctaDesc: "Submit a request — our manager will reach out within 15 minutes, confirm the resort and quote a fixed return price.",
    ctaBtn: "Request a booking",
    prefilledFrom: "Minsk",
    prefilledTo: "Resort",
    backBtn: "← All services",
    faqTitle: "Frequently asked — Belarus resort transfers",
    faq: [
      { q: "How much is a transfer from Minsk to Naroch resort?", a: "Price is on request — please contact us. The exact figure depends on the vehicle class (business sedan for 1–3 passengers or minivan for 4–8), whether you need a child seat, whether you travel with a pet, the chosen resort and date, and any other special requests. The route to Naroch is ~160 km, around 2–2.5 hours one way. Our manager confirms a fixed price with fuel, insurance, luggage help and pickup from any Minsk address already included." },
      { q: "Which Belarusian resorts do you serve?", a: "All major Belarus sanatoriums and resorts: Naroch and Sosny (Lake Naroch), Forest Lakes and Braslav Lakes, Sputnik, Krinitsa, Zhuravushka, Belovezhskaya Pushcha, Zhlobin, Bobruisk and resorts across Mogilev and Brest regions. We drop you right at the building — no long walk with suitcases." },
      { q: "Can you pick us up directly from Minsk Airport (MSQ)?", a: "Yes. We meet you at the terminal exit with a name sign and drive straight to your resort, no buses or transfers. Airport to Naroch is about 3 hours." },
      { q: "Can I book the return transfer in advance?", a: "Yes — most clients do. Book round-trip in one request and we fix the return date (after 7, 14 or 21 days). 5% discount on the pair. The driver confirms the exact return time the day before." },
      { q: "Is it suitable for elderly passengers or small children?", a: "Yes — this is our specialty. We help with boarding, load all luggage ourselves, drive smoothly without sudden manoeuvres. Child seats are free on request. Stops every 1.5–2 hours en route are no problem." },
      { q: "Can I travel with a pet?", a: "Yes — small and medium cats and dogs in a carrier or on a mat. Let the manager know at booking — we'll bring a car with a protective seat cover (small cabin-prep surcharge applies)." },
    ],
  },
  seo: {
    titleRu: "Трансфер в санатории Беларуси | Нарочь, Браслав, Беловежская Пуща | ComfortLine",
    titleEn: "Belarus Resort Transfer | Naroch, Braslav, Belovezhskaya | ComfortLine",
    descRu: "Трансфер в санатории Беларуси: Нарочь, Браслав, Беловежская Пуща, Жлобин и др. От двери дома или аэропорта прямо к корпусу санатория. Помощь с багажом, удобно с детьми и пожилыми.",
    descEn: "Transfer to Belarus resorts — Naroch, Braslav, Belovezhskaya Pushcha, Zhlobin. Door-to-door from home or airport directly to the resort building. Luggage help, family-friendly.",
    pathRu: "/трансфер-в-санаторий",
    pathEn: "/sanatorium-transfer",
    breadcrumbRu: "Трансфер в санаторий",
    breadcrumbEn: "Resort Transfer",
    fromName: "Минск",
    toName: "Санаторий",
    priceCurrency: "EUR",
  },
};

export default function SanatoriumTransferPage() {
  return <RouteLandingPage data={data} />;
}
