import { MapPin, ShieldCheck, Building2 } from "lucide-react";
import { RouteLandingPage, RoutePageData } from "./route-landing-page";


const data: RoutePageData = {
  ru: {
    badge: "Трансфер в Варшаву",
    title: "Минск — Варшава",
    subtitle: "Комфортный трансфер из Минска в центр Варшавы. Прямая поездка без пересадок — деловые встречи, шоппинг, отдых или транзит через Польшу.",
    stats: [
      { label: "Расстояние", value: "~550 км" },
      { label: "Время в пути", value: "6–8 ч" },
      { label: "Граница", value: "Беларусь–Польша" },
      { label: "Класс авто", value: "Бизнес / Минивэн" },
    ],
    photosTitle: "Варшава — достопримечательности",
    photos: [
      { src: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Royal_Castle_in_Warsaw%2C_Poland%2C_2022%2C_03.jpg/1280px-Royal_Castle_in_Warsaw%2C_Poland%2C_2022%2C_03.jpg", caption: "Королевский замок (Старый город)" },
      { src: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Lotnisko_Chopina_w_Warszawie_2018b.jpg/1280px-Lotnisko_Chopina_w_Warszawie_2018b.jpg", caption: "Аэропорт Варшавы Шопен (WAW)" },
    ],
    howTitle: "Как проходит поездка",
    steps: [
      { icon: MapPin, title: "Выезд из Минска", desc: "Водитель заберёт вас по указанному адресу в Минске и направится к польской границе." },
      { icon: ShieldCheck, title: "Граница Беларусь–Польша", desc: "Переход на Тересполь или Кукурыки. Водитель знает актуальные очереди и помогает на КПП." },
      { icon: Building2, title: "Варшава: любой адрес", desc: "Отель в центре, Центральный вокзал, торговый центр или деловой район — куда скажете." },
    ],
    infoTitle: "Детали маршрута",
    infoRows: [
      { label: "Маршрут", value: "Минск → Брест → Тересполь → Варшава" },
      { label: "Расстояние", value: "~550 км" },
      { label: "Пограничный переход", value: "Тересполь / Кукурыки (Беларусь–Польша)" },
      { label: "Время пересечения границы", value: "1–5 ч в зависимости от очереди" },
      { label: "Необходимые документы", value: "Виза Шенген (для граждан не ЕС), загранпаспорт" },
    ],
    includedTitle: "Что включено",
    included: [
      "Подача от адреса в Минске",
      "Прямой маршрут без пересадок",
      "Помощь водителя на границе",
      "Питьевая вода и комфортный салон",
      "Детские кресла по запросу",
      "Фиксированная цена без счётчика",
    ],
    whyTitle: "Почему ComfortLine",
    whyItems: [
      "Регулярные поездки в Варшаву с 2015 года",
      "Водитель знает переходы и очереди",
      "Можно добавить остановки по пути",
      "Обратный трансфер: из Варшавы в Минск",
      "Работаем 24/7, включая праздники",
      "Отзывы реальных клиентов на сайте",
    ],
    faqTitle: "Частые вопросы — Минск–Варшава",
    faq: [
      { q: "Сколько стоит трансфер из Минска в Варшаву?", a: "Фиксированная цена от 250 € за машину (1–4 пассажира) на бизнес-седане. Минивэн на 5–8 пассажиров — от 320 €. В стоимость уже включены топливо, страховка, помощь на границе, бутилированная вода и багаж без ограничений. Точная сумма зависит от конечного адреса в Варшаве и сезона — менеджер подтвердит её при бронировании." },
      { q: "Сколько занимает дорога Минск–Варшава?", a: "Сама дорога ~550 км по трассе М1/A2 занимает 6–8 часов. К этому добавляется пограничный переход Брест–Тересполь или Кукурыки — обычно 1–3 часа, в пиковые дни до 5 часов. Итог: планируйте 7–11 часов в одну сторону." },
      { q: "Какой пограничный переход вы используете?", a: "По умолчанию Брест–Тересполь как самый удобный для пассажирских автомобилей. При сильных очередях водитель может перенаправить на Песчатка–Половцы или Кукурыки (грузовой/легковой) — выбор делается утром по актуальной обстановке." },
      { q: "Какие документы нужны для въезда в Польшу?", a: "Действующий загранпаспорт и шенгенская виза (для граждан, которым она требуется). Граждане ЕС/Польши — только паспорт или ID-карта. Дети — собственный загранпаспорт. Рекомендуем иметь медстраховку с покрытием Шенгенской зоны." },
      { q: "Можно ли сделать остановку по дороге?", a: "Да. Бесплатно — техническая остановка на АЗС каждые 2 часа. Доплачиваемые остановки: заехать в Брестскую крепость, в торговый центр в Бресте или в Тересполе обменять валюту — 15–20 € за остановку до 30 минут. Заранее предупредите менеджера." },
      { q: "Доступен ли обратный трансфер Варшава–Минск?", a: "Да, обратный трансфер бронируется одной заявкой и стоит так же, как и в одну сторону. Если бронируете оба направления вместе — скидка 5%. Подача в Варшаве: отель, аэропорт WAW/WMI, Центральный вокзал — куда удобно." },
      { q: "Какой автомобиль подадут?", a: "По умолчанию Mercedes-Benz E-class (бизнес-седан, 1–4 пассажира) или Volkswagen Passat (комфорт, 1–4 пассажира). Для группы 5–8 человек — минивэн Hyundai Palisade или Kia Carnival. Все автомобили не старше 5 лет, с кондиционером и Wi-Fi." },
    ],
    ctaTitle: "Заказать трансфер Минск–Варшава",
    ctaDesc: "Оставьте заявку — менеджер свяжется с вами в течение 15 минут и назовёт точную стоимость.",
    ctaBtn: "Оставить заявку",
    prefilledFrom: "Минск",
    prefilledTo: "Варшава",
    backBtn: "← Все услуги",
  },
  en: {
    badge: "Warsaw Transfer",
    title: "Minsk — Warsaw",
    subtitle: "Comfortable private transfer from Minsk to Warsaw city centre. Direct, no changes — whether for business, shopping, sightseeing or onward travel across Poland.",
    stats: [
      { label: "Distance", value: "~550 km" },
      { label: "Travel time", value: "6–8 hrs" },
      { label: "Border", value: "Belarus–Poland" },
      { label: "Vehicle class", value: "Business / Minivan" },
    ],
    photosTitle: "Warsaw — Highlights",
    photos: [
      { src: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Royal_Castle_in_Warsaw%2C_Poland%2C_2022%2C_03.jpg/1280px-Royal_Castle_in_Warsaw%2C_Poland%2C_2022%2C_03.jpg", caption: "Royal Castle (Old Town)" },
      { src: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Lotnisko_Chopina_w_Warszawie_2018b.jpg/1280px-Lotnisko_Chopina_w_Warszawie_2018b.jpg", caption: "Warsaw Chopin Airport (WAW)" },
    ],
    howTitle: "How the transfer works",
    steps: [
      { icon: MapPin, title: "Departure from Minsk", desc: "Your driver picks you up at your Minsk address and heads for the Polish border." },
      { icon: ShieldCheck, title: "Belarus–Poland border", desc: "Terespol or Kukuryki crossing. Your driver knows current queue conditions and assists at the checkpoint." },
      { icon: Building2, title: "Warsaw — any address", desc: "City centre hotel, Central Station, shopping centre or business district — wherever you need." },
    ],
    infoTitle: "Route Details",
    infoRows: [
      { label: "Route", value: "Minsk → Brest → Terespol → Warsaw" },
      { label: "Distance", value: "~550 km" },
      { label: "Border crossing", value: "Terespol / Kukuryki (Belarus–Poland)" },
      { label: "Border crossing time", value: "1–5 hrs depending on queues" },
      { label: "Documents required", value: "Schengen visa (non-EU citizens), valid passport" },
    ],
    includedTitle: "What's included",
    included: [
      "Pickup from your Minsk address",
      "Direct route — no transfers",
      "Driver assistance at the border",
      "Bottled water and comfortable cabin",
      "Child seats on request",
      "Fixed price — no meter, no surprises",
    ],
    whyTitle: "Why ComfortLine",
    whyItems: [
      "Regular Warsaw runs since 2015",
      "Driver familiar with border crossings and queues",
      "Optional stops en route on request",
      "Return transfer Warsaw → Minsk also available",
      "Available 24/7 including public holidays",
      "Verified reviews from real clients",
    ],
    faqTitle: "Frequently asked — Minsk to Warsaw",
    faq: [
      { q: "How much does a Minsk to Warsaw transfer cost?", a: "Fixed price from €250 per car (1–4 passengers) in a business sedan. Minivan for 5–8 passengers — from €320. Price already includes fuel, insurance, border assistance, bottled water and unlimited luggage. The exact figure depends on your final Warsaw address and the season — the manager will confirm at booking." },
      { q: "How long does the Minsk to Warsaw drive take?", a: "The ~550 km drive on the M1/A2 highway takes 6–8 hours. Add 1–3 hours (up to 5 on peak days) for the Brest–Terespol or Kukuryki border crossing. Plan for 7–11 hours one way." },
      { q: "Which border crossing do you use?", a: "By default Brest–Terespol — the most convenient for passenger cars. If queues are heavy the driver may switch to Peschatka–Polowce or Kukuryki, decided in the morning based on live conditions." },
      { q: "What documents do I need to enter Poland?", a: "A valid passport and a Schengen visa (for nationals who need one). EU/Polish citizens — passport or national ID only. Children require their own passport. Schengen-area medical insurance is recommended." },
      { q: "Can I make stops along the way?", a: "Yes. Free technical stops at petrol stations every 2 hours. Paid stops — Brest Fortress, a Brest shopping centre or a currency exchange in Terespol — €15–20 each for up to 30 minutes. Just let the manager know in advance." },
      { q: "Is the return transfer Warsaw to Minsk available?", a: "Yes, the return is booked in a single request at the same one-way rate. Book both directions together — 5% discount. Pickup in Warsaw: hotel, WAW/WMI airport, Central Station — wherever suits you." },
      { q: "Which vehicle will I get?", a: "By default a Mercedes-Benz E-class (business sedan, 1–4 passengers) or Volkswagen Passat (comfort, 1–4 passengers). For 5–8 passengers — a Hyundai Palisade or Kia Carnival minivan. All vehicles are no more than 5 years old, with A/C and Wi-Fi." },
    ],
    ctaTitle: "Book Minsk–Warsaw Transfer",
    ctaDesc: "Submit a request and our manager will contact you within 15 minutes with an exact price.",
    ctaBtn: "Request a booking",
    prefilledFrom: "Minsk",
    prefilledTo: "Warsaw",
    backBtn: "← All services",
  },
  seo: {
    titleRu: "Трансфер Минск — Варшава | Прямая поездка в центр Варшавы | ComfortLine",
    titleEn: "Minsk to Warsaw Transfer | Direct Ride to Warsaw City | ComfortLine",
    descRu: "Прямой трансфер из Минска в центр Варшавы. ~550 км, 6–8 ч. Деловые поездки, шоппинг, отдых. Фиксированная цена, опытный водитель, помощь на границе Беларусь–Польша.",
    descEn: "Direct transfer from Minsk to central Warsaw. ~550 km, 6–8 hrs. Business, shopping, leisure. Fixed price, professional driver, assistance at the Belarus–Poland border.",
    pathRu: "/трансфер-варшава",
    pathEn: "/warsaw-transfer",
    breadcrumbRu: "Трансфер в Варшаву",
    breadcrumbEn: "Minsk — Warsaw",
    fromName: "Минск",
    toName: "Варшава",
    priceFrom: 250,
    priceCurrency: "EUR",
  },
};

export default function WarsawTransferPage() {
  return <RouteLandingPage data={data} />;
}
