#!/usr/bin/env node
/**
 * IndexNow submission script.
 * Reads public/sitemap.xml, extracts all <loc> URLs, and submits them to IndexNow.
 * Yandex, Bing, Seznam, Naver and Yep all accept IndexNow pings.
 *
 * Usage:
 *   node scripts/indexnow.mjs              # submit all sitemap URLs
 *   node scripts/indexnow.mjs <url> <url>  # submit specific URLs only
 */
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const HOST = "comfortline.by";
// Two independent IndexNow keys are hosted at the site root:
//   - c8f3d2a1... was generated for Bing's IndexNow onboarding
//   - 6b670190... was generated by Yandex Webmaster's own IndexNow tool
// The shared IndexNow protocol only needs one key per submission, so we submit
// once per key — every participating engine (Yandex, Bing, Seznam, Naver, Yep)
// accepts a ping regardless of which key generated it, but keeping both lets
// each console track submissions made "with its own" key.
const KEYS = ["c8f3d2a1b94e47f6ae7c1d0b5a8e3c92", "6b6701907fdc44cfbf707eda79e5fd70"];
const ENDPOINT = "https://api.indexnow.org/indexnow";

async function readSitemapUrls() {
  const sitemapPath = resolve(__dirname, "..", "public", "sitemap.xml");
  const xml = await readFile(sitemapPath, "utf8");
  const matches = [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)];
  return [...new Set(matches.map((m) => m[1].trim()))];
}

async function submitWithKey(key, urls) {
  const keyLocation = `https://${HOST}/${key}.txt`;
  const body = { host: HOST, key, keyLocation, urlList: urls };
  const res = await fetch(ENDPOINT, {
    method: "POST",
    headers: { "Content-Type": "application/json; charset=utf-8" },
    body: JSON.stringify(body),
  });
  const text = await res.text().catch(() => "");
  if (res.ok || res.status === 202) {
    console.log(`IndexNow accepted (${res.status}) for key ${key}.`);
  } else {
    console.error(`IndexNow rejected (${res.status}) for key ${key}: ${text}`);
    process.exitCode = 1;
  }
}

async function submit(urls) {
  if (urls.length === 0) {
    console.log("No URLs to submit.");
    return;
  }
  console.log(`Submitting ${urls.length} URL(s) to IndexNow with ${KEYS.length} key(s)…`);
  for (const key of KEYS) {
    await submitWithKey(key, urls);
  }
}

const argUrls = process.argv.slice(2).filter((a) => /^https?:\/\//.test(a));
const force = process.argv.includes("--force");

// On Replit, REPLIT_DEPLOYMENT=1 is set during production deploy builds.
// Outside deploys (local dev, CI typecheck, manual rebuilds) we skip the submission
// so we don't burn IndexNow quota or trigger spurious recrawls. Use --force to override.
const isDeploy = process.env.REPLIT_DEPLOYMENT === "1" || process.env.INDEXNOW_SUBMIT === "1";
if (!isDeploy && !force && argUrls.length === 0) {
  console.log("IndexNow: skipped (not a production deploy build). Use --force or INDEXNOW_SUBMIT=1 to override.");
  process.exit(0);
}

const urls = argUrls.length > 0 ? argUrls : await readSitemapUrls();
await submit(urls);
